import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import '../src/model.js';import '../src/presets.js';import '../src/session.js';import '../src/editing.js';import '../src/catalog-data.js';import '../src/catalog.js';
const G=globalThis.GridTone,clone=G.clone,example=clone(G.EXAMPLE_CATALOG);
function install(){return G.installCatalog(example);}
function freshPack(id){return {format:'gridtone.catalog',version:1,id,name:id,presets:[],drumkits:[],templates:[],assets:{}};}
test('built-in templates and 47 presets come from validated catalog configuration',()=>{const c=G.catalogContents();assert.equal(c.presets.length,47);assert.equal(c.templates.filter(t=>t.id.startsWith('builtin.drum.')).length,3);assert.equal(c.drumkits.length,5);assert.equal(G.validateCatalog({...G.BUILTIN_CATALOG,presets:G.PRESETS}).templates.length,71);});
test('example pack installs one sound, nine-row kit, three templates, and a real WAV',()=>{const r=install();assert.equal(r.pack.presets.length,1);assert.equal(r.pack.templates.length,3);assert.equal(r.pack.drumkits[0].rows.length,9);assert.ok(r.pack.assets['example.clink'].data.startsWith('data:audio/wav;base64,UklGR'));});
test('reimporting identical material is idempotent',()=>{install();const before=G.catalogContents();assert.equal(install().duplicate,true);assert.deepEqual(G.catalogContents(),before);});
test('changed library id cannot replace sound already used in a project',()=>{const p=clone(example);p.id='collision.pack';p.presets[0].ratio=6;assert.throws(()=>G.installCatalog(p),/冲突/);assert.equal(G.resolvePreset('example.glass').ratio,3.1);});
test('unknown engine and malicious data fail before any library mutation',()=>{const before=G.catalogContents();const p=freshPack('bad.engine');p.presets=[{...example.presets[0],id:'bad.voice',engine:'eval'}];assert.throws(()=>G.installCatalog(p));const hostile=JSON.parse('{"format":"gridtone.catalog","version":1,"id":"bad.tree","__proto__":{"polluted":true}}');assert.throws(()=>G.installCatalog(hostile));assert.deepEqual(G.catalogContents(),before);assert.equal({}.polluted,undefined);});
test('missing dependency is reported atomically',()=>{const p=freshPack('bad.dependency');p.presets=[{...example.presets[0],id:'would.partial'}];p.templates=[{...example.templates[0],id:'bad.template',presetId:'missing.voice'}];assert.throws(()=>G.installCatalog(p),/缺少音色/);assert.equal(G.resolvePreset('would.partial').missing,true);});
test('duplicate ids, unsafe ids, invalid timing, and oversized rows rejected',()=>{for(const change of [p=>p.presets.push(p.presets[0]),p=>p.presets[0].id='"><script>',p=>p.templates[0].notes[0].duration=1e9,p=>p.drumkits[0].rows.push(p.drumkits[0].rows[0])]){const p=clone(example);p.id=G.uid('bad');change(p);assert.throws(()=>G.validateCatalog(p));}});
test('custom sound applied to new track is pinned in project, original stays unchanged',()=>{install();const p=G.blankProject(),before=clone(p),t=G.getTemplate('example.answer');const r=G.applyTemplate(p,t,{mode:'new-track',bar:0});assert.deepEqual(p,before);assert.equal(r.project.tracks.length,2);assert.equal(r.project.catalog.presets[0].id,'example.glass');assert.equal(r.project.tracks[1].patterns[0].notes.length,t.notes.length);});
test('drum kit application pins sample and exposes ninth row for editing',()=>{const p=G.blankProject(),r=G.applyTemplate(p,G.getTemplate('example.beat'),{mode:'new-track',bar:0});const t=r.project.tracks[1];assert.equal(G.drumsFor(r.project,t).length,9);assert.equal(G.resolveKit(t.drumkitId,r.project).rows[8].source.type,'sample');assert.ok(r.project.assets['example.clink']);assert.doesNotThrow(()=>G.assertPlayable(r.project));});
test('two uses of a template create distinct independent pattern and note ids',()=>{const p=G.blankProject(),tpl=G.getTemplate('builtin.melody.answer');const a=G.applyTemplate(p,tpl,{mode:'new',trackId:p.tracks[0].id,bar:1});const b=G.applyTemplate(a.project,tpl,{mode:'new',trackId:p.tracks[0].id,bar:3});assert.notEqual(a.patternId,b.patternId);const t=b.project.tracks[0],one=t.patterns.find(x=>x.id===a.patternId),two=t.patterns.find(x=>x.id===b.patternId);assert.notEqual(one.notes[0].id,two.notes[0].id);assert.equal(b.project.bars,8);});
test('new insertion validates collisions without altering original arrangement',()=>{const p=G.blankProject(),before=clone(p);assert.throws(()=>G.applyTemplate(p,G.getTemplate('builtin.melody.answer'),{mode:'new',trackId:p.tracks[0].id,bar:0}),/已有片段/);assert.deepEqual(p,before);});
test('template replacement retains shared references and repeats a shorter template',()=>{const p=G.blankProject(),t=G.newTrack('drum');p.tracks=[t];t.patterns[0].bars=2;t.clips.push({id:G.uid('c'),bar:2,patternId:t.patterns[0].id});const r=G.applyTemplate(p,G.getTemplate('builtin.drum.four'),{mode:'replace',trackId:t.id,patternId:t.patterns[0].id});const out=r.project.tracks[0];assert.deepEqual(out.clips,t.clips);assert.equal(out.patterns[0].id,t.patterns[0].id);assert.equal(out.patterns[0].notes.length,2*G.getTemplate('builtin.drum.four').notes.length);});
test('oversized replacement never truncates or shifts existing clips silently',()=>{const p=G.blankProject();assert.throws(()=>G.applyTemplate(p,G.getTemplate('builtin.chords.cafg'),{mode:'replace',trackId:p.tracks[0].id,patternId:p.tracks[0].patterns[0].id}),/请选择新增/);});
test('existing track retains sound unless explicit sound replacement requested',()=>{const p=G.blankProject(),t=p.tracks[0];const a=G.applyTemplate(p,G.getTemplate('example.answer'),{mode:'new',trackId:t.id,bar:1});assert.equal(a.project.tracks[0].preset,'epiano');const b=G.applyTemplate(p,G.getTemplate('example.answer'),{mode:'new',trackId:t.id,bar:1,applySound:true});assert.equal(b.project.tracks[0].preset,'example.glass');});
test('template pitch conversion is explicit; source template and global reference retained',()=>{const p=G.blankProject();p.key=2;const tpl=G.getTemplate('example.answer'),before=clone(tpl);const r=G.applyTemplate(p,tpl,{mode:'new-track',bar:0,adapt:'key'});assert.equal(r.project.tracks[1].patterns[0].notes[0].pitch,tpl.notes[0].pitch+2);assert.deepEqual(tpl,before);assert.equal(r.project.key,2);});
test('whole-song template regenerates identity and embeds custom dependencies',()=>{const tpl=G.getTemplate('example.song'),r=G.applyTemplate(G.blankProject(),tpl);assert.notEqual(r.project.id,tpl.project.id);assert.notEqual(r.project.tracks[0].id,tpl.project.tracks[0].id);assert.equal(r.project.catalog.presets[0].id,'example.glass');assert.ok(G.compileSong(r.project).events.length>200);});
test('saved project opens in clean runtime with custom sound and drum samples, without imported library',()=>{let r=G.applyTemplate(G.blankProject(),G.getTemplate('example.answer'),{mode:'new-track',bar:0});r=G.applyTemplate(r.project,G.getTemplate('example.beat'),{mode:'new-track',bar:0});const ctx=vm.createContext({console});ctx.globalThis=ctx;for(const f of ['model','presets','session','editing','catalog-data','catalog'])vm.runInContext(fs.readFileSync(new URL('../src/'+f+'.js',import.meta.url),'utf8'),ctx);ctx.json=JSON.stringify(r.project);const result=vm.runInContext('(()=>{const p=GridTone.validateProject(JSON.parse(json));GridTone.assertPlayable(p);return {tracks:p.tracks.length,defs:p.catalog.presets.length,assets:Object.keys(p.assets).length};})()',ctx);assert.equal(result.tracks,3);assert.equal(result.defs,1);assert.equal(result.assets,1);});
test('missing sound opens with explicit diagnostic and never falls back to piano',()=>{const p=G.blankProject();p.tracks[0].preset='unknown.sound';const checked=G.validateProject(p);assert.equal(G.presetById('unknown.sound',checked).missing,true);assert.match(G.missingResources(checked)[0].message,/unknown.sound/);assert.throws(()=>G.assertPlayable(checked));});
test('missing sample stays editable and is blocked only for an audible target',()=>{const p=G.demoProject();p.tracks[0].preset='sample:not.present';const checked=G.validateProject(p);assert.throws(()=>G.assertPlayable(checked));assert.doesNotThrow(()=>G.assertPlayable(checked,[p.tracks[1].id]));});
test('track and note ids cannot escape HTML attributes in imported projects',()=>{const p=G.blankProject();p.tracks[0].id='t" onload="alert(1)';assert.throws(()=>G.validateProject(p));});
test('a project cannot silently shadow a built-in kit',()=>{const p=G.blankProject();p.catalog={presets:[],drumkits:[clone(G.BUILTIN_CATALOG.drumkits[0])]};p.catalog.drumkits[0].rows[0].name='different';assert.throws(()=>G.validateProject(p),/内置鼓组/);});
test('opening a kit with missing sample preserves repairable content and reports it',()=>{const p=G.blankProject();p.tracks=[G.newTrack('drum',0)];const kit=clone(example.drumkits[0]);kit.id='repairable.kit';kit.rows[8].source.assetId='unavailable.clink';p.catalog={presets:[],drumkits:[kit]};p.tracks[0].drumkitId=kit.id;p.tracks[0].patterns[0].notes=[G.newNote(50,0,240,.7)];const checked=G.pinDocument(G.validateProject(p));assert.equal(checked.tracks[0].patterns[0].notes[0].pitch,50);assert.ok(G.missingResources(checked).some(x=>x.message.includes('unavailable.clink')));assert.throws(()=>G.assertPlayable(checked),/unavailable.clink/);});
test('catalog refuses a drum pattern with melodic engine atomically',()=>{const pack=freshPack('invalid.trackengine');pack.templates=[clone(example.templates.find(x=>x.kind==='drum'))];pack.templates[0].id='bad.kit.pattern';pack.templates[0].presetId='epiano';const before=G.catalogContents();assert.throws(()=>G.installCatalog(pack),/类型与音色/);assert.deepEqual(G.catalogContents(),before);});
