import test from 'node:test';import assert from 'node:assert/strict';
import '../src/model.js';import '../src/presets.js';import '../src/editing.js';import '../src/music/progressions.js';import '../src/music/harmony.js';import '../src/music/generation.js';import '../src/music/ensemble.js';import '../src/catalog-data.js';import '../src/catalog.js';import '../src/music/recipes.js';
const G=globalThis.GridTone;
const permutations=a=>a.length?a.flatMap((v,i)=>permutations(a.filter((_,j)=>i!==j)).map(t=>[v,...t])):[[]];
const music=r=>r.project.tracks.filter(t=>r.trackIds.includes(t.id)).map(t=>({id:t.id,clips:t.clips.map(c=>({bar:c.bar,notes:G.musicalNotes(t.patterns.find(p=>p.id===c.patternId).notes)}))})).sort((a,b)=>a.id.localeCompare(b.id));
test('C3-T02 all 120 visual track permutations preserve ensemble music and current dependencies',()=>{const p=G.recipeProject('recipe.pop'),settings={sourceTrackId:p.tracks[0].id,sourceBar:0,bars:4,drumRole:'kick',density:'dense'},expected=music(G.generateEnsembleGroup(p,settings,42));for(const order of permutations(p.tracks)){const result=G.generateEnsembleGroup({...p,tracks:order},settings,42);assert.deepEqual(music(result),expected);for(const t of result.project.tracks)for(const pat of t.patterns)if(pat.generation)assert.equal(G.dependencyStatus(result.project,pat),'current');}});
test('C8-T06 unequal pattern lengths and offset clips preserve outside-range notes',()=>{const p=G.recipeProject('recipe.pop'),source=p.tracks[0],drums=p.tracks[1],bass=p.tracks[2];p.bars=8;source.clips.push({id:G.uid('c'),patternId:source.patterns[0].id,bar:4});drums.patterns[0].bars=2;drums.patterns[0].notes=drums.patterns[0].notes.filter(n=>n.start<2*G.BAR);drums.clips=[1,3,5].map(bar=>({id:G.uid('c'),patternId:drums.patterns[0].id,bar}));bass.clips.push({id:G.uid('c'),patternId:bass.patterns[0].id,bar:4});const original=G.clone(p),result=G.generateEnsembleGroup(p,{sourceTrackId:source.id,sourceBar:1,bars:4,drumRole:'kick',density:'dense'},12);assert.deepEqual(p,original);assert.deepEqual(result.range,[G.BAR,5*G.BAR]);assert.equal(result.clipIds.length,4);const afterBass=result.project.tracks.find(t=>t.id===bass.id);for(const clip of bass.clips){const old=bass.patterns.find(p=>p.id===clip.patternId),nextClip=afterBass.clips.find(c=>c.id===clip.id),next=afterBass.patterns.find(p=>p.id===nextClip.patternId),outside=n=>n.start+clip.bar*G.BAR<G.BAR||n.start+n.duration+clip.bar*G.BAR>5*G.BAR;assert.deepEqual(G.musicalNotes(next.notes.filter(outside)),G.musicalNotes(old.notes.filter(outside)));}const unchanged=drums.clips.at(-1),afterDrums=result.project.tracks.find(t=>t.id===drums.id);assert.deepEqual(afterDrums.patterns.find(p=>p.id===afterDrums.clips.find(c=>c.id===unchanged.id).patternId),drums.patterns[0]);});
test('C6 the 47 preset and 71 template legacy IDs retain their exact catalog definitions',async()=>{const {readFile}=await import('node:fs/promises'),{createHash}=await import('node:crypto');const current=JSON.parse(await readFile(new URL('../catalog/builtin.json',import.meta.url)));assert.equal(createHash('sha256').update(JSON.stringify(current)).digest('hex'),'2a9780f4b13ae73982046253fb315d74ffb60a0efc7545686de20d31d2e37a99');assert.equal(G.PRESETS.length,47);assert.equal(G.catalogTemplates().length,71);assert.equal(G.PROGRESSIONS.length,24);assert.equal(G.RECIPES.length,8);});
test('C5 shelf caches catalog expansion and freezes picked musical content across key changes',async()=>{await import('../src/views/template-shelf.js');const p=G.blankProject(),shelf=Object.create(G.TemplateShelf.prototype);shelf.c={getProject:()=>p,render:()=>{}};const original=G.generateProgression;let calls=0;G.generateProgression=(...args)=>{calls++;return original(...args);};try{const first=shelf.all();assert.equal(first.length,71+8+24);assert.equal(shelf.all(),first);assert.equal(calls,24);const item=first.find(t=>t.role==='texture');shelf.choose(item.id);const frozen=G.clone(shelf.selectedItem);p.key=5;shelf.all();assert.equal(calls,48);assert.deepEqual(shelf.selectedItem,frozen);assert.notDeepEqual(G.musicalNotes(shelf.item(item.id).notes),G.musicalNotes(frozen.notes));}finally{G.generateProgression=original;}});
