import test from 'node:test';import assert from 'node:assert/strict';
import '../src/model.js';import '../src/presets.js';import '../src/editing.js';import '../src/music/progressions.js';import '../src/music/harmony.js';import '../src/music/generation.js';import '../src/music/ensemble.js';import '../src/catalog-data.js';import '../src/catalog.js';import '../src/music/recipes.js';import '../src/creation/operations.js';import '../src/creation/session.js';
import '../src/creation/placement.js';
const G=globalThis.GridTone;
const setup=()=>{const p=G.recipeProject('recipe.pop'),t=p.tracks.at(-1),source=p.tracks[0],target={trackId:t.id,clipId:t.clips[0].id};return {p,t,source,target};};
test('C2 local candidate patch preserves concurrent volume and unrelated notes',()=>{const {p,t,source,target}=setup(),flow=new G.CandidateSession(p,'generate',target);flow.begin();const h=G.resolveHarmony(p,{...target,sourceTrackId:source.id});flow.ready([G.applyGenerated(p,target,G.generateMelody({harmony:h,notes:[]},{},4).candidates[0])]);const current=G.clone(p);current.tracks[2].volume=.123;current.tracks[3].patterns[0].notes[0].pitch++;const result=flow.materialize(current);assert.equal(result.project.tracks[2].volume,.123);assert.deepEqual(result.project.tracks[3],current.tracks[3]);assert.ok(result.project.tracks.at(-1).patterns[0].notes.length);assert.equal(p.tracks.at(-1).patterns[0].notes.length,0);});
test('C2 candidate rejects source edits, moved/deleted target and changed project',()=>{const {p,t,source,target}=setup(),flow=new G.CandidateSession(p,'generate',target);flow.begin();flow.ready([G.applyGenerated(p,target,G.generateMelody({harmony:G.resolveHarmony(p,{...target,sourceTrackId:source.id}),notes:[]},{},4).candidates[0])]);for(const mutate of [x=>x.tracks[0].patterns[0].notes[0].pitch++,x=>x.tracks.at(-1).clips[0].bar++,x=>x.tracks.at(-1).clips=[],x=>x.id='different']){const current=G.clone(p);mutate(current);assert.throws(()=>flow.materialize(current),/变化|切换/);}});
test('C2 cancellation isolates late work and a failed generation clears old results',()=>{const {p}=setup(),flow=new G.CandidateSession(p,'mix'),id=flow.begin();flow.cancel();assert.equal(flow.ready([{project:G.suggestedMix(p)}],id),false);flow.begin();flow.ready([{project:G.suggestedMix(p)}]);flow.invalidate();assert.throws(()=>flow.materialize(p));flow.fail(Error('invalid'));assert.equal(flow.state,'failed');assert.equal(flow.candidates.length,0);});
test('C3 onset and occupancy preserve crossing duration without inventing an attack',()=>{const {p,t}=setup();t.patterns[0].notes=[G.newNote(60,0,7680)];assert.equal(G.onsetsInRange(p,t.id,3840,7680).length,0);const n=G.soundingIntervals(p,t.id,3840,7680)[0];assert.deepEqual([n.start,n.duration,n.originalStart],[0,3840,-3840]);assert.equal(G.soundingIntervals(p,t.id,7680,9600).length,0);});
test('C3 local dependency ignores remote source edits but tracks target movement',()=>{const {p,t,source,target}=setup();p.bars=16;const distant=G.copyPattern(source.patterns[0]);source.patterns.push(distant);source.clips.push({id:G.uid('c'),patternId:distant.id,bar:8});const h=G.resolveHarmony(p,{...target,sourceTrackId:source.id});const doc=G.applyGenerated(p,target,G.generateMelody({harmony:h,notes:[]},{},4).candidates[0]).project,pat=doc.tracks.at(-1).patterns[0],clip=doc.tracks.at(-1).clips[0];doc.tracks[0].patterns[1].notes[0].pitch++;doc.tracks[0].volume=.2;assert.equal(G.dependencyStatus(doc,pat,clip),'current');clip.bar=4;assert.equal(G.dependencyStatus(doc,pat,clip),'stale');clip.bar=0;assert.equal(G.dependencyStatus(doc,pat,clip),'current');});
test('C8 requested bass range controls actual sounding pitch and density changes attacks',()=>{const {p,source}=setup(),t=p.tracks[2],target={trackId:t.id,clipId:t.clips[0].id};t.pipeline.transpose=12;const s={mode:'bass',sourceTrackId:source.id,low:72,high:84};const a=G.generateEnsemble(p,target,{...s,density:'sparse'},1),b=G.generateEnsemble(p,target,{...s,density:'dense'},1);assert.ok(a.notes.every(n=>n.pitch+12>=72&&n.pitch+12<=84));assert.ok(b.notes.length>a.notes.length);assert.notDeepEqual(G.musicalNotes(b.notes),G.musicalNotes(G.generateEnsemble(p,target,{...s,density:'dense'},13).notes));});
test('C3/C8 ensemble result and dependency validity do not depend on visual order',()=>{const {p,source}=setup();const s={sourceTrackId:source.id,sourceBar:0,bars:4,drumRole:'kick',density:'dense'},a=G.generateEnsembleGroup(p,s,42),reordered=G.clone(p);reordered.tracks.reverse();const b=G.generateEnsembleGroup(reordered,s,42);for(const id of a.trackIds){const x=a.project.tracks.find(t=>t.id===id).patterns[0],y=b.project.tracks.find(t=>t.id===id).patterns[0];assert.deepEqual(G.musicalNotes(x.notes),G.musicalNotes(y.notes));assert.equal(G.dependencyStatus(a.project,x),'current');assert.equal(G.dependencyStatus(b.project,y),'current');}});
test('C8 group failure is atomic',()=>{const {p}=setup(),before=G.clone(p);assert.throws(()=>G.generateEnsembleGroup(p,{sourceTrackId:'missing',drumRole:'kick',density:'dense'}));assert.deepEqual(p,before);});
test('C5 replacement protects boundary notes and isolates shared instances',()=>{const {p,t}=setup();p.bars=8;const pat=t.patterns[0];pat.notes=[G.newNote(60,0,2*G.BAR),G.newNote(64,3*G.BAR,400)];t.clips.push({id:G.uid('c'),patternId:pat.id,bar:4});const template={...G.catalogContents().templates.find(x=>x.type==='pattern'&&x.kind==='melodic'),bars:1,notes:[G.newNote(67,0,240)]};delete template.harmony;const options={trackId:t.id,clipId:t.clips[0].id,start:G.BAR,end:2*G.BAR,replace:true};assert.throws(()=>G.planPlacement(p,template,options),/长音/);const result=G.planPlacement(p,template,{...options,splitBoundary:true}),next=result.project.tracks.at(-1);assert.deepEqual(next.patterns[0],pat);assert.notEqual(next.clips[0].patternId,next.clips[1].patternId);assert.equal(next.patterns.at(-1).notes.find(n=>n.start===0).duration,G.BAR);assert.equal(next.patterns.at(-1).notes.find(n=>n.start===3*G.BAR).pitch,64);});
test('C6/C7 rhythm skeleton keeps exact onset, duration and rests across keys',()=>{const {p,source,target}=setup(),h=G.resolveHarmony(p,{...target,sourceTrackId:source.id}),rhythmTemplate={bars:4,slots:[{start:0,duration:480},{start:2400,duration:960},{start:3*G.BAR,duration:960}]};for(const seed of [1,19,67])for(const c of G.generateMelody({harmony:h,notes:[]},{rhythmTemplate},seed).candidates)assert.deepEqual(c.notes.map(n=>[n.start,n.duration]),rhythmTemplate.slots.map(n=>[n.start,n.duration]));});
test('C7 sixteen-bar pattern supports explicit four-bar subrange',()=>{const {p,t,source,target}=setup();p.bars=16;t.patterns[0].bars=16;t.patterns[0].notes=[G.newNote(61,10*G.BAR,120)];const harmony=G.resolveHarmony(p,{...target,sourceTrackId:source.id,start:0,end:4*G.BAR});const results=G.generateMelody({harmony,notes:t.patterns[0].notes},{start:0,end:4*G.BAR},3);assert.ok(results.candidates.length);for(const c of results.candidates)assert.deepEqual(c.notes.find(n=>n.start===10*G.BAR),t.patterns[0].notes[0]);assert.throws(()=>G.generateMelody({harmony,notes:[]},{start:0,end:16*G.BAR}),/4 \/ 8/);});
test('C7 explanation distinguishes third-beat support and unsupported non-chord labels',()=>{const h={end:4*G.BAR,events:[{start:0,duration:4*G.BAR,pitchClasses:[0,4,7]}]};assert.equal(G.explainNote(G.newNote(60,2*G.PPQ,G.PPQ),h).role,'结构支点');assert.match(G.explainNote(G.newNote(61,480,240),h).reason,/缺少明确连接依据/);const a=G.newNote(60,0,240),b=G.newNote(62,480,240),c=G.newNote(64,960,240);assert.match(G.explainNote(b,h,0,[a,b,c]).reason,/经过关系/);});

test('C2 application preserves candidate order and concurrent visual track reorder',()=>{const {p}=setup(),next=G.clone(p);next.tracks[0].patterns[0].notes.reverse();const extra=G.newNote(72,120,60);next.tracks[0].patterns[0].notes.splice(2,0,extra);const patch=G.candidatePatch(p,next);assert.deepEqual(G.applyCandidatePatch(p,patch),next);const current=G.clone(p);current.tracks.reverse();const applied=G.applyCandidatePatch(current,patch);assert.deepEqual(applied.tracks.map(t=>t.id),current.tracks.map(t=>t.id));assert.deepEqual(applied.tracks.at(-1).patterns[0].notes,next.tracks[0].patterns[0].notes);});

test('C8 performed-reference bass alignment survives humanize, swing and baking once',()=>{const {p,source}=setup(),drums=p.tracks.find(t=>t.kind==='drum'),bass=p.tracks.find(t=>t.role==='bass');p.swing=.31;drums.pipeline.humanize=38;bass.pipeline.humanize=27;bass.pipeline.transpose=12;drums.patterns[0].notes=[G.newNote(36,240,180),G.newNote(36,1200,180),G.newNote(36,2640,180)];const target={trackId:bass.id,clipId:bass.clips[0].id},candidate=G.generateEnsemble(p,target,{mode:'bass',sourceTrackId:source.id,referenceTrackId:drums.id,low:48,high:72,strategy:'align'},8),result=G.applyGenerated(p,target,candidate).project,t=result.tracks.find(t=>t.id===bass.id),pat=t.patterns[0];const reference=G.processPattern(drums.patterns[0],drums,p),actual=G.processPattern(pat,t,result);assert.equal(actual.length,reference.length);for(let i=0;i<actual.length;i++)assert.ok(Math.abs(actual[i].start-reference[i].start)<1e-7);const baked=G.clone(result),b=baked.tracks.find(t=>t.id===bass.id);b.patterns[0].notes=G.processPattern(pat,t,{...result,swing:0});b.pipeline={transpose:0,arp:'off',rate:G.STEP,humanize:0};const again=G.processPattern(b.patterns[0],b,baked);assert.deepEqual(again.map(n=>[n.pitch,n.start,n.duration]),actual.map(n=>[n.pitch,n.start,n.duration]));assert.equal(G.dependencyStatus(result,pat),'current');result.swing=.1;assert.equal(G.dependencyStatus(result,pat),'stale');});
test('C8 drum style and velocity controls have distinct output without touching other pieces',()=>{const {p}=setup(),t=p.tracks.find(t=>t.kind==='drum'),target={trackId:t.id,clipId:t.clips[0].id},base={mode:'drums',drumRole:'kick',density:'normal'};const straight=G.generateEnsemble(p,target,{...base,drumStyle:'straight'},9),four=G.generateEnsemble(p,target,{...base,drumStyle:'four'},9),soft=G.generateEnsemble(p,target,{...base,drumStyle:'straight',velocityStyle:'soft'},9);const kicks=r=>r.notes.filter(n=>n.pitch===36);assert.equal(kicks(four).length,kicks(straight).length*2);assert.ok(kicks(soft).every((n,i)=>n.velocity<kicks(straight)[i].velocity));assert.deepEqual(G.musicalNotes(four.notes.filter(n=>n.pitch!==36)),G.musicalNotes(t.patterns[0].notes.filter(n=>n.pitch!==36)));});
test('C8 accompaniment offers sustained, pulsed and arpeggiated ordinary notes',()=>{const {p,t,source,target}=setup();t.role='texture';const base={mode:'accompaniment',strategy:'support',sourceTrackId:source.id,low:60,high:84};const results=['sustain','pulse','arp'].map(textureStyle=>G.generateEnsemble(p,target,{...base,textureStyle},7));assert.ok(results[0].notes.some(n=>n.duration>G.PPQ*2));assert.ok(results[1].notes.length>results[0].notes.length);assert.ok(results[2].notes.every((n,i,a)=>!i||n.start>=a[i-1].start+a[i-1].duration));});
test('C6 applying recipe tempo updates performed dependency hashes after tempo decision',()=>{const doc=G.applyRecipe(G.demoProject(),'recipe.dance',{bar:8,tempo:true}).project;for(const t of doc.tracks.slice(4))for(const pat of t.patterns)if(pat.generation)assert.equal(G.dependencyStatus(doc,pat),'current');});
