import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {studioRuntime} from './studio-runtime.mjs';import {root} from './runtime.mjs';
const G=studioRuntime(),cx=vm.createContext({GridTone:G});cx.globalThis=cx;for(const f of ['creation/batch-placement','content/collections'])vm.runInContext(fs.readFileSync(`${root}/src/${f}.js`,'utf8'),cx);
const j=x=>JSON.parse(JSON.stringify(x));
function item(kind='melodic',bars=4,pitch=60){return {id:G.uid('test'),version:1,type:'pattern',name:'测试'+kind,role:kind==='drum'?'drums':'melody',kind,bars,key:0,scale:'major',presetId:kind==='drum'?'drums':'epiano',drumkitId:'builtin.standard',notes:[G.newNote(pitch,0,960,.7)]};}
function p0(){const p=G.blankProject();p.bars=16;p.tracks.push(G.newTrack('drum'));for(const t of p.tracks)t.clips=[];return p;}
test('C-B01 parallel uses explicit existing tracks and preserves their sounds',()=>{const p=p0(),r=G.planBatchPlacement(p,[item(),item('drum',4,36)],{mode:'parallel',bar:4,targets:p.tracks.map(t=>t.id)});assert.equal(r.project.tracks.length,2);assert.equal(r.newTrackCount,0);assert.deepEqual(j(r.placements.map(x=>x.bar)),[4,4]);assert.deepEqual(j(r.project.tracks.map(t=>t.preset)),j(p.tracks.map(t=>t.preset)));});
test('C-B02 suggested targets reuse matching free voices',()=>{const p=p0(),out=G.suggestBatchTargets(p,[item(),item('drum',4,36)],4);assert.deepEqual(j(out),j(p.tracks.map(t=>t.id)));});
test('C-B03 occupied tracks are not suggested and are never overwritten',()=>{const p=p0(),a=item();p.tracks[0].patterns[0].bars=8;p.tracks[0].clips=[{id:G.uid('c'),bar:0,patternId:p.tracks[0].patterns[0].id}];assert.equal(G.suggestBatchTargets(p,[a],0)[0],'new-track');assert.throws(()=>G.planBatchPlacement(p,[a],{mode:'parallel',bar:0,targets:[p.tracks[0].id]}));});
test('C-B04 existing plus new is an atomic mixed target plan',()=>{const p=p0(),before=JSON.stringify(p);const r=G.planBatchPlacement(p,[item(),item('drum',2,36)],{mode:'parallel',bar:4,targets:[p.tracks[0].id,'new-track']});assert.equal(r.newTrackCount,1);assert.equal(r.project.tracks.length,3);assert.equal(JSON.stringify(p),before);assert.equal(r.placements[0].newTrack,false);assert.equal(r.placements[1].newTrack,true);});
test('C-B05 ordered lengths 4+4+2 at bar5 occupy exactly ten bars',()=>{const p=p0(),r=G.planBatchPlacement(p,[item(),item(),item('melodic',2)],{mode:'series',bar:4,trackId:p.tracks[0].id});assert.deepEqual(j(r.placements.map(x=>x.bar)),[4,8,12]);assert.deepEqual(j(r.range),[4*G.BAR,14*G.BAR]);assert.equal(r.project.bars,16);});
test('C-B06 a new series creates one track, not one track per block',()=>{const r=G.planBatchPlacement(p0(),[item(),item()],{mode:'series',bar:1,trackId:'new-track'});assert.equal(r.newTrackCount,1);assert.equal(r.trackIds.length,1);});
test('C-B07 source snapshots include key mapping and original drum timing',()=>{const p=p0();p.key=2;const a=item(),r=G.planBatchPlacement(p,[a],{mode:'series',bar:4,trackId:p.tracks[0].id,adapt:'key'});assert.equal(r.project.tracks[0].patterns.at(-1).notes[0].pitch,62);assert.equal(a.notes[0].pitch,60);});
test('C-B08 invalid duplicate parallel track assignment rejects whole batch',()=>{const p=p0(),before=JSON.stringify(p);assert.throws(()=>G.planBatchPlacement(p,[item(),item()],{mode:'parallel',bar:4,targets:[p.tracks[0].id,p.tracks[0].id]}));assert.equal(JSON.stringify(p),before);});
test('C-B09 changing a relevant target invalidates candidate, unrelated track preserved',()=>{const p=p0(),items=[item()],opts={mode:'series',bar:4,trackId:p.tracks[0].id};const r=G.planBatchPlacement(p,items,opts),flow=new G.CandidateSession(p,'batch-placement',{},opts);flow.begin();flow.ready([r]);const next=G.clone(p);next.tracks[1].volume=.18;assert.equal(G.batchContextHash(next,[p.tracks[0].id]),G.batchContextHash(p,[p.tracks[0].id]));assert.equal(flow.materialize(next).project.tracks[1].volume,.18);next.tracks[0].volume=.11;assert.notEqual(G.batchContextHash(next,[p.tracks[0].id]),G.batchContextHash(p,[p.tracks[0].id]));});
test('C-B10 actual materialized plan uses exactly preview clip IDs and range',()=>{const p=p0(),r=G.planBatchPlacement(p,[item()],{mode:'series',bar:4,trackId:p.tracks[0].id}),flow=new G.CandidateSession(p,'batch-placement',{});flow.begin();flow.ready([r]);const applied=flow.materialize(p);assert.deepEqual(j(applied.clipIds),j(r.clipIds));assert.deepEqual(j(G.compileSong(applied.project)),j(G.compileSong(r.project)));});
test('C-B11 batch never accepts sounds, songs, too many items or invalid times',()=>{const p=p0();for(const type of ['sound','song','recipe'])assert.throws(()=>G.planBatchPlacement(p,[{...item(),type}],{mode:'parallel'}));for(const bar of [NaN,.5,-1,255])assert.throws(()=>G.planBatchPlacement(p,[item()],{mode:'parallel',bar}));assert.throws(()=>G.planBatchPlacement(p,Array.from({length:17},()=>item()),{mode:'parallel'}));});
class Store{constructor(values={}){this.values=values;}getItem(k){return this.values[k]??null;}setItem(k,v){this.values[k]=v;}}
test('C-L01 migration merges old catalog and wide library favorites once',()=>{const s=new Store({'legou.catalog.preferences':JSON.stringify({favorites:['old','shared'],recent:['old','shared'],tray:['a','a','b']}),'legou.library.preferences':JSON.stringify({favorites:['new','shared'],recent:['new']})}),c=new G.LibraryCollections(s);assert.deepEqual(j(c.favorites),['new','shared','old']);assert.deepEqual(j(c.tray),['a','b']);assert.deepEqual(j(c.recent),['new','old','shared']);c.favorite('old');const again=new G.LibraryCollections(s);assert.ok(!again.favorites.includes('old'));});
test('C-L02 empty tray is intentionally empty after reopening',()=>{const s=new Store(),c=new G.LibraryCollections(s);c.clearTray();assert.deepEqual(j(new G.LibraryCollections(s).tray),[]);});
test('C-L03 storage denial preserves in-window data with a truthful error',()=>{const s={getItem(){throw Error('denied');},setItem(){throw Error('denied');}},c=new G.LibraryCollections(s);c.pin('x');c.touch('y');assert.ok(c.tray.includes('x'));assert.equal(c.recent[0],'y');assert.match(c.error,/当前窗口/);});
test('C-L04 corrupted legacy collection values do not break startup',()=>{const s=new Store({'legou.catalog.preferences':JSON.stringify({favorites:1,recent:null,tray:false})}),c=new G.LibraryCollections(s);assert.deepEqual(j(c.favorites),[]);assert.deepEqual(j(c.recent),[]);});
test('C-L05 unavailable identifiers remain stored for later resource reimport',()=>{const s=new Store(),c=new G.LibraryCollections(s);c.pin('missing.future.pack');const again=new G.LibraryCollections(s);assert.ok(again.tray.includes('missing.future.pack'));});
test('C-L06 used collection comes from placed music only, not unused patterns',()=>{const p=p0(),t=p.tracks[0],pat=t.patterns[0];pat.materialIds=['abc'];assert.ok(!G.usedMaterialIds(p).has('abc'));t.clips=[{id:G.uid('c'),bar:0,patternId:pat.id}];assert.ok(G.usedMaterialIds(p).has('abc'));assert.ok(G.usedMaterialIds(p).has(t.preset));});
test('C-L07 old catalog songs still exist and copy independently',()=>{const samples=G.catalogTemplates().filter(t=>t.type==='song');assert.equal(samples.length,5);for(const sample of samples){const r=G.applyTemplate(G.blankProject(),sample);assert.notEqual(r.project.id,sample.project.id);assert.doesNotThrow(()=>G.validateProject(r.project));}});
test('C-L08 an original template records identity for the used collection',()=>{const p=p0(),template=G.catalogTemplates().find(t=>t.type==='pattern'&&t.kind==='melodic'),r=G.applyTemplate(p,template,{mode:'new',trackId:p.tracks[0].id,bar:4,applySound:false});assert.ok(G.usedMaterialIds(r.project).has(template.id));});

test('C-L09 old untagged material is identified by exact music, never a name guess',()=>{const p=p0(),x=G.catalogTemplates().find(t=>t.type==='pattern'&&t.kind==='melodic'&&t.notes.length),t=p.tracks[0];t.patterns[0].bars=x.bars;t.patterns[0].notes=G.clone(x.notes);t.clips=[{id:G.uid('c'),patternId:t.patterns[0].id,bar:0}];assert.ok(G.usedMaterialIds(p).has(x.id));t.patterns[0].notes[0].pitch++;assert.ok(!G.usedMaterialIds(p).has(x.id));});
