import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {studioRuntime} from './studio-runtime.mjs';import {root} from './runtime.mjs';
const G=studioRuntime(),cx=vm.createContext({GridTone:G});cx.globalThis=cx;vm.runInContext(fs.readFileSync(root+'/src/music/time-edit.js','utf8'),cx);
const json=x=>JSON.parse(JSON.stringify(x)),events=p=>json(G.compileSong(p).events.map(n=>[n.start,n.duration,n.pitch,n.velocity]));
function song(){const p=G.blankProject();p.bars=16;const t=p.tracks[0];t.pipeline.humanize=0;t.patterns[0].bars=8;t.patterns[0].notes=[G.newNote(60,4*G.BAR,4*G.BAR,.7)];return p;}
test('C-T01 clear outside a long note never invents attacks',()=>{const p=song(),before=events(p),r=G.editSongTime(p,{startBar:0,endBar:1,kind:'clear'}).project;assert.deepEqual(events(r),before);assert.deepEqual(json(r),json(p));});
for(const n of [1,2,3,5,7])test('C-T02 exact '+n+'-bar deletion preserves one surviving sustain',()=>{const p=song();p.tracks[0].patterns[0].notes=[G.newNote(60,0,8*G.BAR,.7)];const r=G.editSongTime(p,{startBar:0,endBar:n,kind:'delete'}).project;assert.deepEqual(events(r),[[0,(8-n)*G.BAR,60,.7]]);assert.equal(r.tracks[0].clips.length,1);assert.equal(r.tracks[0].patterns[0].bars,8-n);assert.doesNotThrow(()=>G.validateProject(json(r)));});
test('C-T03 delete the middle of one sustain joins it once',()=>{const p=song();p.tracks[0].patterns[0].notes=[G.newNote(64,G.BAR,6*G.BAR,.75)];const r=G.editSongTime(p,{startBar:2,endBar:4,kind:'delete'}).project;assert.deepEqual(events(r),[[G.BAR,4*G.BAR,64,.75]]);});
test('C-T04 clear the middle creates only the two intentional sides',()=>{const p=song();p.tracks[0].patterns[0].notes=[G.newNote(64,G.BAR,6*G.BAR,.75)];const r=G.editSongTime(p,{startBar:2,endBar:4,kind:'clear'}).project;assert.deepEqual(events(r),[[G.BAR,G.BAR,64,.75],[4*G.BAR,3*G.BAR,64,.75]]);assert.equal(r.tracks[0].patterns[0].bars,8);});
test('C-T05 all unaffected compiled notes survive humanize, swing and transpose',()=>{const p=song(),t=p.tracks[0];p.swing=.2;t.pipeline.humanize=25;t.pipeline.transpose=5;t.patterns[0].notes=[G.newNote(63,4*G.BAR+240,2*G.BAR,.65)];G.confirmHarmony(t.patterns[0],{version:1,events:[{start:0,duration:8*G.BAR,rootPitchClass:0,quality:'major'}]});const before=events(p);assert.deepEqual(events(G.editSongTime(p,{startBar:0,endBar:1,kind:'clear'}).project),before);const after=events(G.editSongTime(p,{startBar:0,endBar:1,kind:'delete'}).project);assert.deepEqual(after,before.map(([s,...rest])=>[s-G.BAR,...rest]));});
test('C-T06 shared unedited instance retains original pattern and sound events',()=>{const p=song(),t=p.tracks[0],pat=t.patterns[0];t.clips.push({id:G.uid('c'),patternId:pat.id,bar:8});const r=G.editSongTime(p,{startBar:0,endBar:1,kind:'delete'}).project;assert.deepEqual(json(r.tracks[0].patterns.find(x=>x.id===pat.id)),json(pat));assert.equal(r.tracks[0].clips[1].bar,7);assert.equal(G.compileSong(r).events.length,2);});
test('C-T07 clear harmony gaps and retained silence without splitting unrelated notes',()=>{const p=song(),pat=p.tracks[0].patterns[0];G.confirmHarmony(pat,{version:1,events:[{start:0,duration:8*G.BAR,rootPitchClass:0,quality:'major'}]});pat.retention={notes:[{id:pat.notes[0].id,all:true}],ranges:[{start:0,end:8*G.BAR}]};const r=G.editSongTime(p,{startBar:1,endBar:3,kind:'clear'}).project,q=r.tracks[0].patterns[0];assert.deepEqual(events(r),events(p));assert.equal(G.harmonyStatus(q),'confirmed');assert.deepEqual(json(q.harmony.events.map(e=>[e.start,e.duration])),[[0,G.BAR],[3*G.BAR,5*G.BAR]]);assert.equal(q.retention.notes.length,1);assert.equal(q.retention.ranges.length,2);});
test('C-T08 exact phrase lengths 1..16 validate, out of bounds reject',()=>{for(let n=1;n<=16;n++){const p=G.blankProject();p.bars=n;p.tracks[0].patterns[0].bars=n;assert.doesNotThrow(()=>G.validateProject(p));}for(const n of [0,17,3.5]){const p=G.blankProject();p.bars=24;p.tracks[0].patterns[0].bars=n;assert.throws(()=>G.validateProject(p));}});
test('C-T09 deletion moves every track and loop through one time mapping',()=>{const p=song();const t=G.newTrack();t.clips[0].bar=12;t.patterns[0].notes=[G.newNote(80,0,960)];p.tracks.push(t);const r=G.editSongTime(p,{startBar:2,endBar:5,kind:'delete'});assert.equal(r.project.tracks[1].clips[0].bar,9);const s={arrangeCursor:{tick:12*G.BAR}},b={range:[4*G.BAR,12*G.BAR],startTick:4*G.BAR};G.reconcileSongTime(s,b,r.timeEdit);assert.deepEqual(json(b.range),[2*G.BAR,9*G.BAR]);assert.equal(s.arrangeCursor.tick,9*G.BAR);});
test('C-T10 source and edited-instance identity are conserved appropriately',()=>{const p=song(),t=p.tracks[0],id=t.clips[0].id,pat=t.patterns[0];G.confirmHarmony(pat,{version:1,events:[{start:0,duration:8*G.BAR,rootPitchClass:0,quality:'major'}]});pat.notes[0].pitch++;const r=G.editSongTime(p,{startBar:1,endBar:3,kind:'delete'}).project;assert.equal(r.tracks[0].clips[0].id,id);assert.equal(G.harmonyStatus(r.tracks[0].patterns[0]),'stale');});
test('C-T11 matrix checks exact outside events for every 8-bar interval',()=>{for(let a=0;a<8;a++)for(let b=a+1;b<=8;b++)for(const kind of ['clear','delete']){const p=song();p.tracks[0].patterns[0].notes=Array.from({length:8},(_,i)=>G.newNote(60+i,i*G.BAR+120,500,.7));const before=events(p),r=G.editSongTime(p,{startBar:a,endBar:b,kind}).project,expected=before.filter(([s])=>s<a*G.BAR||s>=b*G.BAR).map(([s,...tail])=>[s-(kind==='delete'&&s>=b*G.BAR?(b-a)*G.BAR:0),...tail]);assert.deepEqual(events(r),expected,`${kind} ${a}..${b}`);}});
