/** Design system contracts exercised against production modules. No audio mocks passed as listening. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {runtime,root,json,context} from './runtime.mjs';
function uiRuntime(){const G=runtime(),env=vm.createContext({GridTone:G,console,document:{querySelector:()=>null},performance,innerHeight:900,innerWidth:1440,requestAnimationFrame:fn=>fn()});for(const f of ['messages.zh-CN','formatters','music-palette','components','music-block','tool-panel','candidate-projection'])vm.runInContext(fs.readFileSync(`${root}/src/ui/${f}.js`,'utf8'),env);vm.runInContext(fs.readFileSync(`${root}/src/views/creation.js`,'utf8'),env);return G;}
const G=uiRuntime(),F=G.ui.format;
test('DS01 one-based position roundtrip for integer, triplet, and fractional ticks',()=>{for(const n of [0,1,80,120,160,240,319.5,960,3839.5,3840,5760,16384.25,983039.7,1e-8])assert.equal(F.parsePosition(F.position(n)),n);});
test('DS02 malformed and out-of-bounds positions rejected',()=>{for(const v of ['0.1','1.0','1.5','2','foo','1.1+960','2.1+-1','99999999999999999999.1','258.1'])assert.throws(()=>F.parsePosition(v));});
test('DS03 musical end boundary and duration ranges explicit',()=>{assert.equal(F.position(4*G.BAR),'5.1');assert.equal(F.range(0,4*G.BAR),'第 1—4 小节');assert.match(F.range(120,960),/终点不含/);});
test('DS04 pan formatter consistent in all positions',()=>{assert.equal(F.pan(0),'居中');assert.equal(F.pan(-.25),'左 25%');assert.equal(F.pan(.25),'右 25%');assert.equal(F.parameter('track','pan',0),'居中');});
test('DS05 every chord quality has a readable Chinese name',()=>{for(const q of Object.keys(G.CHORD_SHAPES)){assert.notEqual(F.quality(q),q);assert.notEqual(F.quality(q),'自定义和弦');}});
test('DS06 button role, size, busy and accessible name declared',()=>{for(const size of ['normal','small','icon'])for(const variant of ['primary','secondary','quiet','danger']){const h=G.ui.Button({action:'a',label:'试听 & 音乐',icon:'play',size,variant});assert.ok(h.includes(`data-size="${size}"`));assert.ok(h.includes(`data-variant="${variant}"`));assert.match(h,/aria-label="试听 &amp; 音乐"/);}assert.match(G.ui.Button({action:'a',label:'等待',busy:true}),/disabled/);});
test('DS07 invalid component variations rejected',()=>{assert.throws(()=>G.ui.Button({action:'a',label:'b',size:'tiny'}));assert.throws(()=>G.ui.Button({action:'a',label:'b',variant:'bright'}));});
test('DS08 legacy compatibility explicitly identifies small icon key and transport',()=>{for(const [cls,size]of [['quiet small-btn','small'],['icon-btn','icon'],['audition-key white-key','key'],['play-btn','transport']])assert.ok(G.ui.button('x','x','',cls).includes(`data-size="${size}"`));});
test('DS09 sources cannot inject markup through material names',()=>{const t=G.getTemplate(G.catalogTemplates().find(t=>t.type==='pattern').id);t.name='<script>alert(1)</script>';const h=G.ui.musicBlock.card(G.ui.musicBlock.model(t));assert.ok(!h.includes('<script>'));assert.ok(h.includes('&lt;script&gt;'));});
test('DS10 single material has exact duration and original notes',()=>{const t=G.getTemplate(G.catalogTemplates().find(t=>t.type==='pattern'&&t.role==='chords').id),before=JSON.stringify(t),m=G.ui.musicBlock.model(t);assert.equal(m.bars,t.bars);assert.deepEqual(json(m.tracks[0].patterns[0].notes),json(t.notes));assert.equal(JSON.stringify(t),before);});
test('DS11 all eight combination previews derive from actual composition roles',()=>{for(const r of G.RECIPES){const m=G.ui.musicBlock.model({...r,type:'recipe',role:'song'}),p=G.recipeProject(r.id,{key:0,seed:1});assert.equal(m.bars,p.bars);assert.deepEqual(json(m.tracks.map(t=>[t.role,t.clips.length,t.patterns[0].notes.length])),json(p.tracks.map(t=>[t.role,t.clips.length,t.patterns[0].notes.length])));assert.ok(G.ui.musicBlock.card(m).includes(`${p.tracks.length} 轨`));}});
test('DS12 example projects cannot start material drags',()=>{const m=G.ui.musicBlock.model({id:'example',name:'示例',type:'song',project:G.recipeProject('recipe.pop')});const h=G.ui.musicBlock.card(m);assert.match(h,/draggable="false"/);assert.match(h,/shelf-open-song/);assert.match(h,/新建作品，保留当前作品/);});
test('DS13 independent audition favorite and pick actions',()=>{const m=G.ui.musicBlock.model(G.catalogTemplates().find(t=>t.type==='pattern')),h=G.ui.musicBlock.card(m,{picked:true,favorite:true,audition:true});for(const x of ['shelf-pick','shelf-preview','shelf-favorite','is-picked','is-auditioning'])assert.ok(h.includes(x));assert.ok(h.includes('aria-pressed="true"'));});
test('DS14 placement previews contain no editable note or clip identities',()=>{const m=G.ui.musicBlock.model(G.catalogTemplates().find(t=>t.type==='pattern')),h=G.ui.musicBlock.projection(m,'第5—8小节',true);assert.ok(!/data-note=|data-clip=|data-resize=/.test(h));assert.match(h,/data-stage="projection"/);});
test('DS15 projection comparison distinguishes unchanged changed removed with multiplicity',()=>{const a=[{id:'a',pitch:60,start:0,duration:240,velocity:.7},{id:'b',pitch:60,start:0,duration:240,velocity:.7}],b=[a[0],{id:'c',pitch:62,start:240,duration:240,velocity:.7}];const d=G.ui.projectionDiff(a,b);assert.equal(d.unchanged,1);assert.equal(d.changed,1);assert.equal(d.removed,1);});
test('DS16 partial retention is labelled by actual dimension; false flags not hard-kept',()=>{const n={id:'a',pitch:60,start:0,duration:240,velocity:.7};assert.equal(G.ui.projectionDiff([n],[n],{notes:[{id:'a',pitch:true}]}).items[0].preserved,'保留音高');assert.equal(G.ui.projectionDiff([n],[n],{notes:[{id:'a',pitch:false}]}).items[0].state,'unchanged');});
test('DS17 range retention and rest boundaries stay external to projection',()=>{const n={id:'a',pitch:60,start:0,duration:240,velocity:.7},copy=JSON.stringify(n),r={ranges:[{start:120,end:360}]};assert.equal(G.ui.projectionDiff([n],[n],r).items[0].state,'retained');assert.equal(JSON.stringify(n),copy);});
test('DS18 comparison score uses caller-shared music coordinates',()=>{const n=[{pitch:60,start:0,duration:240,velocity:.7}],opts={bars:4,low:48,high:84},a=G.ui.NotePreview(n,opts),b=G.ui.NotePreview([...n,{pitch:72,start:480,duration:240,velocity:.7}],opts);assert.equal(a.match(/<rect[^>]+>/)[0],b.match(/<rect[^>]+>/)[0]);});
function creation(mode='generate',noHarmony=false){const {p,t,pat,target}=context(G);if(noHarmony)for(const t of p.tracks)for(const pat of t.patterns)delete pat.harmony;const s=G.createEditorSession(p);G.openPatternInSession(s,p,{...target,edit:true});s.rightPanel='creation';let markup='',audition;const ui=new G.CreationUI({getProject:()=>p,getSession:()=>s,button:G.ui.button,esc:G.ui.esc,playback:{endAudition(){},audition:(...v)=>audition=v},openCreation:(title,html)=>markup=html,toast(){},closeModal(){},updateProjection(){}});ui.open(mode);return {p,t,pat,s,ui,markup:()=>markup,audition:()=>audition};}
test('DS19 preflight missing harmony is visible before computation',()=>{const x=creation('generate',true);assert.match(x.ui.prerequisites(),/先选一段和弦/);assert.match(x.markup(),/creation-pick-chords/);assert.match(x.markup(),/data-action="creation-generate"\s+disabled/);});
test('DS20 preparation uses task choices and disclosed advanced controls',()=>{const x=creation();assert.ok(x.markup().indexOf('task-picker')<x.markup().indexOf('最低音'));assert.match(x.markup(),/写一句旋律/);assert.match(x.markup(),/范围与细节/);assert.ok(!x.markup().includes('第 0 拍'));});
test('DS21 result precedes settings and adoption becomes main action',()=>{const x=creation(),before=JSON.stringify(x.p);x.ui.generate();const h=x.markup();assert.equal(JSON.stringify(x.p),before);assert.ok(h.indexOf('candidate-bar')<h.indexOf('creation-tuning'));assert.match(h,/data-action="creation-apply"[^>]*><[^>]+>.*用这版|用这版/);assert.ok(h.includes('听原稿'));});
test('DS22 read-only projection never writes into original project',()=>{const x=creation();x.ui.generate();const before=JSON.stringify(x.p),projection=x.ui.projection();assert.ok(projection.notes.length);assert.equal(JSON.stringify(x.p),before);x.s.rightPanel='sound';assert.equal(x.ui.projection(),null);});
test('DS23 target and dependency changes remove applicable projected result',()=>{const x=creation();x.ui.generate();x.p.tracks.find(t=>t.id===x.t.id).patterns[0].notes.push(G.newNote(62,100,100));assert.equal(x.ui.projection(),null);});
test('DS24 human timing drafts prevent generation on invalid range',()=>{const x=creation();x.ui.handleField({dataset:{field:'creation-start'},value:'0.1'});assert.ok(x.ui.prerequisites());assert.equal(x.ui.session.start,0);x.ui.handleField({dataset:{field:'creation-start'},value:'1.1'});assert.equal(x.ui.prerequisites(),'');});
test('DS25 generation needs 4 or 8 bars, not just valid endpoints',()=>{const x=creation();x.ui.session.end=3*G.BAR;assert.match(x.ui.prerequisites(),/连续 4 或 8/);});
test('DS26 mode changes keep calculation whitelist while presentation changes',()=>{const x=creation();x.ui.session.intent='ending';x.ui.handleField({dataset:{field:'creation-mode'},value:'rhythm'});const p=G.creationParameters('rhythm',x.ui.session);assert.ok(!Object.hasOwn(p,'intent'));assert.equal(p.mode,'rhythm');});
test('DS27 metadata identities and version stay v3 through presentation',()=>{const p=G.recipeProject('recipe.pop'),a=JSON.stringify(p);for(const t of p.tracks){G.ui.musicBlock.model({id:'p',name:t.name,type:'song',project:p});for(const pat of t.patterns)G.ui.projectionDiff(pat.notes,pat.notes,pat.retention);}assert.equal(JSON.stringify(p),a);assert.equal(G.validateProject(p).version,3);});
test('DS28 formatter is used for initial slider center, not 0 percent',()=>{const h=G.ui.slider('左右位置','track','pan',0,-1,1);assert.ok(h.includes('居中'));assert.ok(!h.includes('>0%</b>'));});
test('DS29 all major flows have coverage owners and production modules',()=>{const table=JSON.parse(fs.readFileSync(`${root}/design-system/coverage.json`));assert.ok(Object.keys(table).length);assert.ok(fs.existsSync(`${root}/design-system/README.md`));});
test('DS30 legacy sound data/algorithms stay frozen; approved v2 extensions use explicit allowlist',()=>{const log=JSON.parse(fs.readFileSync(`${root}/tests/fixtures/v1.9/music-baseline-digests.json`)),allow=JSON.parse(fs.readFileSync(`${root}/docs/content-2.0/approved-core-extensions.json`));for(const [path,expected]of Object.entries(log)){if(allow.changes[path]){assert.ok(allow.changes[path].length>30);continue;}const crypto=awaitCrypto;assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`${root}/${path}`)).digest('hex'),expected,path);}});
import * as awaitCrypto from 'node:crypto';

test('DS31 known browser storage errors are actionable Chinese without renaming user data',()=>{assert.match(F.error("Failed to execute 'open' on 'IDBFactory': access to IndexedDB is denied in this context."),/本机存储.*下载作品文件/);assert.equal(F.error('已保存：用户自己的工程名'),'已保存：用户自己的工程名');assert.equal(F.error('没有和弦来源'),'没有和弦来源');});
