import test from 'node:test';import assert from 'node:assert/strict';
import '../src/model.js';import '../src/session.js';import '../src/editing.js';
const G=globalThis.GridTone;
function setup(){const p=G.blankProject(),t=p.tracks[0],pat=t.patterns[0];pat.notes=[G.newNote(60,0),G.newNote(64,240),G.newNote(67,480),G.newNote(61,720)];const s=G.createEditorSession(p);return {p,t,pat,s};}
test('fixed viewport is a window, never forced to include distant notes',()=>{const {p,t,pat,s}=setup();const v=G.viewportFor(s,t);v.low=90;v.span=12;assert.deepEqual(G.visiblePitches(p,s,t,pat),Array.from({length:13},(_,i)=>102-i));});
test('simplified rows retain chromatic notes within view without rewriting data',()=>{const {p,t,pat,s}=setup(),before=G.clone(p);s.showScale=true;const rows=G.visiblePitches(p,s,t,pat);assert.ok(rows.includes(61));assert.deepEqual(p,before);});
test('view pan zoom and fit leave compiled music untouched',()=>{const {p,t,pat,s}=setup(),before=G.compileSong(p);G.moveViewport(s,t,24);G.viewportFor(s,t).zoomX=2;G.fitViewport(s,t,pat);assert.deepEqual(G.compileSong(p),before);});
test('semitone mirror does not depend on visible scale or reference key',()=>{const {p,t,pat,s}=setup();const a=G.transformNotes(pat.notes,'mirror',G.BAR);s.showScale=true;p.key=2;assert.deepEqual(G.transformNotes(pat.notes,'mirror',G.BAR),a);});
test('diatonic reflection uses degree distance and is reversible for in-scale data',()=>{const notes=[60,64,67].map((v,i)=>G.newNote(v,i*240));const a=G.mirrorDegree(notes,0,'major');assert.deepEqual(a.map(n=>n.pitch),[60,57,53]);assert.deepEqual(G.mirrorDegree(a,0,'major'),notes);});
test('diatonic reflection refuses to silently alter chromatic notes',()=>{assert.throws(()=>G.mirrorDegree([G.newNote(60,0),G.newNote(61,240)],0,'major'),/调内级数/);});
test('explicit transpose changes pitches while preserving times, ids and intervals',()=>{const {pat}=setup();const a=G.changeNotePitches(pat.notes,{mode:'semitone',semitones:2});assert.deepEqual(a.map(n=>n.pitch),[62,66,69,63]);assert.deepEqual(a.map(n=>n.id),pat.notes.map(n=>n.id));assert.deepEqual(a.map(n=>n.start),pat.notes.map(n=>n.start));});
test('key transpose uses nearest direction and scale adaptation is explicit',()=>{const notes=[60,64,67,69].map((p,i)=>G.newNote(p,i*240));assert.deepEqual(G.changeNotePitches(notes,{mode:'key',sourceKey:0,targetKey:2}).map(n=>n.pitch),[62,66,69,71]);assert.deepEqual(G.changeNotePitches(notes,{mode:'adapt',sourceKey:0,sourceScale:'major',targetKey:0,targetScale:'minor'}).map(n=>n.pitch),[60,63,67,68]);});
test('invalid pitch and incompatible scales reject without partially changing source',()=>{const n=[G.newNote(127,0)],before=G.clone(n);assert.throws(()=>G.changeNotePitches(n,{semitones:2}));assert.deepEqual(n,before);assert.throws(()=>G.changeNotePitches(n,{mode:'adapt',sourceScale:'pentatonic',targetScale:'major'}));});
test('candidate selection changes only selected notes, preserves reference and document',()=>{const {p,t,pat}=setup(),before=G.clone(p);const c=G.pitchCandidate(p,t.id,pat.id,[pat.notes[0].id],{semitones:12});assert.deepEqual(p,before);assert.equal(c.tracks[0].patterns[0].notes[0].pitch,72);assert.deepEqual(c.tracks[0].patterns[0].notes.slice(1),pat.notes.slice(1));assert.equal(c.key,p.key);});
