import test from 'node:test';import assert from 'node:assert/strict';
import '../src/model.js';import '../src/presets.js';import '../src/editing.js';import '../src/music/progressions.js';import '../src/music/harmony.js';import '../src/catalog-data.js';import '../src/catalog.js';
const G=globalThis.GridTone;
function setup(){let p=G.blankProject();const r=G.applyTemplate(p,G.generateProgression('progression.pop').template,{mode:'new-track',bar:8});p=r.project;const t=p.tracks[0];t.patterns[0].bars=4;t.clips[0].bar=8;return {p,t,source:p.tracks[1],query:{trackId:t.id,clipId:t.clips[0].id,sourceTrackId:p.tracks[1].id}};}
test('R4-T01 every performance style retains identical harmonic events',()=>{const values=['whole','pulse','arp','strum'].map(rhythm=>G.generateProgression('progression.pop',{rhythm}).template.harmony.events);for(const v of values)assert.deepEqual(v,values[0]);});
test('R4-T02/T03 instance offset and half-bar clipping are exact',()=>{const {p,query}=setup();const h=G.resolveHarmony(p,{...query,start:G.BAR,end:2*G.BAR});assert.equal(h.events[0].rootPitchClass,7);assert.equal(h.events[0].start,G.BAR);assert.equal(h.origin,8*G.BAR);const all=G.resolveHarmony(p,{...query,start:G.BAR/2,end:G.BAR*1.5});assert.equal(all.events.length,2);assert.equal(all.events[0].duration,G.BAR/2);});
test('R4-T04/T06 display and mix edits preserve context; notes invalidate and undo restores',()=>{const {p,query,source}=setup(),before=G.clone(p);const hash=G.sourceHash(source);p.key=7;source.volume=.1;source.name='改名';assert.equal(G.sourceHash(source),hash);source.patterns[0].notes[0].pitch++;assert.throws(()=>G.resolveHarmony(p,query),/复核/);assert.doesNotThrow(()=>G.resolveHarmony(before,query));});
test('R4-T05 missing source or uncovered range is explicit',()=>{const {p,query,source}=setup();source.clips[0].bar=9;assert.throws(()=>G.resolveHarmony(p,query),/空档|覆盖/);assert.throws(()=>G.resolveHarmony(p,{...query,sourceTrackId:'missing'}),/选择参考/);});
test('R4-T07 transpose and bake are applied exactly once',()=>{const {p,query,source}=setup();source.pipeline.transpose=5;const before=G.resolveHarmony(p,query).events;for(const pat of source.patterns){pat.notes=G.processPattern(pat,source,{...p,swing:0});G.bakeHarmony(pat,5);}source.pipeline.transpose=0;assert.deepEqual(G.resolveHarmony(p,query).events,before);assert.doesNotThrow(()=>G.validateProject(p));});
test('v3 creative metadata rejects invalid or unbounded fields',()=>{const {p,source}=setup();source.patterns[0].harmony.events[0].duration=-1;assert.throws(()=>G.validateProject(p),/和声/);});
