import test from 'node:test';import assert from 'node:assert/strict';
import '../src/model.js';import '../src/presets.js';import '../src/session.js';import '../src/audio.js';import '../src/playback.js';
const G=globalThis.GridTone;
function setup(){const p=G.demoProject(),s=G.createEditorSession(p),b=G.createPlaybackContext();return {p,s,b};}
test('isolated pattern ignores project mute and unrelated temporary solo',()=>{const {p,s,b}=setup(),t=p.tracks[1];t.mute=true;b.soloIds=[p.tracks[0].id];G.openPatternInSession(s,p,{trackId:t.id,patternId:t.patterns[0].id});b.target='pattern';const c=G.compileSong(p,G.scopeFor(p,s,b));assert.equal(c.events.length,t.patterns[0].notes.length);assert.deepEqual(c.trackIds,[t.id]);});
test('bar audition clips and carries sustained notes at its local zero',()=>{const {p,s,b}=setup(),t=p.tracks[1],pat=t.patterns[0];pat.bars=2;pat.notes=[G.newNote(60,3000,2000),G.newNote(62,5000,200)];G.openPatternInSession(s,p,{trackId:t.id,patternId:pat.id});s.page=1;b.target='bar';const c=G.compileSong(p,G.scopeFor(p,s,b));assert.equal(c.length,G.BAR);assert.deepEqual(c.events.map(n=>[n.start,n.duration]),[[0,1160],[1160,200]]);});
test('selected tracks isolate two tracks, independent from mute and solo',()=>{const {p,s,b}=setup();p.tracks[0].mute=true;b.soloIds=[p.tracks[2].id];b.selectedTrackIds=[p.tracks[0].id,p.tracks[1].id];b.target='tracks';assert.deepEqual(G.compileSong(p,G.scopeFor(p,s,b)).trackIds,b.selectedTrackIds);});
test('invalid local scope fails explicitly rather than quietly playing all',()=>{const {p}=setup();assert.throws(()=>G.compileSong(p,{kind:'pattern',trackId:p.tracks[0].id,patternId:'unknown'}));assert.throws(()=>G.compileSong(p,{kind:'tracks',trackIds:[]}));assert.throws(()=>G.compileSong(p,{kind:'bar',trackId:p.tracks[0].id,patternId:p.tracks[0].patterns[0].id,page:99}));});
function fake(){return {playing:false,starting:false,pausedAt:0,stop(){this.playing=false;this.starting=false;this.pausedAt=0;},pause(){this.playing=false;this.pausedAt=100;},async play(p,scope,loop,start){this.project=p;this.scope=scope;this.playing=true;this.start=start;},update(p,scope){this.project=p;this.scope=scope;}};}
test('playback controller follows editor pattern, exits local, keeps full song across workspaces',async()=>{const {p,s,b}=setup(),e=fake(),c=new G.PlaybackController(e,()=>p,()=>s,b);await c.start('pattern');const t=p.tracks[1];G.openPatternInSession(s,p,{trackId:t.id,patternId:t.patterns[0].id});c.editorChanged();assert.equal(e.scope.patternId,t.patterns[0].id);c.leaveEditor();assert.equal(b.target,'song');assert.equal(e.playing,false);await c.start('song');c.leaveEditor();assert.equal(e.playing,true);});
test('whole-song export ignores temporary solo but respects project mute',()=>{const {p,s,b}=setup(),c=new G.PlaybackController(fake(),()=>p,()=>s,b);b.soloIds=[p.tracks[0].id];p.tracks[1].mute=true;assert.equal(G.compileSong(p,c.exportScope()).trackIds.length,3);assert.equal(G.compileSong(p,c.exportScope('current')).trackIds.length,1);});
test('candidate audition does not mutate document, and stop restores original target',async()=>{const {p,s,b}=setup(),before=G.clone(p),e=fake(),c=new G.PlaybackController(e,()=>p,()=>s,b);const candidate=G.clone(p);candidate.tracks[0].name='候选';await c.audition(candidate,{kind:'song'},'候选试听');assert.equal(b.audition,'候选试听');assert.deepEqual(p,before);c.stop();assert.equal(b.audition,undefined);assert.equal(c.auditionProject,null);});
test('stop during pending audio initialization invalidates a main start',async()=>{const e=new G.AudioEngine();let resolve;e.ready=()=>new Promise(r=>resolve=r);const p=G.blankProject(),pending=e.play(p);assert.equal(e.starting,true);e.stop();resolve({});await pending;assert.equal(e.playing,false);assert.equal(e.starting,false);assert.equal(e.graph,null);});
test('stop during pending note preview invalidates preview generation',async()=>{const e=new G.AudioEngine();let resolve;e.ready=()=>new Promise(r=>resolve=r);const p=G.blankProject(),pending=e.preview(p.tracks[0],60,p,.3);e.stop();resolve({});await pending;assert.equal(e.previewGraphs.size,0);});
