/** Second-pass integration contracts against the delivered 1.7.1 runtime. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {runtime,context,json} from './runtime.mjs';
const G=runtime();
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
function engine(){return {playing:false,starting:false,pausedAt:0,stops:0,position(){return this.pausedAt},stop(){this.stops++;this.playing=false;this.starting=false;this.pausedAt=0},play(p,s,l,t=0){this.last={p,s,l,t};this.playing=true;this.pausedAt=t;return Promise.resolve()},pause(){this.playing=false},update(){},updateMix(){},seek(t){this.pausedAt=t}}}
function playback(){const p=G.demoProject(),s=G.createEditorSession(p),b=G.createPlaybackContext(),e=engine(),errors=[];return {p,s,b,e,errors,c:new G.PlaybackController(e,()=>p,()=>s,b,()=>{},m=>errors.push(m))}}
test('Q01 late audition failure cannot stop a newer audition',async()=>{const {p,e,c,errors}=playback(),first=deferred();let calls=0;e.play=function(p,s,l,t){this.playing=true;return ++calls===1?first.promise:Promise.resolve()};const a=c.audition(p,{kind:'song'},'first');await c.audition(G.clone(p),{kind:'song'},'second');first.reject(Error('old request failed'));await a;assert.equal(c.context.audition,'second');assert.equal(e.playing,true);assert.equal(errors.length,0)});
test('Q02 late normal-play failure cannot stop a newer audition',async()=>{const {p,e,c,errors}=playback(),first=deferred();let calls=0;e.play=function(){this.playing=true;return ++calls===1?first.promise:Promise.resolve()};const a=c.start();await c.audition(G.clone(p),{kind:'song'},'new');first.reject(Error('old startup failed'));await a;assert.equal(c.context.audition,'new');assert.equal(e.playing,true);assert.equal(errors.length,0)});
test('Q03 changing loop range after paused audition clears preview ownership',async()=>{const {p,c,b,e}=playback();await c.audition(p,{kind:'song',range:[0,4*G.BAR]},'old');await c.toggle();c.setRange([4*G.BAR,8*G.BAR]);assert.equal(c.auditionProject,null);assert.equal(b.audition,undefined);await c.toggle();assert.deepEqual(json(e.last.s.range),[4*G.BAR,8*G.BAR]);});
test('Q04 export current listening chooses preview document and scope',async()=>{const {p,c}=playback(),preview=G.clone(p);preview.tracks[0].patterns[0].notes[0].pitch=99;await c.audition(preview,{kind:'song',range:[G.BAR,2*G.BAR],soloIds:[preview.tracks[0].id]},'draft');assert.equal(typeof c.exportSelection,'function');const out=c.exportSelection('current');assert.equal(out.project.tracks[0].patterns[0].notes[0].pitch,99);assert.deepEqual(json(out.scope.range),[G.BAR,2*G.BAR]);const normal=c.exportSelection('song');assert.deepEqual(json(normal.project),json(p));assert.deepEqual(json(normal.scope.soloIds),[]);});
test('Q05 baking performance must not confirm stale harmonic intent',()=>{const {p,source}=context(G),pat=source.patterns[0];pat.notes[0].pitch++;assert.equal(G.harmonyStatus(pat),'stale');source.pipeline.transpose=2;const stale=G.harmonyStatus(pat);pat.notes=G.processPattern(pat,source,{...p,swing:0});G.bakeHarmony(pat,2,stale);assert.equal(G.harmonyStatus(pat),'stale');});
test('Q06 drum candidate invalidated when target drum mapping changes',()=>{const p=G.recipeProject('recipe.pop'),t=p.tracks.find(t=>t.kind==='drum'),target={trackId:t.id,clipId:t.clips[0].id},params={mode:'drums',drumRole:'closedHat',density:'dense'};const c=G.generateEnsemble(p,target,params,7),f=new G.CandidateSession(p,'drums',target,params);f.begin();f.ready([G.applyGenerated(p,target,c)]);const d=G.clone(p);const kit=G.clone(G.resolveKit(t.drumkitId,p));kit.id='reaudit.kit';kit.rows.forEach(r=>{r.role=G.drumRole(r);if(r.role==='closedHat')r.role='openHat';else if(r.role==='openHat')r.role='closedHat'});d.catalog??={presets:[],drumkits:[]};d.catalog.drumkits.push(kit);d.tracks.find(v=>v.id===t.id).drumkitId=kit.id;G.validateProject(d);assert.throws(()=>f.materialize(d),/目标|鼓组|映射/);});
test('Q07 generated bass dependency tracks source drum role mapping',()=>{const p=G.recipeProject('recipe.pop'),t=p.tracks.find(t=>t.role==='bass'),drum=p.tracks.find(t=>t.kind==='drum'),h=p.tracks.find(t=>t.role==='chords'),target={trackId:t.id,clipId:t.clips[0].id};const c=G.generateEnsemble(p,target,{mode:'bass',sourceTrackId:h.id,referenceTrackId:drum.id,strategy:'align'},7);const out=G.applyGenerated(p,target,c),d=G.clone(out.project);const kit=G.clone(G.resolveKit(drum.drumkitId,p));kit.id='reaudit.kickmap';kit.rows.forEach(r=>{r.role=G.drumRole(r);if(r.role==='kick')r.role='snare';else if(r.role==='snare')r.role='kick'});d.catalog??={presets:[],drumkits:[]};d.catalog.drumkits.push(kit);d.tracks.find(v=>v.id===drum.id).drumkitId=kit.id;G.validateProject(d);assert.equal(G.dependencyStatus(d,d.tracks.find(v=>v.id===t.id).patterns[0],d.tracks.find(v=>v.id===t.id).clips[0]),'stale');});
test('Q08 stopped pending playback does not surface a stale failure',async()=>{const {c,e,errors}=playback(),d=deferred();e.play=()=>d.promise;const a=c.start();c.stop();d.reject(Error('stopped'));await a;assert.equal(e.playing,false);assert.equal(errors.length,0);});
test('Q09 current audition failure restores the original listening range',async()=>{const {p,c,b,e,errors}=playback();b.range=[G.BAR,3*G.BAR];b.startTick=G.BAR;e.pausedAt=123;e.playing=true;let calls=0;e.play=function(p,s,l,t){this.last={p,s,l,t};if(++calls===1)return Promise.reject(Error('bad sample'));this.playing=true;this.pausedAt=t;return Promise.resolve()};assert.equal(await c.audition(G.clone(p),{kind:'song'},'bad'),false);assert.equal(c.auditionProject,null);assert.equal(errors.length,1);assert.equal(e.last.t,123);assert.deepEqual(json(e.last.s.range),[G.BAR,3*G.BAR]);});
test('Q10 successive previews restore the pre-preview time exactly once',async()=>{const {p,c,b,e}=playback();e.playing=true;e.pausedAt=222;b.range=[G.BAR,3*G.BAR];await c.audition(p,{kind:'song'},'A');await c.audition(G.clone(p),{kind:'song'},'B');c.endAudition();assert.equal(e.last.t,222);assert.deepEqual(json(e.last.s.range),[G.BAR,3*G.BAR]);assert.equal(c.returnState,null);});
test('Q11 changing range during playback listens to the document at the new range',async()=>{const {p,c,b,e}=playback();await c.audition(G.clone(p),{kind:'song'},'A');c.setRange([G.BAR,2*G.BAR]);assert.equal(c.auditionProject,null);assert.deepEqual(json(e.last.s.range),[G.BAR,2*G.BAR]);assert.equal(e.last.t,0);});
test('Q12 invalid playback range leaves existing transport untouched',async()=>{const {p,c,b,e}=playback();await c.start();const before=json(b);assert.throws(()=>c.setRange([3*G.BAR,2*G.BAR]),/范围/);assert.deepEqual(json(b),before);assert.equal(e.playing,true);});
test('Q13 export selection is an independent snapshot',async()=>{const {p,c}=playback();await c.audition(p,{kind:'song',range:[0,G.BAR]},'P');const out=c.exportSelection('current');out.project.tracks[0].patterns[0].notes[0].pitch=1;out.scope.range[1]=1;assert.notEqual(p.tracks[0].patterns[0].notes[0].pitch,1);assert.equal(c.auditionScope.range[1],G.BAR);});
test('Q14 paused candidate retains current-export identity',async()=>{const {p,c}=playback(),candidate=G.clone(p);candidate.title='Candidate';await c.audition(candidate,{kind:'song',range:[G.BAR,2*G.BAR]},'P');await c.toggle();assert.equal(c.exportSelection('current').project.title,'Candidate');assert.equal(c.exportSelection('song').project.title,p.title);});
test('Q15 saved mute and temporary solo remain separate in all export selection paths',()=>{const {p,c,b}=playback();p.tracks[1].mute=true;b.soloIds=[p.tracks[0].id];const full=c.exportSelection('song'),solo=c.exportSelection('current');assert.equal(G.compileSong(full.project,full.scope).trackIds.length,3);assert.equal(G.compileSong(solo.project,solo.scope).trackIds.length,1);});
test('Q16 a confirmed harmony retains confirmation after a proved performance bake',()=>{const {p,source}=context(G),pat=source.patterns[0],first=pat.harmony.events[0].rootPitchClass;const status=G.harmonyStatus(pat);source.pipeline.transpose=2;pat.notes=G.processPattern(pat,source,{...p,swing:0});G.bakeHarmony(pat,2,status);assert.equal(G.harmonyStatus(pat),'confirmed');assert.equal(pat.harmony.events[0].rootPitchClass,(first+2)%12);});
test('Q17 baking a track with no harmonic intent never invents it',()=>{const pat=G.newPattern('empty');G.bakeHarmony(pat,2,'missing');assert.equal(pat.harmony,undefined);});
test('Q18 drum mapping fingerprint ignores name and same-role sound changes',()=>{const p=G.recipeProject('recipe.pop'),t=p.tracks.find(t=>t.kind==='drum'),before=G.drumMappingHash(p,t);t.name='new name';t.volume=.1;t.preset='softdrums';assert.equal(G.drumMappingHash(p,t),before);});
test('Q19 mapping-aware source dependency survives project roundtrip',()=>{const p=G.recipeProject('recipe.pop'),t=p.tracks.find(t=>t.role==='bass'),d=p.tracks.find(t=>t.kind==='drum'),h=p.tracks[0],target={trackId:t.id,clipId:t.clips[0].id};const c=G.generateEnsemble(p,target,{mode:'bass',sourceTrackId:h.id,referenceTrackId:d.id},17);const out=G.validateProject(json(G.applyGenerated(p,target,c).project)),pat=out.tracks.find(v=>v.id===t.id).patterns[0];assert.equal(pat.generation.settings.drumReferenceMapHash,G.drumMappingHash(out,d));assert.equal(G.dependencyStatus(out,pat,out.tracks.find(v=>v.id===t.id).clips[0]),'current');});
test('Q20 old generation sources without mapping hash remain readable',()=>{const p=G.recipeProject('recipe.pop');for(const t of p.tracks)for(const pat of t.patterns)if(pat.generation){delete pat.generation.settings.drumReferenceTrackId;delete pat.generation.settings.drumReferenceMapHash;}assert.equal(G.validateProject(json(p)).version,3);});
test('Q21 copy preserves mapping-aware dependencies and performance identity',()=>{const p=G.recipeProject('recipe.dance'),copy=G.copyProject(p);assert.deepEqual(json(G.compileSong(p).events.map(n=>[n.pitch,n.start,n.duration,n.velocity])),json(G.compileSong(copy).events.map(n=>[n.pitch,n.start,n.duration,n.velocity])));for(const t of copy.tracks)for(const clip of t.clips){const pat=t.patterns.find(p=>p.id===clip.patternId);if(pat.generation)assert.equal(G.dependencyStatus(copy,pat,clip),'current');}});
test('Q22 drum remapping preserves timing, identity, and rejects missing target roles',()=>{const p=G.recipeProject('recipe.pop'),t=p.tracks.find(t=>t.kind==='drum'),rows=G.drumsFor(p,t),target=rows.map(r=>({...r,pitch:r.pitch+12})),notes=t.patterns[0].notes;const out=G.remapDrums(notes,rows,target);assert.ok(out.every((n,i)=>n.pitch===notes[i].pitch+12&&n.id===notes[i].id&&n.start===notes[i].start&&n.duration===notes[i].duration));assert.throws(()=>G.remapDrums(notes,rows,target.filter(r=>G.drumRole(r)!=='kick')),/缺少/);});
test('Q23 closing a paused preview cancels its pending resume safely',async()=>{const {p,c,e,errors}=playback();await c.audition(p,{kind:'song'},'A');await c.toggle();const d=deferred();e.play=()=>d.promise;const pending=c.toggle();c.stop();d.reject(Error('stale resume'));await pending;assert.equal(c.auditionProject,null);assert.equal(errors.length,0);});
test('Q24 property matrix: all recipes remain valid and reproducible at 12 keys',()=>{for(const r of G.RECIPES)for(let key=0;key<12;key++){const a=G.recipeProject(r.id,{key,seed:42}),b=G.recipeProject(r.id,{key,seed:42});G.validateProject(a);assert.deepEqual(json(G.compileSong(a).events.map(n=>[n.pitch,n.start,n.duration,n.velocity])),json(G.compileSong(b).events.map(n=>[n.pitch,n.start,n.duration,n.velocity])));}});

import fs from 'node:fs';import vm from 'node:vm';
test('Q25 newly generated documents remain readable by the unchanged 1.7.1 v3 validator',()=>{const legacy={...G};const c=vm.createContext({GridTone:legacy,console});vm.runInContext(fs.readFileSync(new URL('./fixtures/model-1.7.1.js',import.meta.url),'utf8'),c);for(const recipe of G.RECIPES){const p=G.recipeProject(recipe.id);assert.equal(legacy.validateProject(json(p)).version,3);}});
