import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {studioRuntime} from './studio-runtime.mjs';import {root} from './runtime.mjs';
const G=studioRuntime(),ctx=vm.createContext({GridTone:G});ctx.globalThis=ctx;for(const path of ['music/time-edit','creation/batch-placement'])vm.runInContext(fs.readFileSync(root+'/src/'+path+'.js','utf8'),ctx);
const plain=x=>JSON.parse(JSON.stringify(x));
function song(){const p=G.blankProject();p.bars=16;const t=p.tracks[0],pat=t.patterns[0];pat.bars=8;pat.notes=[G.newNote(60,0,8*G.BAR,.7),G.newNote(64,3*G.BAR,2*G.BAR,.6)];G.confirmHarmony(pat,{version:1,events:[{start:0,duration:8*G.BAR,rootPitchClass:0,quality:'major'}]});return G.validateProject(p);}
function absolute(p){return p.tracks.flatMap(t=>t.clips.flatMap(c=>t.patterns.find(x=>x.id===c.patternId).notes.map(n=>({start:c.bar*G.BAR+n.start,end:c.bar*G.BAR+n.start+n.duration,pitch:n.pitch}))));}
test('Recovery: shrinking tail respects a placed empty block',()=>{const p=song();p.tracks[0].patterns[0].notes=[];assert.equal(G.trimSong(p).project.bars,8);assert.throws(()=>G.resizeSong(p,7));});
test('Recovery: tail trim only changes song length',()=>{const p=song(),r=G.trimSong(p).project;assert.equal(r.bars,8);assert.deepEqual(plain(r.tracks),plain(p.tracks));});
test('Recovery: resize rejects invalid lengths',()=>{for(const x of [0,-1,257,1.5,NaN,'8'])assert.throws(()=>G.resizeSong(song(),x));});
test('Recovery: time clear retains length and leaves an actual gap',()=>{const p=song(),r=G.editSongTime(p,{startBar:2,endBar:4,kind:'clear'}).project;assert.equal(r.bars,16);assert.ok(absolute(r).every(n=>n.end<=2*G.BAR||n.start>=4*G.BAR));assert.equal(p.tracks[0].patterns[0].notes.length,2);});
test('Recovery: time delete shifts all tracks equally',()=>{const p=song(),second=G.newTrack();second.clips[0].bar=8;second.patterns[0].notes=[G.newNote(72,0,960,.7)];p.tracks.push(second);const r=G.editSongTime(p,{startBar:2,endBar:4,kind:'delete'}).project;assert.equal(r.bars,14);assert.equal(r.tracks[1].clips[0].bar,6);assert.equal(r.tracks[1].patterns[0].notes[0].start,0);assert.ok(G.validateProject(r));});
test('Recovery: deleting the whole time is rejected; clearing is allowed',()=>{assert.throws(()=>G.editSongTime(song(),{startBar:0,endBar:16,kind:'delete'}));const r=G.editSongTime(song(),{startBar:0,endBar:16,kind:'clear'}).project;assert.equal(r.bars,16);assert.equal(r.tracks[0].clips.length,0);assert.equal(r.tracks[0].patterns.length,1);});
test('Recovery: sliced harmonic intent follows notes',()=>{const r=G.editSongTime(song(),{startBar:2,endBar:4,kind:'delete'}).project;for(const t of r.tracks)for(const c of t.clips){const p=t.patterns.find(x=>x.id===c.patternId);assert.equal(G.harmonyStatus(p),'confirmed');assert.equal(p.harmony.events[0].duration,p.bars*G.BAR);}});
test('Recovery: stale harmonic intent remains stale after time operation',()=>{const p=song();p.tracks[0].patterns[0].notes[0].pitch++;const r=G.editSongTime(p,{startBar:2,endBar:4,kind:'clear'}).project;for(const c of r.tracks[0].clips)assert.equal(G.harmonyStatus(r.tracks[0].patterns.find(x=>x.id===c.patternId)),'stale');});
test('Recovery: retained notes and empty ranges are clipped validly',()=>{const p=song(),pat=p.tracks[0].patterns[0];pat.retention={notes:[{id:pat.notes[0].id,all:true}],ranges:[{start:0,end:8*G.BAR}]};const r=G.editSongTime(p,{startBar:2,endBar:4,kind:'delete'}).project;for(const c of r.tracks[0].clips){const q=r.tracks[0].patterns.find(x=>x.id===c.patternId);assert.equal(q.retention.notes.length,1);assert.equal(q.retention.ranges[0].end,q.bars*G.BAR);}assert.ok(G.validateProject(r));});
test('Recovery: shared patterns outside edited range retain originals',()=>{const p=song(),t=p.tracks[0];t.clips.push({id:G.uid('c'),bar:8,patternId:t.patterns[0].id});const id=t.patterns[0].id,copy=plain(t.patterns[0]);const r=G.editSongTime(p,{startBar:2,endBar:4,kind:'delete'}).project;assert.deepEqual(plain(r.tracks[0].patterns.find(x=>x.id===id)),copy);assert.equal(r.tracks[0].clips.at(-1).bar,6);});
for(const [a,b] of [[0,1],[1,3],[2,7],[3,6],[4,8],[0,8],[8,16],[7,9]])test(`Recovery: serialized time edits ${a}..${b} remain valid`,()=>{for(const kind of ['clear','delete']){const result=G.editSongTime(song(),{startBar:a,endBar:b,kind});assert.ok(G.validateProject(JSON.parse(JSON.stringify(result.project))));assert.ok(result.project.tracks.flatMap(t=>t.patterns).every(p=>G.PATTERN_BARS.includes(p.bars)));}});
test('Recovery: invalid ranges are atomic',()=>{for(const [a,b] of [[-1,2],[2,2],[0,17],[.5,2]]){const p=song(),before=JSON.stringify(p);assert.throws(()=>G.editSongTime(p,{startBar:a,endBar:b,kind:'clear'}));assert.equal(JSON.stringify(p),before);}});
test('Recovery: song tick mapping covers before, within, after deletion',()=>{const e={kind:'delete',startBar:2,endBar:4,bars:14};assert.equal(G.mapSongTick(1*G.BAR,e),1*G.BAR);assert.equal(G.mapSongTick(3*G.BAR,e),2*G.BAR);assert.equal(G.mapSongTick(8*G.BAR,e),6*G.BAR);});
function item(kind='melodic',pitch=60,bars=2){return {id:G.uid('test'),version:1,type:'pattern',name:'恢复测试模板',kind,bars,key:0,scale:'major',presetId:kind==='drum'?'drums':G.blankProject().tracks[0].preset,drumkitId:'builtin.standard',notes:[G.newNote(pitch,0,240,.7)]};}
test('Recovery: ordered batch adds independent clips preserving track sound',()=>{const p=G.blankProject(),t=p.tracks[0],sound=t.preset;t.clips=[];const a=item(),b=item();const r=G.planBatchPlacement(p,[a,b],{mode:'series',trackId:t.id,bar:1});assert.deepEqual(plain(r.project.tracks[0].clips.map(c=>c.bar)),[1,3]);assert.equal(r.project.tracks[0].preset,sound);assert.equal(r.project.bars,5);assert.notEqual(r.clipIds[0],r.clipIds[1]);});
test('Recovery: parallel batch allocates tracks at same position',()=>{const p=G.blankProject(),r=G.planBatchPlacement(p,[item(),item('drum',36)],{mode:'parallel',bar:2});assert.equal(r.project.tracks.length,3);assert.ok(r.project.tracks.slice(1).every(t=>t.clips[0].bar===2));assert.ok(G.validateProject(r.project));});
test('Recovery: mixed-kind series batch is rejected',()=>{const p=G.blankProject();assert.throws(()=>G.planBatchPlacement(p,[item(),item('drum',36)],{mode:'series',trackId:p.tracks[0].id,bar:2}));});
test('Recovery: batch overlap is rejected without partial writes',()=>{const p=G.blankProject(),before=JSON.stringify(p);assert.throws(()=>G.planBatchPlacement(p,[item(),item()],{mode:'series',trackId:p.tracks[0].id,bar:0}));assert.equal(JSON.stringify(p),before);});
test('Recovery: batch exceeding timeline is rejected',()=>assert.throws(()=>G.planBatchPlacement(G.blankProject(),[item(),item()],{mode:'parallel',bar:255})));
test('Recovery: existing source data unaffected by new UI',()=>{const before=fs.readFileSync(root+'/src/audio.js','utf8');assert.ok(before.includes('AudioEngine'));assert.equal(G.projectPresets(G.blankProject()).length>=76,true);});
