/** Integrated production-controller journey; pointer widgets are covered in interactions/closure. */
import assert from 'node:assert/strict';import {writeFile,mkdir} from 'node:fs/promises';import {harness} from './browser-harness.mjs';
const h=await harness(),p=h.page,results=[];await mkdir(h.output+'/fixtures',{recursive:true});let passed=false;
try{for(const view of ['arrange','edit']){
 const result=await p.evaluate(async view=>{
  const G=GridTone,A=GridToneApp,steps=[];const ensure=(ok,message)=>{if(!ok)throw Error(message);};
  const commit=r=>{const c=A.creation.c.commit(r);ensure(c.ok!==false,c.error?.message);};
  const select=t=>A.openPattern({trackId:t.id,clipId:t.clips.at(-1).id,edit:false});
  const add=(preset,role)=>{const doc=A.getProject(),t=G.newTrack(role==='drums'?'drum':'melodic',doc.tracks.length,preset);t.role=role;t.patterns[0].bars=4;doc.tracks.push(t);commit({project:doc,trackId:t.id,patternId:t.patterns[0].id,clipId:t.clips[0].id});return t.id;};
  const doc=G.blankProject();doc.title='18步整体验证 · '+view;doc.bpm=160;doc.tracks[0].patterns[0].bars=4;doc.tracks[0].role='chords';await A.loadProject(doc);A.changeView(view);steps.push('01 blank A and persistent shelf');
  const chord=A.shelf.all().find(t=>t.type==='pattern'&&t.harmony&&t.bars===4);ensure(chord,'four-bar chord material missing');A.shelf.choose(chord.id);await A.shelf.apply({trackId:doc.tracks[0].id,clipId:doc.tracks[0].clips[0].id,start:0,end:4*G.BAR});const sourceId=doc.tracks[0].id;ensure(A.getProject().tracks[0].patterns[0].harmony,'harmony missing');steps.push('02 four-bar chord placed in current range');
  const drumsId=add('drums','drums'),drums=A.getProject().tracks.find(t=>t.id===drumsId),beat=A.shelf.all().find(t=>t.type==='pattern'&&t.kind==='drum'&&t.bars<=4);A.shelf.choose(beat.id);await A.shelf.apply({trackId:drumsId,clipId:drums.clips[0].id,start:0,end:4*G.BAR});ensure(G.compileSong(A.getProject()).events.some(n=>n.trackId===drumsId),'drum output missing');steps.push('03 drum material with role mapping');
  const melodyId=add('marimba','melody');select(A.getProject().tracks.find(t=>t.id===melodyId));A.creation.open('generate');Object.assign(A.creation.session,{sourceTrackId:sourceId,rhythmTemplateId:'rhythm.recipe.pop',seed:37});steps.push('04 melody target and reusable rhythm skeleton');A.creation.generate();ensure(A.creation.session.candidates.length===3,'three candidates expected');steps.push('05 actual-instance harmony and three candidates');
  for(let index=0;index<2;index++){A.creation.handleAction('creation-choose',{dataset:{index:String(index)}});A.creation.handleAction('creation-preview',{});await new Promise(r=>setTimeout(r,150));ensure(A.playback.scope().range[0]===0&&A.playback.scope().range[1]===4*G.BAR,'wrong preview range');}A.creation.handleAction('creation-apply',{});A.playback.stop();steps.push('06 compare candidates in matching accompaniment');
  A.creation.open('ending');let x=A.creation.session;x.selected=x.base.tracks.find(t=>t.id===melodyId).patterns[0].notes.map(n=>n.id);A.creation.keep('rhythm');x.selected=x.selected.slice(0,2);A.creation.keep('all');A.creation.handleAction('creation-save-keeps',{});A.creation.open('ending');A.creation.session.sourceTrackId=sourceId;const retained=A.getProject().tracks.find(t=>t.id===melodyId).patterns[0];A.creation.generate();ensure(A.creation.session.candidates.length,'ending candidate missing');steps.push('07 retain rhythm and two notes, rewrite ending');
  const concurrent=A.getProject();concurrent.tracks.find(t=>t.id===drumsId).volume=.321;commit({project:concurrent});A.creation.handleAction('creation-apply',{});ensure(A.getProject().tracks.find(t=>t.id===drumsId).volume===.321,'parallel edit lost');const changed=A.getProject().tracks.find(t=>t.id===melodyId).patterns[0];ensure(JSON.stringify(changed.notes.map(n=>[n.id,n.start,n.duration]))===JSON.stringify(retained.notes.map(n=>[n.id,n.start,n.duration])),'retained timing changed');steps.push('08 preserve concurrent unrelated volume edit');
  const shared=A.getProject(),original=shared.tracks.find(t=>t.id===melodyId);shared.bars=8;shared.tracks[0].clips.push({id:G.uid('c'),patternId:shared.tracks[0].patterns[0].id,bar:4});original.clips.push({id:G.uid('c'),patternId:original.patterns[0].id,bar:4});commit({project:shared});const originalSnapshot=G.clone(original),dup=G.duplicateTrack(A.getProject(),melodyId);dup.project.tracks.find(t=>t.id===dup.trackId).name='独立 A′';commit(dup);ensure(JSON.stringify(A.getProject().tracks.find(t=>t.id===melodyId))===JSON.stringify(originalSnapshot),'original shared instances changed');steps.push('09 independent A-prime with original sharing preserved');
  add('roundbass','bass');add('cloudpad','texture');const groupBase=A.getProject(),settings={sourceTrackId:sourceId,sourceBar:0,bars:4,drumRole:'kick',density:'normal'},group=G.generateEnsembleGroup(groupBase,settings,17),reverse=G.clone(groupBase);reverse.tracks.reverse();const reordered=G.generateEnsembleGroup(reverse,settings,17);for(const id of group.trackIds){const notes=q=>q.tracks.find(t=>t.id===id).patterns.map(p=>G.musicalNotes(p.notes));ensure(JSON.stringify(notes(group.project))===JSON.stringify(notes(reordered.project)),'track order changes group music');}commit(group);steps.push('10 atomic drum/bass/texture group independent of visual track order');
  select(A.getProject().tracks.find(t=>t.id===melodyId));A.creation.open('arrange');Object.assign(A.creation.session,{bar:8,bars:16,sourceBar:0});A.creation.generate();ensure(A.creation.session.candidates.length,'arrangement missing');ensure(JSON.stringify(A.creation.session.candidates[0].outputRange)===JSON.stringify([8*G.BAR,24*G.BAR]),'wrong new arrangement bounds');A.creation.handleAction('creation-preview',{});await new Promise(r=>setTimeout(r,150));A.creation.handleAction('creation-apply',{});A.playback.stop();steps.push('11 place and preview bars 9 through 24');
  const unchanged=JSON.stringify(A.getProject()),history=JSON.stringify(A.getHistory());A.changeView('arrange');A.changeView('edit');A.changeView(view);ensure(JSON.stringify(A.getProject())===unchanged&&JSON.stringify(A.getHistory())===history,'navigation changed music/history');steps.push('12 shared state across workspaces');
  A.changeView('mix');A.creation.open('mix');A.creation.generate();const unmixed=JSON.stringify(A.getProject());A.creation.handleAction('creation-preview',{});await new Promise(r=>setTimeout(r,150));A.creation.close();ensure(JSON.stringify(A.getProject())===unmixed,'cancelled mix changed document');A.creation.open('mix');A.creation.generate();A.creation.handleAction('creation-apply',{});steps.push('13 third workspace mix compare/cancel/apply');
  const beforeSolo=JSON.stringify(A.getProject());document.querySelector('.mixer-channel [data-action="solo"]').click();ensure(JSON.stringify(A.getProject())===beforeSolo,'solo persisted');document.querySelector('[data-action="clear-solo"]')?.click();A.playback.stop();steps.push('14 temporary listening leaves project unchanged');
  await A.flushSave();const a=A.getProject();const b=G.blankProject();b.title='18步 B';b.tracks[0].patterns[0].notes=[G.newNote(72,0,240)];await A.loadProject(b);await A.flushSave();await A.loadProject(await G.projects.load(a.id),{fromLibrary:true});ensure(JSON.stringify(A.getProject())===JSON.stringify(a),'A/B storage crossed');steps.push('15 A/B editing and independent stored recovery');
  const midi=G.encodeMidi(a),full=await A.engine.exportWav(a),scope={kind:'song',range:[8*G.BAR,12*G.BAR]},ranged=await A.engine.exportWav(a,scope);ensure(midi.length>100&&full.peak>.001&&ranged.peak>.001,'exports empty');steps.push('16 actual full/range WAV, MIDI and serialized project');
  const encode=async blob=>{const bytes=new Uint8Array(await blob.arrayBuffer());let str='';for(let i=0;i<bytes.length;i+=32768)str+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(str);};
  return {project:a,steps,full:await encode(full.blob),range:await encode(ranged.blob),midi:Array.from(midi),seconds:[full.buffer.duration,ranged.buffer.duration]};
 },view);
 await p.reload();await p.waitForFunction(id=>GridToneApp?.getProject().id===id,result.project.id);assert.deepEqual(await p.evaluate(()=>GridToneApp.getProject()),result.project);result.steps.push('17 actual origin reload restores A');
 await p.goto(h.url.replace('/dist/index.html','/乐构.html'));await p.waitForFunction(()=>GridToneApp);assert.deepEqual(await p.evaluate(()=>GridToneApp.getProject()),result.project);result.steps.push('18 standalone delivery HTML restores A; independent archive rebuild verified separately');
 for(const [ext,bytes] of [['gridtone',Buffer.from(JSON.stringify(result.project))],['mid',Buffer.from(result.midi)],['wav',Buffer.from(result.full,'base64')],['range.wav',Buffer.from(result.range,'base64')]])await writeFile(h.output+'/fixtures/journey-'+view+'.'+ext,bytes);
 assert.ok(Math.abs(result.seconds[1]-(4*4*60/result.project.bpm+3))<.01,'ranged audio duration');results.push({view,status:'PASS',steps:result.steps,seconds:result.seconds});
}assert.deepEqual(h.errors,[]);passed=true;}finally{await writeFile(h.output+'/journey.json',JSON.stringify({status:passed?'PASS':'FAIL',sha256:h.sha256,date:new Date().toISOString(),results,errors:h.errors,method:'Integrated production-controller journey in two desktop workspaces with real storage/render and delivery HTML; widget pointer/keyboard tests separate.'},null,2));await h.close();}
