import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {harness} from './browser-harness.mjs';
const h=await harness(),page=h.page,checks=[];let passed=false;
const click=a=>page.locator(`button[data-action="${a}"]${a==='creation'?':not([data-mode])':''}`).filter({visible:true}).first().click();
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS',name);}
try{
 await page.evaluate(async()=>{const G=GridTone,A=GridToneApp,p=G.recipeProject('recipe.pop');await A.loadProject(p);A.openPattern({trackId:p.tracks.at(-1).id,clipId:p.tracks.at(-1).clips[0].id});});
 await check('C2 dock is nonmodal; field changes immediately remove old candidate',async()=>{await click('creation');assert.equal(await page.locator('#app').evaluate(e=>e.inert),false);await click('creation-generate');assert.equal(await page.locator('[data-action="creation-choose"]').count(),3);await page.locator('[data-field="creation-low"]').selectOption('62');assert.equal(await page.locator('[data-action="creation-apply"]').count(),0);assert.match(await page.locator('#creation-feedback').innerText(),/重新生成/);});
 await check('C1/C2 local application preserves current workspace, one history and independent edit',async()=>{await click('creation-generate');await page.evaluate(()=>GridToneApp.changeView('arrange'));const bass=await page.evaluate(()=>GridToneApp.getProject().tracks[2].id);await page.locator(`.arrange-row [data-track="${bass}"][data-range="track.volume"]`).evaluate(el=>{el.dispatchEvent(new Event('pointerdown',{bubbles:true}));el.value='.321';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});const before=await page.evaluate(()=>GridToneApp.getHistory().undo);await click('creation-apply');assert.equal(await page.evaluate(()=>GridToneApp.getState().view),'arrange');assert.equal(await page.evaluate(()=>GridToneApp.getProject().tracks[2].volume),.32);assert.equal(await page.evaluate(()=>GridToneApp.getHistory().undo),before+1);});
 await check('C2/C9 new arrangement owns absolute preview range',async()=>{await page.evaluate(()=>GridToneApp.creation.open('arrange'));await click('creation-generate');const output=await page.evaluate(()=>GridToneApp.creation.session.candidates[0]);assert.deepEqual(output.outputRange,[4*3840,12*3840]);await click('creation-preview-solo');await page.waitForFunction(()=>GridToneApp.engine.playing);assert.deepEqual(await page.evaluate(()=>GridToneApp.playback.scope().range),output.outputRange);await click('stop');await click('creation-close');});
 await check('C2/C9 no-clip project can use recipes and mixing',async()=>{await page.evaluate(async()=>{const p=GridTone.blankProject();p.tracks[0].clips=[];await GridToneApp.loadProject(p);GridToneApp.changeView('mix');GridToneApp.creation.open('mix');});await click('creation-generate');assert.ok(await page.locator('[data-action="creation-apply"]').isVisible());await click('creation-close');await page.evaluate(()=>GridToneApp.creation.open('recipe'));await click('creation-generate');assert.equal(await page.evaluate(()=>GridToneApp.creation.session.candidates[0].trackIds.length),5);await click('creation-close');});
 await check('C5 mouse drag and click placement use equivalent musical output',async()=>{
  const setup=async()=>{await page.evaluate(async()=>{const p=GridTone.blankProject();p.bars=8;p.tracks[0].clips=[];await GridToneApp.loadProject(p);GridToneApp.changeView('arrange');});await page.locator('[data-action="shelf-filter"][data-filter="melody"]').click();return page.locator('.shelf-card[data-shelf-id]').first();};
  let card=await setup();const id=await card.getAttribute('data-shelf-id');await card.locator('[data-action="shelf-pick"]').click();await page.locator('.empty-bar[data-bar="0"]').first().click();const first=await page.evaluate(()=>GridTone.musicalNotes(GridToneApp.getProject().tracks[0].patterns.at(-1).notes));assert.equal(await page.evaluate(()=>GridToneApp.getHistory().undo),1);
  card=await setup();card=page.locator(`.shelf-card[data-shelf-id="${id}"]`);await card.dragTo(page.locator('.empty-bar[data-bar="0"]').first());assert.deepEqual(await page.evaluate(()=>GridTone.musicalNotes(GridToneApp.getProject().tracks[0].patterns.at(-1).notes)),first);assert.equal(await page.evaluate(()=>GridToneApp.getHistory().undo),1);assert.equal(await page.locator('.shelf-drop-ghost').count(),0);
 });
 await check('C4 desktop geometry and DOM order match the selected focus',async()=>{for(const view of ['arrange','edit','mix']){await page.evaluate(v=>GridToneApp.changeView(v),view);const geometry=await page.evaluate(()=>{const r=s=>document.querySelector(s)?.getBoundingClientRect();return {width:document.documentElement.scrollWidth,viewport:innerWidth,shelf:r('.template-shelf')?.height,workspace:r('.workspace-body')?.height,editor:r('.creation-workspace')?.top,arrange:r('.studio-arrangement')?.top,order:[...document.querySelector('.view-content').children].map(e=>e.id||e.className)};});assert.ok(geometry.width<=geometry.viewport);assert.ok(geometry.shelf<=geometry.workspace+1);if(view==='arrange'){assert.ok(geometry.arrange<geometry.editor);assert.equal(geometry.order[0],'arrangement-pane');}if(view==='edit'){assert.ok(geometry.editor<geometry.arrange);assert.equal(geometry.order[0],'creation-workspace');}}});
 await check('C5 piano-grid placement uses actual drop position and one undo step',async()=>{
  await page.evaluate(async()=>{const p=GridTone.blankProject();p.tracks[0].patterns[0].bars=8;p.bars=8;await GridToneApp.loadProject(p);GridToneApp.changeView('edit');});
  await page.locator('[data-action="shelf-filter"][data-filter="melody"]').click();const card=page.locator('.shelf-card[data-shelf-id]').first(),id=await card.getAttribute('data-shelf-id');await card.locator('[data-action="shelf-pick"]').click();
  const grid=page.locator('#note-grid'),coords=await grid.evaluate(e=>({x:Number(e.dataset.left)+Number(e.dataset.cellWidth)*16+2,y:80}));await grid.click({position:coords});const result=await page.evaluate(id=>{const p=GridToneApp.getProject(),t=p.tracks[0],template=GridToneApp.shelf.item(id);return {notes:GridTone.musicalNotes(t.patterns[0].notes),expected:GridTone.musicalNotes(template.notes.map(n=>({...n,start:n.start+GridTone.BAR}))),undo:GridToneApp.getHistory().undo};},id);assert.deepEqual(result.notes,result.expected);assert.equal(result.undo,1);await click('undo');assert.equal(await page.evaluate(()=>GridToneApp.getProject().tracks[0].patterns[0].notes.length),0);
 });
 await check('C5 long template offers an explicit independent position and protects current phrase',async()=>{
  await page.evaluate(async()=>{const p=GridTone.blankProject();p.tracks[0].patterns[0].bars=1;await GridToneApp.loadProject(p);GridToneApp.changeView('edit');});await page.locator('[data-action="shelf-filter"][data-filter="melody"]').click();await page.locator('[data-action="shelf-pick"]').first().click();await click('shelf-current');assert.equal(await page.locator('#shelf-new-bar').inputValue(),'2');await click('shelf-new-independent');const result=await page.evaluate(()=>GridToneApp.getProject());assert.equal(result.tracks[0].patterns[0].bars,1);assert.equal(result.tracks[0].patterns[0].notes.length,0);assert.equal(result.tracks[0].clips.at(-1).bar,1);assert.equal(await page.evaluate(()=>GridToneApp.getState().view),'edit');await click('undo');
 });
 await check('C4 closing dock after workspace change restores a usable focus',async()=>{
  await click('creation');await page.locator('.workspace-tabs [data-view="mix"]').click();await click('creation-close');assert.ok(await page.evaluate(()=>document.activeElement?.matches('button')&&document.activeElement.isConnected));
 });
 await check('C10 recording cancellation releases a late permission stream without starting recorder',async()=>{
  await page.evaluate(()=>{window.realMediaRecorder=MediaRecorder;window.recordingProbe={stopped:0,started:0};Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:()=>new Promise(resolve=>window.resolveRecording=()=>resolve({getTracks:()=>[{stop:()=>recordingProbe.stopped++}]}))});window.MediaRecorder=class{constructor(){recordingProbe.started++;}};const b=document.createElement('button');b.dataset.action='record';b.id='record-probe';document.body.append(b);});
  await page.locator('#record-probe').click();await page.waitForFunction(()=>typeof window.resolveRecording==='function');await click('close-modal');await page.evaluate(()=>resolveRecording());await page.waitForFunction(()=>recordingProbe.stopped===1);assert.equal(await page.evaluate(()=>recordingProbe.started),0);assert.equal(await page.locator('#record-time').count(),0);
 });
 await check('C10 denied microphone permission preserves project and remains retryable',async()=>{
  const before=await page.evaluate(()=>GridToneApp.getProject());await page.evaluate(()=>{Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{throw new DOMException('Permission denied','NotAllowedError');}});});await page.locator('#record-probe').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('录音未开始'));assert.deepEqual(await page.evaluate(()=>GridToneApp.getProject()),before);assert.equal(await page.locator('#record-time').count(),0);
 });
 await check('C10 real MediaRecorder encodes a synthetic microphone stream and saves embedded audio',async()=>{
  await page.evaluate(async()=>{window.MediaRecorder=realMediaRecorder;const ctx=new AudioContext(),osc=ctx.createOscillator(),dest=ctx.createMediaStreamDestination();osc.frequency.value=261.63;osc.connect(dest);osc.start();await ctx.resume();window.syntheticMic={ctx,osc,stream:dest.stream};Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>dest.stream});});
  await page.locator('#record-probe').click();await page.locator('#record-time').waitFor();await page.waitForTimeout(1100);await click('stop-record');await page.waitForFunction(()=>Object.keys(GridToneApp.getProject().assets).length>0);await page.evaluate(async()=>{await GridToneApp.flushSave();syntheticMic.osc.stop();await syntheticMic.ctx.close();});const before=await page.evaluate(()=>GridToneApp.getProject());assert.ok(Object.values(before.assets).every(a=>a.data.startsWith('data:audio/wav;base64,')));assert.ok(await page.evaluate(()=>syntheticMic.stream.getTracks().every(t=>t.readyState==='ended')));await page.reload();await page.waitForFunction(id=>GridToneApp?.getProject().id===id,before.id);assert.deepEqual(await page.evaluate(()=>GridToneApp.getProject()),before);
 });
 await check('C5 cancel, blur and project switch cannot apply an old shelf payload',async()=>{
  await page.evaluate(()=>{GridToneApp.changeView('arrange');GridToneApp.shelf.collapsed=false;GridToneApp.render();});
  const before=await page.evaluate(()=>GridToneApp.getProject());await page.locator('[data-action="shelf-pick"]').first().click();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>GridToneApp.shelf.selected),null);assert.deepEqual(await page.evaluate(()=>GridToneApp.getProject()),before);
  await page.locator('[data-action="shelf-pick"]').first().click();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal(await page.locator('.shelf-drop-ghost').count(),0);assert.deepEqual(await page.evaluate(()=>GridToneApp.getProject()),before);
  await page.locator('[data-action="shelf-pick"]').first().click();const fresh=await page.evaluate(async()=>{await GridToneApp.loadProject(GridTone.blankProject());const p=GridToneApp.getProject();await GridToneApp.shelf.apply({trackId:p.tracks[0].id,bar:1});return p;});assert.deepEqual(await page.evaluate(()=>GridToneApp.getProject()),fresh);assert.equal(await page.evaluate(()=>GridToneApp.getHistory().undo),0);
 });
 assert.deepEqual(h.errors,[]);passed=true;await page.screenshot({path:h.output+'/closure-workspace.png',fullPage:true});
}finally{await writeFile(h.output+'/closure.json',JSON.stringify({status:passed?'PASS':'FAIL',sha256:h.sha256,checks,errors:h.errors},null,2));await h.close();}
