import {readFileSync} from 'node:fs';const requireText=f=>readFileSync(new URL('../'+f,import.meta.url),'utf8');
import test from 'node:test';import assert from 'node:assert/strict';
import {runtime,json} from './runtime.mjs';
function setup(){const G=runtime(),p=G.recipeProject('recipe.pop'),s=G.createEditorSession(p),t=p.tracks.at(-1),pat=t.patterns[0],c=t.clips[0];if(!pat.notes.length)pat.notes=[G.newNote(60,0,240,.7),G.newNote(64,1920,480,.7),G.newNote(67,5760,960,.7)];G.openPatternInSession(s,p,{trackId:t.id,clipId:c.id});G.activateNotes(s,p);return {G,p,s,t,pat,c};}
function noteSelection(x,ids=x.pat.notes.slice(0,2).map(n=>n.id)){x.s.selected=ids;x.G.activateNotes(x.s,x.p);}
function apply(x,id){const r=x.G.performEditCommand(x.p,x.s,id);x.p=r.document;Object.assign(x.s,r.patch);x.G.reconcileSession(x.s,x.p);return r;}
const musical=p=>json(p.notes.map(n=>[n.pitch,n.start,n.duration,n.velocity]));
test('W01 new project opens one arrangement workspace with closed lower editor',()=>{const G=runtime(),p=G.blankProject(),s=G.createEditorSession(p);assert.equal(s.view,'arrange');assert.equal(s.editorOpen,false);assert.equal(s.editTarget.kind,'none');});
test('W02 opening a block shows its content without a second page',()=>{const x=setup();assert.equal(x.s.view,'arrange');assert.equal(x.s.editorOpen,true);assert.equal(x.s.clipId,x.c.id);});
test('W03 no active target never falls back to deleting opened content',()=>{const x=setup();x.G.setEditTarget(x.s,x.p,{kind:'none'});assert.equal(x.G.editCommandState(x.p,x.s,'delete').enabled,false);assert.throws(()=>apply(x,'delete'));});
test('W04 selecting track leaves opened pattern and cursor unchanged',()=>{const x=setup(),ids=[x.s.trackId,x.s.patternId,x.s.clipId];x.s.cursor=120;x.G.setEditTarget(x.s,x.p,{kind:'track',trackId:x.p.tracks[0].id});assert.deepEqual([x.s.trackId,x.s.patternId,x.s.clipId],ids);assert.equal(x.s.cursor,120);});
test('W05 note Copy never moves edit cursor or changes the project',()=>{const x=setup();noteSelection(x);x.s.cursor=123.5;const before=JSON.stringify(x.p);const out=apply(x,'copy');assert.equal(x.s.cursor,123.5);assert.equal(before,JSON.stringify(x.p));assert.equal(out.changed,false);assert.equal(x.s.editClipboard.kind,'notes');});
test('W06 note Paste uses explicit edit cursor, independent of transport fields',()=>{const x=setup();noteSelection(x,[x.pat.notes[0].id]);apply(x,'copy');x.s.cursor=6000.5;x.s.startTick=0;const r=apply(x,'paste');const out=x.p.tracks.at(-1).patterns[0];assert.ok(out.notes.some(n=>n.start===6000.5));assert.equal(r.changed,true);});
test('W07 overflow paste is rejected without clamp or mutation',()=>{const x=setup();noteSelection(x);apply(x,'copy');x.s.cursor=x.pat.bars*x.G.BAR-1;const before=JSON.stringify(x.p);assert.throws(()=>apply(x,'paste'),/超出/);assert.equal(JSON.stringify(x.p),before);});
test('W08 duplicate notes is immediate and independent of the clipboard',()=>{const x=setup();noteSelection(x,[x.pat.notes[0].id]);const n=x.pat.notes[0],before=x.pat.notes.length;apply(x,'duplicate');const p=x.p.tracks.at(-1).patterns[0];assert.equal(p.notes.length,before+1);assert.ok(p.notes.some(v=>v.id!==n.id&&v.start===n.start+n.duration));assert.equal(x.s.editClipboard,null);});
test('W09 Delete notes does not remove block instances',()=>{const x=setup();noteSelection(x);const clips=json(x.t.clips),before=x.pat.notes.length;apply(x,'delete');const t=x.p.tracks.at(-1);assert.equal(t.patterns[0].notes.length,before-2);assert.deepEqual(json(t.clips),clips);});
test('W10 Delete block removes only occurrence and keeps shared pattern',()=>{const x=setup();x.p.bars=8;x.t.clips.push({id:x.G.uid('c'),bar:4,patternId:x.pat.id});const other=x.t.clips[1].id;x.G.activateClips(x.s,x.p,[x.c.id],x.t.id);const notes=musical(x.pat);apply(x,'delete');const t=x.p.tracks.at(-1);assert.equal(t.clips.length,1);assert.equal(t.clips[0].id,other);assert.deepEqual(musical(t.patterns[0]),notes);assert.equal(x.s.editorOpen,false);});
test('W11 stale selection ids cannot delete a fallback block',()=>{const x=setup();x.G.setEditTarget(x.s,x.p,{kind:'clips',trackId:x.t.id,ids:['missing']});assert.equal(x.G.editCommandState(x.p,x.s,'delete').enabled,false);});
test('W12 music block duplicate creates independent pattern and ids',()=>{const x=setup();x.G.activateClips(x.s,x.p,[x.c.id],x.t.id);apply(x,'duplicate');const t=x.p.tracks.at(-1);assert.equal(t.clips.length,2);assert.equal(t.clips[1].bar,4);assert.notEqual(t.clips[1].patternId,t.clips[0].patternId);assert.equal(x.p.bars,8);});
test('W13 associated repeat keeps shared content explicit',()=>{const x=setup();x.G.activateClips(x.s,x.p,[x.c.id],x.t.id);apply(x,'linked');const t=x.p.tracks.at(-1);assert.equal(t.clips[0].patternId,t.clips[1].patternId);assert.equal(x.s.clipId,t.clips[1].id);});
test('W14 unlink isolates only selected shared occurrence',()=>{const x=setup();x.G.activateClips(x.s,x.p,[x.c.id],x.t.id);apply(x,'linked');apply(x,'unlink');const t=x.p.tracks.at(-1);assert.notEqual(t.clips[0].patternId,t.clips[1].patternId);assert.deepEqual(musical(t.patterns[0]),musical(t.patterns[1]));});
test('W15 music block clipboard pastes at arrangement cursor',()=>{const x=setup();x.G.activateClips(x.s,x.p,[x.c.id],x.t.id);apply(x,'copy');x.s.arrangeCursor={trackId:x.t.id,tick:8*x.G.BAR};apply(x,'paste');assert.equal(x.p.tracks.at(-1).clips.at(-1).bar,8);});
test('W16 block clipboard incompatible target is atomic',()=>{const x=setup();x.G.activateClips(x.s,x.p,[x.c.id],x.t.id);apply(x,'copy');x.s.arrangeCursor={trackId:x.p.tracks.find(t=>t.kind==='drum').id,tick:8*x.G.BAR};const before=JSON.stringify(x.p);assert.throws(()=>apply(x,'paste'),/类型/);assert.equal(before,JSON.stringify(x.p));});
test('W17 track copy and paste preserve internal sharing and isolate source',()=>{const x=setup();x.p.bars=8;x.t.clips.push({id:x.G.uid('c'),patternId:x.pat.id,bar:4});x.G.setEditTarget(x.s,x.p,{kind:'track',trackId:x.t.id});apply(x,'copy');apply(x,'paste');const copied=x.p.tracks.find(t=>t.id===x.s.editTarget.trackId);assert.notEqual(copied.id,x.t.id);assert.equal(copied.clips[0].patternId,copied.clips[1].patternId);assert.notEqual(copied.clips[0].patternId,x.pat.id);assert.deepEqual(musical(copied.patterns[0]),musical(x.pat));});
test('W18 Delete track cannot delete final remaining track',()=>{const G=runtime(),p=G.blankProject(),s=G.createEditorSession(p);G.setEditTarget(s,p,{kind:'track',trackId:p.tracks[0].id});assert.equal(G.editCommandState(p,s,'delete').enabled,false);});
test('W19 deleting different track keeps opened pattern intact',()=>{const x=setup();x.G.setEditTarget(x.s,x.p,{kind:'track',trackId:x.p.tracks[0].id});apply(x,'delete');assert.equal(x.s.trackId,x.t.id);assert.equal(x.s.editorOpen,true);assert.ok(x.p.tracks.some(t=>t.id===x.t.id));});
test('W20 two timelines cannot be active command owners simultaneously',()=>{const x=setup();noteSelection(x);x.G.activateClips(x.s,x.p,[x.c.id],x.t.id);assert.equal(x.G.resolveEditTarget(x.p,x.s).kind,'clips');assert.equal(x.s.selected.length,2);x.G.activateNotes(x.s,x.p);assert.equal(x.G.resolveEditTarget(x.p,x.s).kind,'notes');});
test('W21 Select all in notes never selects other tracks',()=>{const x=setup();apply(x,'select-all');assert.deepEqual(json(x.s.selected),json(x.pat.notes.map(n=>n.id)));assert.equal(x.s.editTarget.kind,'notes');});
test('W22 Select all in arrangement selects all occurrences',()=>{const x=setup();x.G.activateClips(x.s,x.p,[],x.t.id);apply(x,'select-all');assert.equal(x.s.editTarget.ids.length,x.p.tracks.reduce((n,t)=>n+t.clips.length,0));});
test('W23 mix page disables destructive composition commands',()=>{const x=setup();noteSelection(x);x.s.view='mix';for(const k of ['copy','paste','duplicate','delete'])assert.equal(x.G.editCommandState(x.p,x.s,k).enabled,false);});
test('W24 range copies silence and clips boundary sustains',()=>{const x=setup();x.pat.notes=[x.G.newNote(60,0,3000),x.G.newNote(64,6000,240)];const range={start:960,end:4800};x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:x.t.id,patternId:x.pat.id,clipId:x.c.id,range});apply(x,'copy');assert.equal(x.s.editClipboard.span,3840);assert.deepEqual(x.s.editClipboard.notes.map(n=>[n.start,n.duration]),[[0,2040]]);});
test('W25 range delete splits long note and preserves outside',()=>{const x=setup(),n=x.G.newNote(60,0,9600);x.pat.notes=[n];x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:x.t.id,patternId:x.pat.id,clipId:x.c.id,range:{start:1920,end:3840}});apply(x,'delete');const ns=x.p.tracks.at(-1).patterns[0].notes;assert.deepEqual(json(ns.map(n=>[n.start,n.duration])),[[0,1920],[3840,5760]]);assert.notEqual(ns[0].id,ns[1].id);});
test('W26 range duplicate preserves length including rests',()=>{const x=setup();x.pat.notes=[x.G.newNote(60,0,240)];x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:x.t.id,patternId:x.pat.id,clipId:x.c.id,range:{start:0,end:3840}});apply(x,'duplicate');assert.ok(x.p.tracks.at(-1).patterns[0].notes.some(n=>n.start===3840));});
test('W27 range clear preserves outside harmony intervals',()=>{const x=setup(),t=x.p.tracks[0],p=t.patterns[0];x.G.openPatternInSession(x.s,x.p,{trackId:t.id,clipId:t.clips[0].id});x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:t.id,patternId:p.id,clipId:t.clips[0].id,range:{start:3840,end:7680}});apply(x,'delete');const h=x.p.tracks[0].patterns[0].harmony;assert.deepEqual(json(h.events.map(e=>e.start)),[0,7680,11520]);assert.equal(x.G.harmonyStatus(x.p.tracks[0].patterns[0]),'confirmed');});
test('W28 clipboard from stale harmony never acquires confirmation',()=>{const x=setup(),t=x.p.tracks[0],p=t.patterns[0];p.notes[0].pitch++;x.G.openPatternInSession(x.s,x.p,{trackId:t.id,clipId:t.clips[0].id});x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:t.id,patternId:p.id,clipId:t.clips[0].id,range:{start:0,end:3840}});apply(x,'copy');x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:t.id,patternId:p.id,clipId:t.clips[0].id,range:{start:3840,end:7680}});apply(x,'paste');assert.equal(x.G.harmonyStatus(x.p.tracks[0].patterns[0]),'stale');});
test('W29 range copy/paste carries known harmony to empty destination',()=>{const x=setup(),t=x.p.tracks[0],p=t.patterns[0];x.G.openPatternInSession(x.s,x.p,{trackId:t.id,clipId:t.clips[0].id});x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:t.id,patternId:p.id,clipId:t.clips[0].id,range:{start:0,end:3840}});apply(x,'copy');x.G.openPatternInSession(x.s,x.p,{trackId:x.t.id,clipId:x.c.id});x.s.cursor=0;x.s.selected=[];x.G.activateNotes(x.s,x.p);x.p.tracks.at(-1).patterns[0].notes=[];apply(x,'paste');assert.equal(x.G.harmonyStatus(x.p.tracks.at(-1).patterns[0]),'confirmed');});
test('W30 applying range paste to occupied content requires explicit range',()=>{const x=setup();x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:x.t.id,patternId:x.pat.id,clipId:x.c.id,range:{start:0,end:3840}});apply(x,'copy');x.G.activateNotes(x.s,x.p);x.s.cursor=0;assert.throws(()=>apply(x,'paste'),/明确/);});
test('W31 range validity rejects reversed and out-of-bounds spans',()=>{const x=setup();for(const range of [{start:1,end:0},{start:0,end:1e9}]){x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:x.t.id,patternId:x.pat.id,range});assert.equal(x.s.editTarget.kind,'none');}});
test('W32 clipboard and editing targets remain outside musical document',()=>{const x=setup();noteSelection(x);const before=JSON.stringify(x.p);apply(x,'copy');x.G.setEditTarget(x.s,x.p,{kind:'track',trackId:x.t.id});assert.equal(JSON.stringify(x.p),before);assert.equal('editTarget'in x.p,false);});
test('W33 every exposed basic command has one state definition',()=>{const x=setup();for(const [id,def]of Object.entries(x.G.EDIT_COMMANDS)){assert.ok(def.label&&def.kinds.length);const state=x.G.editCommandState(x.p,x.s,id);assert.equal(typeof state.enabled,'boolean');}});
test('W34 note clipboard rejects drum targets without mutation',()=>{const x=setup();noteSelection(x);apply(x,'copy');const t=x.p.tracks.find(t=>t.kind==='drum');x.G.openPatternInSession(x.s,x.p,{trackId:t.id,clipId:t.clips[0].id});x.s.selected=[];x.G.activateNotes(x.s,x.p);assert.equal(x.G.editCommandState(x.p,x.s,'paste').enabled,false);});
test('W35 empty range can be copied as intentional rest',()=>{const x=setup();x.pat.notes=[];x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:x.t.id,patternId:x.pat.id,range:{start:0,end:3840}});apply(x,'copy');assert.equal(x.s.editClipboard.span,3840);assert.equal(x.s.editClipboard.notes.length,0);});
test('W36 duplicate clips checks collisions without partial inserts',()=>{const x=setup();x.p.bars=8;x.t.clips.push({id:x.G.uid('c'),patternId:x.pat.id,bar:4});x.G.activateClips(x.s,x.p,[x.c.id],x.t.id);const before=JSON.stringify(x.p);assert.throws(()=>apply(x,'duplicate'),/已有/);assert.equal(before,JSON.stringify(x.p));});
test('W37 clear pattern explicitly clears related content, not clip identity',()=>{const x=setup();noteSelection(x);const c=json(x.t.clips);apply(x,'clear');assert.deepEqual(json(x.p.tracks.at(-1).clips),c);assert.equal(x.p.tracks.at(-1).patterns[0].notes.length,0);});
test('W38 note range delete maintains valid retained references',()=>{const x=setup(),n=x.G.newNote(60,0,9600);x.pat.notes=[n];x.pat.retention={notes:[{id:n.id,all:true}],ranges:[{start:0,end:9600}]};x.G.setEditTarget(x.s,x.p,{kind:'range',trackId:x.t.id,patternId:x.pat.id,range:{start:1920,end:3840}});apply(x,'delete');const p=x.p.tracks.at(-1).patterns[0];assert.equal(p.retention.notes.length,2);assert.deepEqual(json(p.retention.ranges.map(r=>[r.start,r.end])),[[0,1920],[3840,9600]]);x.G.validateProject(x.p);});
test('W39 deletion of selected pattern invalidates target, never falls back',()=>{const x=setup();noteSelection(x);x.t.clips=[];x.t.patterns=[x.G.newPattern()];x.G.reconcileSession(x.s,x.p);assert.equal(x.s.editTarget.kind,'none');});
test('W40 copies retain current input document and legacy file version',()=>{const x=setup();noteSelection(x);apply(x,'duplicate');assert.equal(x.p.version,3);assert.deepEqual(json(x.G.validateProject(JSON.parse(JSON.stringify(x.p)))),json(x.p));});
function storage(){const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};}
test('W41 legacy phrase workspace preference migrates without rewriting music',()=>{const localStorage=storage(),G=runtime({localStorage}),p=G.demoProject(),s=G.createEditorSession(p),before=JSON.stringify(p);localStorage.setItem('gridtone.workspace.'+p.id,JSON.stringify({view:'edit',layoutVersion:2,editorHeight:510,editorOpen:true,trackId:p.tracks[0].id,patternId:p.tracks[0].patterns[0].id}));G.restoreWorkspace(s,p);assert.equal(s.view,'arrange');assert.equal(s.editorHeight,510);assert.equal(s.editorOpen,true);assert.equal(JSON.stringify(p),before);});
test('W42 save/reload workspace keeps panel size and open state, not live selection',()=>{const localStorage=storage(),G=runtime({localStorage}),p=G.demoProject(),s=G.createEditorSession(p);s.editorHeight=477;s.editorExpanded=true;s.editorOpen=true;s.editTarget={kind:'track',trackId:p.tracks[0].id};G.saveWorkspace(s,p.id);const r=G.createEditorSession(p);G.restoreWorkspace(r,p);assert.equal(r.editorHeight,477);assert.equal(r.editorExpanded,true);assert.equal(r.editTarget.kind,'none');assert.equal(r.rightPanel,null);});
test('W43 closed editor preference stays closed when restored',()=>{const localStorage=storage(),G=runtime({localStorage}),p=G.demoProject(),s=G.createEditorSession(p);s.editorOpen=false;s.editorManuallyClosed=true;G.saveWorkspace(s,p.id);const r=G.createEditorSession(p);G.restoreWorkspace(r,p);assert.equal(r.editorManuallyClosed,true);assert.equal(r.editorOpen,false);});
test('W44 same shared content opened at a different instance reports change',()=>{const x=setup();x.p.bars=8;x.t.clips.push({id:x.G.uid('c'),bar:4,patternId:x.pat.id});const r=x.G.openPatternInSession(x.s,x.p,{trackId:x.t.id,clipId:x.t.clips[1].id});assert.equal(r.changed,true);assert.equal(x.s.clipId,x.t.clips[1].id);});
test('W45 expanding whole pattern copy preserves legacy metadata shape',()=>{const x=setup();x.G.setEditTarget(x.s,x.p,{kind:'clips',trackId:x.p.tracks[0].id,ids:[x.p.tracks[0].clips[0].id]});apply(x,'duplicate');const t=x.p.tracks[0];assert.equal(x.G.harmonyStatus(t.patterns[0]),'confirmed');assert.equal(x.G.harmonyStatus(t.patterns[1]),'confirmed');x.G.validateProject(x.p);});
test('W46 track clipboard copied into another project includes self-contained voice settings',()=>{const x=setup();x.G.setEditTarget(x.s,x.p,{kind:'track',trackId:x.t.id});apply(x,'copy');x.p=x.G.blankProject();x.s.view='arrange';x.G.setEditTarget(x.s,x.p,{kind:'track',trackId:x.p.tracks[0].id});apply(x,'paste');assert.equal(x.p.tracks.length,2);assert.equal(x.p.tracks[1].preset,x.t.preset);x.G.validateProject(x.p);});

test('W47 repeated selection ids resolve to one object',()=>{const x=setup(),id=x.pat.notes[0].id;x.G.setEditTarget(x.s,x.p,{kind:'notes',trackId:x.t.id,patternId:x.pat.id,clipId:x.c.id,ids:[id,id]});assert.equal(x.s.editTarget.ids.length,1);x.G.activateClips(x.s,x.p,[x.c.id,x.c.id],x.t.id);assert.equal(x.s.editTarget.ids.length,1);});
test('W48 current build has one layout owner and no old properties renderer',()=>{const data=JSON.parse(requireText('assets.json'));assert.ok(data.styles.includes('src/styles/workspace.css'));for(const file of ['src/styles/legou.css','src/styles/studio.css','src/styles/responsive.css'])assert.ok(!data.styles.includes(file));assert.ok(!data.scripts.includes('src/views/properties.js'));});

test('W49 explicit quantization aligns onset only and preserves identity/duration',()=>{const x=setup(),source=[x.G.newNote(60,130,121),x.G.newNote(64,370,83)];const out=x.G.quantizeStarts(source,240,3840);assert.deepEqual(json(out.map(n=>n.start)),[240,480]);assert.deepEqual(json(out.map(n=>[n.id,n.pitch,n.duration,n.velocity])),json(source.map(n=>[n.id,n.pitch,n.duration,n.velocity])));});
test('W50 quantization rejects free-grid and overflow rather than silently cropping',()=>{const x=setup();assert.throws(()=>x.G.quantizeStarts([x.G.newNote(60,0,240)],0,3840));assert.throws(()=>x.G.quantizeStarts([x.G.newNote(60,3601,239)],480,3840));assert.throws(()=>x.G.quantizeStarts([x.G.newNote(60,130,100)],240,3840,{start:0,end:250}));});
