/** Production component and combination gallery. Uses the actual renderers and an isolated demo document. */
(function(){'use strict';const G=GridTone,U=G.ui,B=U.Button,root=document.querySelector('#samples');
 const recipe=G.recipeProject('recipe.pop'),single=G.getTemplate(G.catalogTemplates().find(t=>t.type==='pattern'&&t.role==='chords').id);
 const buttons=['primary','secondary','quiet','danger'].map(variant=>`<section><h2>${({primary:'主要动作',secondary:'次要动作',quiet:'轻量动作',danger:'危险操作'})[variant]}</h2><div class="sample-row">${['normal','small','icon'].map(size=>B({action:'sample',label:'试听',icon:'play',variant,size})).join('')}${B({action:'sample',label:'已选中',variant,pressed:true})}${B({action:'sample',label:'正在处理',variant,busy:true})}${B({action:'sample',label:'暂不可用',variant,disabled:true})}</div></section>`).join('');
 const objects=[U.musicBlock.model(single),U.musicBlock.model({...G.RECIPES[0],type:'recipe',role:'song'}),U.musicBlock.model({id:'gallery.song',type:'song',name:'示例作品',project:recipe})];
 const d=G.blankProject(),t=d.tracks[0],pat=t.patterns[0],ws=G.createEditorSession(d);pat.notes=[G.newNote(60,0,240),G.newNote(64,960,480)];const targets=[{kind:'none'},{kind:'clips',trackId:t.id,ids:[t.clips[0].id]},{kind:'notes',trackId:t.id,patternId:pat.id,clipId:t.clips[0].id,ids:pat.notes.map(n=>n.id)},{kind:'range',trackId:t.id,patternId:pat.id,clipId:t.clips[0].id,range:{start:0,end:1920}},{kind:'track',trackId:t.id}];const commands=targets.map((target,i)=>{G.setEditTarget(ws,d,target);return G.views.renderEditBar({project:d,S:ws,...U}).replace('id="edit-command-bar"','id="example-command-'+i+'"');}).join('');
 const sound=G.views.soundCards({project:recipe,S:{soundSource:'curated',tab:'键盘',query:''},track:()=>recipe.tracks[0],icon:U.icon,esc:U.esc,button:U.button});
 const notices=['info','warning','error','success'].map(tone=>U.InlineNotice({tone,title:({info:'准备好材料',warning:'参考和弦已经变化',error:'这次没有保存成功',success:'已经放入作品'})[tone],text:'状态文字与下一步动作留在当前位置。',actions:B({action:'sample',label:'查看详情',size:'small'})})).join('');
 root.innerHTML=`<section><h2>同一规格，在所有页面一致</h2><p>normal 40px / 16px，small 32px / 14px，icon 36px。图标、触感、聚焦和状态是同一套规则。</p></section>${buttons}<section><h2>同一操作栏，明确的五种对象</h2>${commands}</section><section><h2>可拿取的音乐</h2><div class="gallery-materials">${objects.map((m,i)=>U.musicBlock.card(m,{picked:i===0,favorite:i===1,audition:false})).join('')}</div></section><section><h2>数值与选择 · 面板内嵌</h2><div class="sample-row"><label class="form-label">默认<input value="108" type="number" aria-label="默认速度"></label><label class="form-label">选择<select aria-label="声音类型样例"><option>模拟电路</option><option>FM 数字</option></select></label><label class="form-label">禁用<input value="尚未选择音轨" disabled></label><label class="form-label">错误<input value="0" type="number" aria-invalid="true" aria-describedby="sample-field-error"><span id="sample-field-error">小节从 1 开始。</span></label></div><p>底线提示可编辑，数字保留文字光标；Tab 检查聚焦外圈。播放键保留按压感，普通操作保持轻量。</p></section><section><h2>字段与单位</h2><div class="sample-row">${U.Field({field:'gallery-position',label:'位置 · 小节.拍',value:U.format.position(5760)})}${U.Field({field:'gallery-name',label:'一段很长的中文标题也需要保持完整',value:'晴天下午，慢慢写下的一小段旋律'})}${U.slider('左右位置','track','pan',0,-1,1,.01)}${U.Toggle({field:'gallery-toggle',label:'生成时保留节奏',checked:true})}</div></section><section><h2>组合：生成前与生成后</h2><p>以下两栏直接运行生产CreationUI和本地生成器。它们使用独立演示作品，样例不接入声音或存档。</p><div class="gallery-panels"><aside id="gallery-prepare" class="creation-dock"></aside><aside id="gallery-result" class="creation-dock"></aside></div></section><section><h2>组合：本轨音色</h2><p>卡片直接来自生产声音浏览器，独立试听与使用拥有不同的动作。</p><div class="creation-dock gallery-sound"><div class="sound-grid">${sound}</div></div></section><section><h2>状态与恢复</h2><div class="gallery-notices">${notices}</div></section><section><h2>专用控制</h2><p>琴键、传输播放键、音乐块和普通文字按钮有不同职责，使用已登记的专用形态。</p><div class="sample-row">${U.button('sample','','play','play-btn','aria-label="播放"')}${U.ib('sample-stop','停止','stop','','secondary')}<div class="creation-dock" style="width:300px">${G.views.auditionKeys(4,U.button)}</div></div></section>`;
 const sample=(id,generate)=>{const project=G.clone(recipe),t=project.tracks.at(-1),s=G.createEditorSession(project);G.openPatternInSession(s,project,{trackId:t.id,clipId:t.clips[0].id});s.rightPanel='creation';const c={getProject:()=>project,getSession:()=>s,button:U.button,esc:U.esc,playback:{endAudition(){}},closeModal(){},openCreation:(title,body,subtitle)=>document.getElementById(id).innerHTML=U.PanelHeader({title,subtitle})+body,toast(){}};const ui=new G.CreationUI(c);ui.open('generate');if(generate)ui.generate();document.getElementById(id).querySelectorAll('button').forEach(b=>{b.addEventListener('click',e=>e.preventDefault());});};
 sample('gallery-prepare',false);sample('gallery-result',true);
 root.addEventListener('click',e=>{if(e.target.closest('[data-action]'))e.preventDefault();});
 document.querySelectorAll('[data-gallery-skin]').forEach(b=>b.addEventListener('click',()=>{delete document.documentElement.dataset.direction;document.querySelector('[data-gallery-direction]')?.setAttribute('aria-pressed','false');document.documentElement.dataset.skin=b.dataset.gallerySkin;document.querySelectorAll('[data-gallery-skin]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));}));
 document.querySelector('[data-gallery-direction]')?.addEventListener('click',()=>{document.documentElement.dataset.skin='crystal';document.documentElement.dataset.direction='clear';document.querySelectorAll('[data-gallery-skin]').forEach(b=>b.setAttribute('aria-pressed','false'));document.querySelector('[data-gallery-direction]').setAttribute('aria-pressed','true');});
})();
