/** View renderer. Receives the current document and session; never mutates either. */
(function (G) {
    'use strict';
    G.views ||= {};
    G.views.renderArrange = function (C) {
        const { project, S, B, track, pattern, button, ib, icon, esc, miniPattern, slider, presetName, trackIcon, soundCards, waveIllustration, renderSound, renderPipeline } = C;
        const { KEYS, PRESETS, clamp, noteName, presetById, canPlace } = G;
        const bw = G.UI_METRICS.barWidth, w = project.bars * bw, sel = project.tracks.flatMap(t => t.clips.map(c => ({ ...c, t }))).find(c => c.id === S.clipId);
        return `<div class="view-heading compact-heading"><div><span class="eyebrow">SONG / 整曲结构</span><h1>编排 <span class="pill">${project.tracks.length} 轨 / ${project.bars} 小节</span></h1><p>空白处放片段 · 拖动编排 · 双击编辑</p></div><div class="heading-actions">${button('add-track', '添加音轨', 'plus', 'dark-btn')}${button('repeat-song', '整段重复', 'copy', 'soft-btn')}${button('add-bars', '增加 4 小节', 'plus', 'soft-btn')}</div></div>
 <div class="monitor-toolbar"><span>${B.selectedTrackIds.length ? `已选 ${B.selectedTrackIds.length} 条音轨` : '勾选后一起试听'}</span>${button('listen-tracks', '试听所选', 'headphones', 'quiet', B.selectedTrackIds.length ? '' : 'disabled')}${(B.soloIds.length || B.target === 'tracks') ? button('clear-solo', '恢复全曲', '', 'soft-btn') : ''}<small>静音会保存；“只听”仅临时试听。</small></div>
 <section class="arrange-card"><div class="arrange-scroll" data-scroll="arrange"><div class="arrange-inner" style="min-width:${w + G.UI_METRICS.trackHead}px"><div class="timeline-ruler"><div class="ruler-label">${project.tracks.length} 条音轨</div><div class="ruler-bars">${Array.from({ length: project.bars }, (_, i) => `<div style="width:${100 / project.bars}%"><span>${i + 1}</span>${i === 0 ? '<small>起点</small>' : ''}</div>`).join('')}</div></div>
 ${project.tracks.map(t => `<div class="arrange-row" data-track="${t.id}"><div class="arrange-track-head ${t.id === S.trackId ? 'current' : ''}" style="--track:${t.color}"><div class="track-title-row"><input type="checkbox" data-field="monitor-track" data-id="${t.id}" aria-label="选择试听 ${esc(t.name)}" ${B.selectedTrackIds.includes(t.id) ? 'checked' : ''}><button class="arrange-track-name" data-action="track" data-id="${t.id}"><span>${icon(trackIcon(t), 18)}</span><div><strong>${esc(t.name)}</strong><small>${esc(presetName(t))}</small></div></button></div><div class="track-controls">${button('mute', '静音', '', t.mute ? 'active' : '', `data-id="${t.id}" title="作品静音" aria-pressed="${t.mute}"`)}${button('solo', '只听', '', B.soloIds.includes(t.id) ? 'active' : '', `data-id="${t.id}" title="可同时只听多轨；不写入作品" aria-pressed="${B.soloIds.includes(t.id)}"`)}<input type="range" min="0" max="1" step=".01" value="${t.volume}" data-range="track.volume" data-track="${t.id}" aria-label="${esc(t.name)} 音量"></div></div><div class="arrange-lane" data-track="${t.id}" data-bars="${project.bars}" style="--bar-width:${100 / project.bars}%">${Array.from({ length: project.bars }, (_, i) => `<button class="empty-bar" data-action="place-clip" data-track="${t.id}" data-bar="${i}" style="left:${i * 100 / project.bars}%;width:${100 / project.bars}%" aria-label="${esc(t.name)}，第 ${i + 1} 小节，添加片段">+</button>`).join('')}${t.clips.map(c => { const p = t.patterns.find(p => p.id === c.patternId), links = t.clips.filter(x => x.patternId === p.id).length; return `<div class="song-clip ${c.id === S.clipId ? 'selected' : ''}" data-clip="${c.id}" data-track="${t.id}" style="left:calc(${c.bar * 100 / project.bars}% + 3px);width:calc(${p.bars * 100 / project.bars}% - 6px);--track:${t.color}" title="${esc(p.name)} · ${links} 处共享" tabindex="0" role="button" aria-label="${esc(p.name)}，第 ${c.bar + 1} 小节"><header><b>${esc(p.name)}</b>${links > 1 ? icon('link', 11) : ''}</header>${miniPattern(p, t, Math.max(50, p.bars * bw - 18), 30)}</div>`; }).join('')}</div></div>`).join('')}</div></div>
 <div class="arrange-bottom"><span>${sel ? `<b>${esc(sel.t.patterns.find(p => p.id === sel.patternId).name)}</b> · 第 ${sel.bar + 1} 小节 · ${sel.t.clips.filter(c => c.patternId === sel.patternId).length} 处共享` : '选择一个片段，继续编辑。'}</span><div>${sel ? `${button('edit-clip', '画音符', 'pencil', 'soft-btn')}${button('duplicate-clip', '重复引用', 'link', 'quiet')}${button('unlink-clip', '独立副本', 'split', 'quiet')}${button('delete-clip', '移除', 'trash', 'quiet')}` : ''}</div></div></section>
 <details class="workflow-help"><summary>片段如何连接成作品？</summary><p>重复引用会共享音符。创建 A′ 或独立副本后可以分别修改。空白小节保留留白。进入片段后，音色仍作用于本轨所有片段。</p></details>`;
    };
})(globalThis.GridTone ||= {});
