/** Arrangement has one layout and one set of behaviours; clips reference editable patterns. */
(function(G){G.views||={};
 G.views.renderArrange=function(C){
  const {project,S,B,button,ib,icon,esc,miniPattern,presetName,trackIcon}=C,a=G.resolveEditTarget(project,S),w=project.bars*G.UI_METRICS.barWidth;
  return `<section class="arrange-card" data-density="standard"><div class="arrange-scroll" data-scroll="arrange" tabindex="0" aria-label="编排时间轴"><div class="arrange-inner" style="--timeline-width:${w+G.UI_METRICS.trackHead}px;min-width:${w+G.UI_METRICS.trackHead}px"><div class="timeline-ruler"><div class="ruler-label"><span>音轨</span><small>${project.bars} 小节</small></div><div class="ruler-bars" aria-label="时间尺：点击设置播放起点，拖动设置循环">${Array.from({length:project.bars},(_,i)=>`<div style="width:${100/project.bars}%"><span>${i+1}</span></div>`).join('')}<div id="loop-ghost" style="left:${(B.range?.[0]||0)/(project.bars*G.BAR)*100}%;width:${B.range?(B.range[1]-B.range[0])/(project.bars*G.BAR)*100:0}%"></div></div></div>
  ${project.tracks.map((t,i)=>`<div class="arrange-row ${t.mute||(B.soloIds.length&&!B.soloIds.includes(t.id))?'is-muted':''}" data-row-key="${t.id}" data-track="${t.id}" style="--track:${t.color};${G.ui.musicStyle(t.color,t.role|| (t.kind==='drum'?'drums':'melody'))}">${G.ui.TrackHeader({track:t,index:i,selected:a.kind==='track'&&a.trackId===t.id,solo:B.soloIds.includes(t.id),density:'standard',soundName:presetName(t),trackIcon:trackIcon(t)})}<div class="arrange-lane" data-track="${t.id}" data-bars="${project.bars}" style="--bar-width:${100/project.bars}%">${Array.from({length:project.bars},(_,b)=>`<button class="empty-bar" data-action="place-clip" data-track="${t.id}" data-bar="${b}" style="left:${b*100/project.bars}%;width:${100/project.bars}%" aria-label="第 ${b+1} 小节设置编辑落点" title="单击设置粘贴落点；双击创建音乐块"></button>`).join('')}
  ${t.clips.map(c=>{const p=t.patterns.find(p=>p.id===c.patternId),refs=t.clips.filter(x=>x.patternId===p.id).length,selected=a.kind==='clips'&&a.ids.includes(c.id),opened=S.editorOpen&&c.id===S.clipId;return `<div class="song-clip ${selected?'selected':''} ${opened?'opened':''}" data-component="timeline-clip" data-stage="timeline" data-pattern-id="${p.id}" data-clip="${c.id}" data-track="${t.id}" style="left:calc(${c.bar*100/project.bars}% + 4px);width:calc(${p.bars*100/project.bars}% - 8px);--track:${t.color};${G.ui.musicStyle(t.color,t.role|| (t.kind==='drum'?'drums':'melody'))}" tabindex="0" role="button" aria-pressed="${selected}" aria-label="${esc(p.name)}，第 ${c.bar+1} 小节${opened?'，下方已打开':''}" title="${esc(p.name)} · ${refs>1?refs+' 处关联':'独立内容'}"><header><b>${esc(p.name)}</b>${refs>1?icon('link',12):''}<small class="clip-length">${p.bars} 小节</small></header>${miniPattern(p,t,Math.max(80,p.bars*100),28)}</div>`;}).join('')}
  ${S.arrangeCursor?.trackId===t.id?`<div class="arrange-insertion" style="left:${(S.arrangeCursor.tick||0)/(project.bars*G.BAR)*100}%" aria-hidden="true"></div>`:''}</div></div>`).join('')}<div id="arrange-playhead" style="display:none"></div></div></div><footer class="arrange-bottom"><span>点音乐块在下方编辑 · Shift 多选 · Alt 拖动复制</span><small>编辑落点 ${G.editPositionLabel(S.arrangeCursor?.tick||0)}</small></footer></section>`;
 };
})(globalThis.GridTone||={});
