/** Clip-level chord progressions. Preview is disposable; applying commits one ordinary pattern. */
(function(G){'use strict';
 class ComposerUI{
  constructor(context){this.c=context;this.id=G.PROGRESSIONS[0].id;this.group='全部';this.options=null;}
  open(){
   const p=this.c.getProject(),s=this.c.getSession(),t=p.tracks.find(x=>x.id===s.trackId);
   if(t.kind==='drum')throw Error('请先进入旋律音轨，再生成和弦进行。');
   this.options={key:p.key,voicing:'smooth',rhythm:'whole',mode:'new',trackId:t.id,patternId:s.patternId,bar:0,adapt:'original',applySound:false};this.place();this.render();
  }
  place(){const p=this.c.getProject(),t=p.tracks.find(x=>x.id===this.options.trackId),r=G.PROGRESSIONS.find(x=>x.id===this.id);const free=G.firstFreeBar(t,{bars:r.bars},p.bars);this.options.bar=free<0?p.bars:free;}
  generated(){return G.generateProgression(this.id,this.options);}
  candidate(){const g=this.generated();return G.applyTemplate(this.c.getProject(),g.template,this.options);}
  render(){
   const {button,esc,openModal}=this.c,o=this.options,g=this.generated(),r=g.recipe,p=this.c.getProject(),t=p.tracks.find(x=>x.id===o.trackId),pat=t.patterns.find(x=>x.id===o.patternId),refs=t.clips.filter(x=>x.patternId===pat?.id).length;
   const token=G.ui.captureFocus();
   const groups=['全部',...new Set(G.PROGRESSIONS.map(x=>x.group))],recipes=G.PROGRESSIONS.filter(x=>this.group==='全部'||x.group===this.group);
   const select=(field,values,value)=>`<select data-field="composer-${field}">${values.map(([id,label])=>`<option value="${id}" ${String(id)===String(value)?'selected':''}>${esc(label)}</option>`).join('')}</select>`;
   const notes=g.template.notes,lo=Math.min(...notes.map(n=>n.pitch))-2,hi=Math.max(...notes.map(n=>n.pitch))+2;
   const drawing=`<svg viewBox="0 0 480 90" role="img" aria-label="候选和弦音符排列" class="chord-drawing"><g stroke="var(--line)">${Array.from({length:r.bars+1},(_,b)=>`<path d="M${b*480/r.bars} 0v90"/>`).join('')}</g>${notes.map(n=>`<rect x="${n.start/(r.bars*G.BAR)*480}" y="${(hi-n.pitch)/(hi-lo)*76+3}" width="${Math.max(2,n.duration/(r.bars*G.BAR)*480-1)}" height="4.5" rx="2" fill="currentColor"/>`).join('')}</svg>`;
   openModal('和弦进行',`<div class="composer-intro"><p>选一种走向，听一听，再生成可以逐音修改的伴奏。</p><span class="pill">${G.PROGRESSIONS.length} 组进行 · 4 种弹奏</span></div><div class="composer-layout"><section class="progression-library"><nav class="catalog-role-tabs" aria-label="和弦进行分组">${groups.map(x=>button('composer-group',x,'',this.group===x?'active':'quiet',`data-group="${x}" aria-pressed="${this.group===x}"`)).join('')}</nav><div class="progression-list">${recipes.map(x=>`<button class="progression-card ${x.id===this.id?'selected':''}" data-action="composer-select" data-id="${x.id}" aria-pressed="${x.id===this.id}"><span><strong>${esc(x.name)}</strong><small>${x.scale==='minor'?'小调':'大调'} · ${x.bars} 小节</small></span><b>${esc(x.roman)}</b></button>`).join('')}</div></section><section class="progression-detail"><div class="chord-hero"><span class="eyebrow">${esc(r.group)}</span><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><div class="chord-pills">${g.chords.map((x,i)=>`<span><small>${i+1}</small>${esc(x)}</span>`).join('')}</div>${drawing}</div><div class="form-grid"><label class="form-label">主音 · ${r.scale==='minor'?'小调':'大调'}${select('key',G.KEYS.map((k,i)=>[i,k]),o.key)}</label><label class="form-label">音符排列${select('voicing',[['smooth','就近连接'],['root','原位排列'],['open','开放排列']],o.voicing)}</label><label class="form-label">弹奏方式${select('rhythm',[['whole','整小节长音'],['pulse','四拍轻弹'],['arp','八分音符分解'],['strum','逐音铺开']],o.rhythm)}</label><label class="form-label">放在哪里${select('mode',[['new','本轨新增独立片段'],['new-track','新增一条和弦音轨'],['replace','替换当前片段内容']],o.mode)}</label></div>${o.mode!=='replace'?`<label class="form-label compact-field">从第几小节开始<input data-field="composer-bar" type="number" min="1" max="${257-r.bars}" step="1" value="${o.bar+1}"></label>`:''}${o.mode!=='new-track'?`<label class="catalog-check"><input type="checkbox" data-field="composer-sound" ${o.applySound?'checked':''}> 使用建议的电钢琴音色 · 影响本轨全部片段</label>`:'<p class="field-note">新音轨使用晶片电钢琴，可以随时更换。</p>'}<p class="field-note">${o.mode==='replace'?`当前片段 ${pat.bars} 小节 · ${refs} 处共享引用同步变化。${pat.bars<r.bars?'长度不足，请改用新增片段。':'替换可整体撤销。'}`:`生成 ${r.bars} 小节、${notes.length} 个普通音符；原片段保持不变。`}</p><p class="resource-feedback" id="composer-feedback" role="status"></p><div class="composer-actions">${button('composer-preview','试听候选','headphones','soft-btn')}${button('stop','停止','stop','quiet')}${button('composer-apply',`生成 ${r.bars} 小节`,'check','dark-btn',(o.mode==='replace'&&pat.bars<r.bars)?'disabled':'')}</div></section></div>`,'片段编辑 / 创作辅助');
   if(token?.el?.closest?.('.modal'))G.ui.restoreFocus(token);
  }
  feedback(message){const el=document.querySelector('#composer-feedback');if(el)el.textContent=message;this.c.toast(message);}
  async preview(){try{const result=this.candidate();const started=await this.c.playback.audition(result.project,{kind:'pattern',trackId:result.trackId,patternId:result.patternId,ignoreMute:true},'和弦预听 · '+this.generated().recipe.name);if(started)this.feedback('正在试听候选。当前作品保持不变。');}catch(e){this.feedback(e.message);}}
  apply(){try{const result=this.candidate();this.c.closeModal();this.c.commit(result);this.c.toast('和弦进行已展开为普通音符；可逐音修改或一次撤销。');}catch(e){this.feedback(e.message);}}
  handleField(el){if(!el.dataset.field?.startsWith('composer-'))return false;this.c.playback.endAudition();const f=el.dataset.field.slice(9);if(f==='key')this.options.key=Number(el.value);else if(f==='bar')this.options.bar=Number(el.value)-1;else if(f==='sound')this.options.applySound=el.checked;else if(['mode','voicing','rhythm'].includes(f))this.options[f]=el.value;this.render();return true;}
  handleAction(a,el){if(a==='composer'){this.open();return true;}if(!a.startsWith('composer-'))return false;this.c.playback.endAudition();if(a==='composer-group'){this.group=el.dataset.group;this.render();}else if(a==='composer-select'){this.id=el.dataset.id;this.place();this.render();}else if(a==='composer-preview')void this.preview();else if(a==='composer-apply')this.apply();return true;}
 }
 G.ComposerUI=ComposerUI;
})(globalThis.GridTone ||= {});
