/** One disposable candidate session for recipes, notes, ensemble and arrangement. */
(function(G){'use strict';
 const LABELS={generate:'生成一句',rhythm:'保留节奏换音高',anchors:'保留关键音改连接',ending:'只改结尾',answer:'回答句',drums:'鼓型变化',bass:'生成贝斯',accompaniment:'生成伴奏',recipe:'配套模板',arrange:'发展编排',mix:'建议混音',ensemble:'鼓 / 贝斯 / 伴奏一起变化'};
 class CreationUI{
  constructor(context){this.c=context;this.session=null;}
  open(mode){
   this.c.closeModal?.();
   const p=this.c.getProject(),s=this.c.getSession(),t=p.tracks.find(t=>t.id===s.trackId)||p.tracks[0],c=t.clips.find(c=>c.id===s.clipId)||t.clips.find(c=>c.patternId===s.patternId),pat=t.patterns.find(x=>x.id===c?.patternId)||t.patterns.find(x=>x.id===s.patternId)||t.patterns[0];
   mode??=t.kind==='drum'?'drums':t.role==='bass'?'bass':'generate';
   const sources=p.tracks.filter(t=>t.patterns.some(p=>p.harmony));
   this.session={base:G.clone(p),token:G.contentHash(p),target:{trackId:t.id,clipId:c?.id},patternId:pat.id,mode,sourceTrackId:sources.filter(v=>v.id!==t.id).length===1?sources.find(v=>v.id!==t.id).id:'',referenceTrackId:'',seed:42,low:t.role==='bass'?36:60,high:t.role==='bass'?55:84,start:0,end:Math.min(pat.bars,8)*G.BAR,bar:mode==='arrange'?p.bars:0,bars:mode==='ensemble'?pat.bars:8,sourceBar:c?.bar||0,strategy:mode==='arrange'?'variation':mode==='bass'?'align':'support',rhythmTemplateId:'',color:'none',intent:'loop',drumRole:'closedHat',drumStyle:'straight',velocityStyle:'balanced',textureStyle:'sustain',density:'normal',recipeId:G.RECIPES[0].id,tempo:false,retention:G.clone(pat.retention||{notes:[],ranges:[]}),selected:[...s.selected],candidates:[],chosen:0,message:''};this.render();
  }
  current(){const x=this.session,t=x.base.tracks.find(t=>t.id===x.target.trackId),p=t.patterns.find(p=>p.id===x.patternId);return {x,t,p};}
  fresh(){const x=this.session;if(!x||x.token!==G.contentHash(x.base))throw Error('原稿或参考内容已变化，请重新生成。');if(this.c.getProject().id!==x.base.id)throw Error('作品已切换，请重新生成。');if(x.flow?.state==='ready')x.flow.validate(this.c.getProject(),x.candidates[x.chosen]);}
  close(){this.session?.flow?.cancel();this.session=null;this.c.playback.endAudition();this.c.closeCreation?.();}
  refresh(){if(!this.session)return;const x=this.session;if(this.c.getProject().id!==x.base.id){this.close();return;}try{if(x.flow?.state==='ready')this.fresh();}catch(e){x.flow.invalidate(e.message);x.candidates=[];x.message=e.message;this.c.playback.endAudition();}const s=this.c.getSession();if(s.trackId===x.target.trackId&&s.clipId===x.target.clipId){x.selected=[...s.selected];const current=this.c.getProject(),t=current.tracks.find(t=>t.id===x.target.trackId);if(x.flow?.state!=='ready'&&t?.patterns.some(p=>p.id===x.patternId)){x.base=G.clone(current);x.token=G.contentHash(x.base);}}this.render();}
  render(){
   const {x,t,p}=this.current(),{button,esc}=this.c,select=(name,items,value)=>`<select data-field="creation-${name}" aria-label="${name}">${items.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`,number=(name,label,value,min,max)=>G.ui.Field({field:'creation-'+name,label,value,type:'number',min,max});
   const op=G.CREATION_OPERATIONS[x.mode],sources=x.base.tracks.filter(t=>t.patterns.some(p=>p.harmony)),melody=['generate','rhythm','anchors','ending','answer'].includes(x.mode),instance=op.scope==='instance';
   const choices=Object.entries(LABELS).filter(([id])=>id===x.mode||instance&&G.CREATION_OPERATIONS[id].scope==='instance'&&(t.kind==='drum'?id==='drums':t.role==='bass'?id==='bass':['texture','chords'].includes(t.role)?id==='accompaniment':['generate','rhythm','anchors','ending','answer'].includes(id)));
   let settings='',advanced='';
   if(instance&&t.kind!=='drum')settings+=button('harmony-editor',p.harmony?'复核本片段和弦':'指定本片段和弦','piano','quiet');
   if(op.requiredInputs.includes('harmony'))settings+=`<label>参考和弦${select('sourceTrackId',[['','选择明确的和弦来源'],...sources.filter(v=>v.id!==t.id).map(v=>[v.id,v.name])],x.sourceTrackId)}</label>`;
   if(instance&&x.mode!=='drums')settings+=`<div class="form-grid"><label>最低音${select('low',Array.from({length:128},(_,n)=>[n,G.noteName(n)]),x.low)}</label><label>最高音${select('high',Array.from({length:128},(_,n)=>[n,G.noteName(n)]),x.high)}</label></div>`;
   if(op.parameters.includes('density')&&(!melody||!x.rhythmTemplateId))settings+=`<label>节奏密度${select('density',[['sparse','稀疏'],['normal','适中'],['dense','密集']],x.density)}</label>`;
   if(x.mode==='recipe')settings+=`<label>配套风格${select('recipeId',G.RECIPES.map(r=>[r.id,r.name]),x.recipeId)}</label><p>${esc(G.RECIPES.find(r=>r.id===x.recipeId).description)}</p>${number('bar','插入第几小节',x.bar+1,1,256)}${G.ui.Toggle({field:'creation-tempo',label:'采用配方速度与 Swing（全曲）',checked:x.tempo})}`;
   if(x.mode==='arrange')settings+=`<div class="form-grid">${number('bar','放到第几小节',x.bar+1,1,256)}${number('sourceBar','取用材料的起始小节',x.sourceBar+1,1,256)}</div><label>发展长度${select('bars',[[8,'8 小节'],[16,'16 小节']],x.bars)}</label><label>组织方式${select('strategy',[['variation','主题—变化—结尾'],['entry','先伴奏，后旋律'],['repeat','共享重复']],x.strategy)}</label><p>已选实例优先；保留材料之间的相对位置。空间不足时整次拒绝。</p>`;
   if(x.mode==='ensemble')settings+=`${number('sourceBar','从第几小节开始',x.sourceBar+1,1,256)}<label>变化范围${select('bars',G.PATTERN_BARS.map(n=>[n,n+' 小节']),x.bars)}</label><p>按鼓→贝斯→伴奏的顺序计算，各声部使用自己的默认音域。</p>`;
   if(x.mode==='mix')settings+=`<p>为全曲已指定角色的音轨建议音量和声像。音符、音色与临时独奏保持原样。</p>`;
   if(['bass','accompaniment'].includes(x.mode))settings+=`<label>配合声部${select('referenceTrackId',[['','仅参考和声'],...x.base.tracks.filter(v=>v.id!==t.id&&(x.mode==='bass'?v.kind==='drum':v.role==='melody')).map(v=>[v.id,v.name])],x.referenceTrackId)}</label><label>配合方式${select('strategy',x.mode==='bass'?[['align','对齐底鼓'],['answer','呼应底鼓']]:[['support','承托 / 避让'],['answer','空白处呼应'],['together','同拍加强']],x.strategy)}</label>`;
   if(x.mode==='accompaniment')settings+=`<label>弹奏方式${select('textureStyle',[['sustain','长音铺底'],['pulse','轻弹脉搏'],['arp','分解流动']],x.textureStyle)}</label>`;
   if(x.mode==='drums')settings+=`<label>基本律动${select('drumStyle',[['straight','直拍'],['half','半拍'],['four','四拍底鼓']],x.drumStyle)}</label><label>力度倾向${select('velocityStyle',[['soft','轻柔'],['balanced','均衡'],['punch','有力']],x.velocityStyle)}</label>`;
   if(x.mode==='drums')settings+=`<label>变化鼓件${select('drumRole',[...G.drumMap(x.base,t)].map(([r])=>[r,({kick:'底鼓',snare:'军鼓',closedHat:'闭镲',openHat:'开镲',clap:'拍手',tom:'通鼓',crash:'吊镲',rim:'边击'})[r]||r]),x.drumRole)}</label>${G.ui.Toggle({field:'creation-lastBeat',label:'只改最后一拍',checked:x.lastBeat})}`;
   if(instance)advanced+=`<div class="form-grid">${number('start','起点（第 0 拍起）',x.start/G.PPQ,0,p.bars*4)}${number('end','终点（拍）',x.end/G.PPQ,1,p.bars*4)}</div>`;
   if(op.parameters.includes('rhythmTemplateId'))advanced+=`<label>节奏骨架${select('rhythmTemplateId',[['','按密度生成'],...G.RECIPES.map(r=>['rhythm.'+r.id,r.name+' · 节奏骨架']),...G.catalogTemplates().filter(v=>v.type==='pattern'&&v.kind==='melodic').map(v=>[v.id,v.name])],x.rhythmTemplateId)}</label>`;if(op.parameters.includes('intent'))advanced+=`<label>句尾意图${select('intent',[['loop','继续循环'],['ending','收束结束']],x.intent)}</label>`;if(op.parameters.includes('color'))advanced+=`<label>连接色彩${select('color',[['none','和弦内连接'],['diatonic','调内经过 / 邻接'],['chromatic','半音趋近']],x.color)}</label>`;
   if(op.random)advanced+=number('seed','变化种子',x.seed,0,4294967295);
   const selected=this.c.getSession(),candidate=x.candidates[x.chosen],wrongTarget=instance&&(selected.trackId!==x.target.trackId||selected.clipId!==x.target.clipId);
   const feedback=candidate&&wrongTarget?'候选固定在原片段，返回原目标后可以应用。':x.message;
   let insights='';if(x.selected.length&&x.sourceTrackId){try{const h=G.resolveHarmony(x.base,{...x.target,sourceTrackId:x.sourceTrackId,start:x.start,end:x.end});insights=p.notes.filter(n=>x.selected.includes(n.id)).slice(0,4).map(n=>{const a=G.explainNote(n,h,h.targetTranspose,p.notes);return `<p><b>${G.noteName(n.pitch)} · ${esc(a.role)}</b><br>${esc(a.reason)}</p>`;}).join('');}catch(e){insights=`<p>${esc(e.message)}</p>`;}}
   const unsupported=melody&&![4,8,16].includes(p.bars),moreOpen=document.querySelector('#creation-options')?.open;
   const keep=instance?`<details class="retention-controls" ${document.querySelector('.retention-controls')?.open?'open':''}><summary>生成时保留 · ${x.retention.notes.length} 音 / ${x.retention.ranges.length} 范围</summary><p>当前选中 ${x.selected.length} 个音符。保留约束作用于生成，手动编辑仍可用。</p><div class="menu-grid">${[['pitch','保留音高'],['rhythm','保留节奏'],['all','全部保留'],['clear','解除音符保留'],['range','保留当前范围与休止'],['clear-ranges','解除范围保留']].map(([v,l])=>button('creation-keep',l,'lock','quiet',`data-keep="${v}"`)).join('')}</div>${button('creation-save-keeps','保存保留设置','save','quiet')}</details>`:'';
   const bar=candidate?G.ui.CandidateBar({count:x.candidates.length,chosen:x.chosen,drawing:(()=>{if(x.mode==='mix')return '<div class="mix-candidate-changes">'+candidate.project.tracks.map(t=>{const before=x.base.tracks.find(v=>v.id===t.id);return before&&(before.volume!==t.volume||before.pan!==t.pan)?'<p><b>'+esc(t.name)+'</b><br>音量 '+Math.round(before.volume*100)+'% → '+Math.round(t.volume*100)+'% · 声像 '+Math.round(before.pan*100)+' → '+Math.round(t.pan*100)+'</p>':'';}).join('')+'</div>';const tr=candidate.project.tracks.find(t=>t.id===candidate.trackId),pat=tr?.patterns.find(p=>p.id===candidate.patternId);return pat?G.ui.miniPattern(pat,tr,360,64):'';})(),actions:button('creation-preview','连伴奏试听','headphones','soft-btn')+button('creation-preview-solo','单独听','play','quiet')+button('stop','停止','stop','quiet')+button('creation-apply','应用这一版','check','dark-btn',wrongTarget?'disabled':'')}):'';
   (this.c.openCreation||this.c.openModal)(LABELS[x.mode],`<div class="creation-target"><strong>${instance?esc(t.name)+' · '+esc(p.name):'整首作品'}</strong><small>${instance?`${p.bars} 小节 · 当前实例独立应用`:'预听后整体应用，一次撤销'}</small></div>${choices.length>1?`<label>这次怎么变化${select('mode',choices,x.mode)}</label>`:''}${settings}${unsupported?`<p class="creation-limitation">当前是 ${p.bars} 小节。可以继续手绘与套素材，或明确新建 4 小节后生成。</p>${button('creation-new-four','新建 4 小节目标','plus','soft-btn')}`:''}${p.bars===16&&melody?'<p>16 小节乐句：在下方“范围与细节”中选择其中 4 / 8 小节。</p>':''}<div class="creation-generate-row">${button('creation-generate',candidate?(op.random?'再来一组':'重新计算'):'生成候选','spark','dark-btn',unsupported?'disabled':'')}</div><p role="status" id="creation-feedback">${esc(feedback)}</p>${advanced?`<details id="creation-options" ${moreOpen?'open':''}><summary>范围与细节</summary>${advanced}</details>`:''}${keep}${insights}${bar}`, '候选固定目标；试听保留原稿。');
  }
  generate(){
   const x=this.session;if(!x||this.c.getProject().id!==x.base.id)throw Error('作品已切换，请重新选择目标。');x.base=G.clone(this.c.getProject());const t=x.base.tracks.find(t=>t.id===x.target.trackId),clip=t?.clips.find(c=>c.id===x.target.clipId);if(!t)throw Error('目标轨道已删除。');x.patternId=clip?.patternId||x.patternId;const p=t.patterns.find(p=>p.id===x.patternId);if(!p)throw Error('目标乐句已删除。');x.retention.notes=x.retention.notes.filter(n=>p.notes.some(v=>v.id===n.id));x.token=G.contentHash(x.base);x.candidates=[];x.message='';const operation=G.CREATION_OPERATIONS[x.mode];if(operation.scope==='instance'&&!x.target.clipId)throw Error('请先把当前乐句放入编排，再生成。');x.flow=new G.CandidateSession(x.base,x.mode,operation.scope==='instance'?x.target:{},Object.fromEntries(Object.entries(x).filter(([key,value])=>!['token','patternId','message'].includes(key)&&['string','number','boolean'].includes(typeof value))));x.flow.begin();
   if(x.mode==='recipe')x.candidates=[G.applyRecipe(x.base,x.recipeId,{bar:x.bar,key:x.base.key,seed:x.seed,tempo:x.tempo})];
   else if(x.mode==='arrange'||x.mode==='mix'){const project=x.mode==='arrange'?G.arrangeSections(x.base,{bar:x.bar,bars:x.bars,sourceBar:x.sourceBar,style:x.strategy,clipIds:this.c.getSession().clipIds}):G.suggestedMix(x.base);const oldIds=new Set(x.base.tracks.flatMap(t=>t.clips.map(c=>c.id))),added=project.tracks.flatMap(tr=>tr.clips.filter(c=>!oldIds.has(c.id)).map(c=>({trackId:tr.id,patternId:c.patternId,clipId:c.id})));x.candidates=[{project,...(added[0]||{trackId:t.id,patternId:p.id,clipId:x.target.clipId}),trackIds:x.mode==='arrange'?[...new Set(added.map(c=>c.trackId))]:project.tracks.map(t=>t.id),range:x.mode==='arrange'?[x.bar*G.BAR,(x.bar+x.bars)*G.BAR]:[0,project.bars*G.BAR]}];}
   else{
    const base=G.clone(x.base),pat=base.tracks.find(v=>v.id===t.id).patterns.find(v=>v.id===p.id);pat.retention=G.clone(x.retention);
    let candidates;
    if(x.mode==='ensemble'){
     x.candidates=[G.generateEnsembleGroup(base,{...x,bars:x.bars,melodyTrackId:t.role==='melody'?t.id:undefined},x.seed)];x.flow.ready(x.candidates);x.candidates=x.flow.candidates;x.chosen=0;this.render();return;
    }
    if(['drums','bass','accompaniment'].includes(x.mode))candidates=[G.generateEnsemble(base,x.target,x,x.seed)];
    else{const harmony=G.resolveHarmony(base,{...x.target,sourceTrackId:x.sourceTrackId,start:x.start,end:x.end});const result=G.generateMelody({harmony,notes:p.notes,retention:x.retention,key:base.key,scale:base.scale},{...x,rhythmTemplate:G.resolveRhythmTemplate(x.rhythmTemplateId)},x.seed);candidates=result.candidates;x.message=result.message;}
    x.candidates=candidates.map(c=>G.applyGenerated(base,x.target,c));
   }
   x.flow.ready(x.candidates);x.candidates=x.flow.candidates;x.chosen=0;if(!x.message)x.message='候选已准备好，可以先听再应用。';this.render();requestAnimationFrame(()=>document.querySelector('.candidate-bar')?.scrollIntoView({block:'nearest'}));
  }
  keep(kind){const {x,p}=this.current();if(kind==='range'){if(x.end<=x.start)throw Error('保留范围无效。');x.retention.ranges.push({start:x.start,end:x.end});}else if(kind==='clear-ranges')x.retention.ranges=[];else{if(!x.selected.length)throw Error('请先在画板选择要保留的音符。');x.retention.notes=x.retention.notes.filter(n=>!x.selected.includes(n.id));if(kind!=='clear')for(const id of x.selected)if(p.notes.some(n=>n.id===id))x.retention.notes.push({id,[kind]:true});}x.candidates=[];x.flow?.invalidate('保留设置已变化，请重新生成。');this.c.playback.endAudition();this.render();}
  harmonyEditor(){const {x,p}=this.current();this.harmony=G.clone(p.harmony||{version:1,events:[{start:0,duration:p.bars*G.BAR,rootPitchClass:x.base.key,quality:'major'}],confirmedMusicHash:'manual'});this.renderHarmony();}
  renderHarmony(){const {button,esc,openModal}=this.c;openModal('指定 / 复核参考和弦',`<p>明确这里的和弦意图，供其他声部生成时参考。现有音符保留。起点以片段开始为第 0 拍。</p><div class="harmony-events">${this.harmony.events.map((e,i)=>`<div class="form-grid"><label>起点（拍）<input type="number" data-field="harmony" data-harmony="start" data-index="${i}" value="${e.start/G.PPQ}" min="0" step="0.5"></label><label>时长（拍）<input type="number" data-harmony="duration" data-index="${i}" value="${e.duration/G.PPQ}" min="0.5" step="0.5"></label><label>根音<select data-harmony="rootPitchClass" data-index="${i}">${G.KEYS.map((k,n)=>`<option value="${n}" ${e.rootPitchClass===n?'selected':''}>${k}</option>`).join('')}</select></label><label>类型<select data-harmony="quality" data-index="${i}">${Object.keys(G.CHORD_SHAPES).map(q=>`<option ${q===e.quality?'selected':''}>${esc(q)}</option>`).join('')}</select></label>${button('harmony-remove','移除此和弦','trash','quiet',`data-index="${i}"`)}</div>`).join('')}</div><div class="modal-actions">${button('harmony-add','增加和弦','plus','soft-btn')}${button('harmony-confirm','确认参考和弦','check','dark-btn')}${button('close-modal','取消','','quiet')}</div>`);}
  handleField(el){if(el.dataset.harmony){const e=this.harmony.events[Number(el.dataset.index)],key=el.dataset.harmony;e[key]=key==='quality'?el.value:Number(el.value)*(['start','duration'].includes(key)?G.PPQ:1);return true;}if(!el.dataset.field?.startsWith('creation-'))return false;const key=el.dataset.field.slice(9),x=this.session;this.c.playback.endAudition();x[key]=el.type==='checkbox'?el.checked:el.type==='number'||['bars','low','high'].includes(key)?Number(el.value):el.value;if(['bar','sourceBar'].includes(key))x[key]--;if(['start','end'].includes(key))x[key]*=G.PPQ;x.candidates=[];x.message='';x.flow?.invalidate();x.message='设置已变化，请重新生成。';if(key==='mode'){if(x.mode==='arrange'){x.bar=x.base.bars;x.strategy='variation';}if(x.mode==='bass'){x.strategy='align';x.low=36;x.high=55;}}this.render();return true;}
  handleAction(action,el){
   if(action==='creation'||action==='recipes'){this.open(action==='recipes'?'recipe':el?.dataset.mode);return true;}if(action==='creation-close'){this.close();return true;}
   if(!action.startsWith('creation-')&&!action.startsWith('harmony-'))return false;
   try{
    if(action==='creation-generate'){if(this.session.candidates.length&&G.CREATION_OPERATIONS[this.session.mode].random)this.session.seed++;this.generate();}if(action==='creation-new-four'){const {x,t}=this.current(),doc=G.clone(this.c.getProject()),tr=doc.tracks.find(v=>v.id===t.id),pat=G.newPattern('新旋律',4),bar=doc.bars;doc.bars+=4;tr.patterns.push(pat);const clip={id:G.uid('c'),patternId:pat.id,bar};tr.clips.push(clip);G.validateProject(doc);const result=this.c.commit({project:doc,trackId:tr.id,patternId:pat.id,clipId:clip.id});if(result?.ok!==false)this.open(x.mode);}
    if(action==='creation-choose'){this.c.playback.endAudition();this.session.chosen=Number(el.dataset.index);this.render();}
    if(action==='creation-keep')this.keep(el.dataset.keep);
    if(action==='creation-save-keeps'){this.fresh();const {x,p,t}=this.current(),project=G.clone(x.base);project.tracks.find(v=>v.id===t.id).patterns.find(v=>v.id===p.id).retention=G.clone(x.retention);G.validateProject(project);this.c.closeModal();this.c.commit({project:G.applyCandidatePatch(this.c.getProject(),G.candidatePatch(x.base,project)),...x.target,patternId:p.id});this.close();}
    if(action==='creation-preview'||action==='creation-preview-solo'){
     this.fresh();const {x,p}=this.current(),r=x.flow?.materialize(this.c.getProject(),x.chosen);if(!r)throw Error('请先生成候选。');const range=r.outputRange;
     const scope={kind:'song',range,soloIds:action.endsWith('-solo')?r.affectedTrackIds:[]};this.c.playback.audition(r.project,scope,'候选预听 · '+LABELS[x.mode]);
    }
    if(action==='creation-apply'){this.fresh();const x=this.session,s=this.c.getSession();if(G.CREATION_OPERATIONS[x.mode].scope==='instance'&&(s.trackId!==x.target.trackId||s.clipId!==x.target.clipId))throw Error('请返回候选的原目标片段，再应用这一版。');const r=x.flow?.materialize(this.c.getProject(),x.chosen);if(!r)throw Error('请先生成候选。');x.flow.state='applying';const result=this.c.commit(r);if(result?.ok===false){x.flow.fail(Error(result.error.message));x.message=result.error.message;this.render();}else this.close();}
    if(action==='harmony-editor')this.harmonyEditor();
    if(action==='harmony-add'){const last=this.harmony.events.at(-1);this.harmony.events.push({start:last?last.start+last.duration:0,duration:G.BAR,rootPitchClass:0,quality:'major'});this.renderHarmony();}
    if(action==='harmony-remove'){this.harmony.events.splice(Number(el.dataset.index),1);this.renderHarmony();}
    if(action==='harmony-confirm'){this.fresh();const {x,p,t}=this.current(),project=G.clone(x.base),pat=project.tracks.find(v=>v.id===t.id).patterns.find(v=>v.id===p.id);G.confirmHarmony(pat,this.harmony);G.validateProject(project);this.c.closeModal();this.c.commit({project:G.applyCandidatePatch(this.c.getProject(),G.candidatePatch(x.base,project)),...x.target,patternId:p.id});this.close();}
   }catch(e){if(action==='creation-generate'){this.session.flow?.fail(e);this.session.candidates=[];this.session.message=e.message;this.render();}this.c.toast(e.message);const feedback=document.querySelector('#creation-feedback');if(feedback)feedback.textContent=e.message;}
   return true;
  }
 }
 G.CreationUI=CreationUI;
})(globalThis.GridTone ||= {});
