(function(G){G.views ||= {};
 G.views.renderEditor=function(C){
  const {S,project,track,pattern,button,ib,esc,renderSound,renderPipeline,presetName,miniPattern}=C,t=track(),p=pattern(),refs=t.clips.filter(c=>c.patternId===p.id).length;
  const tabs=`<div class="dock-tabs">${[['notes','音符'],['sound','本轨音色'],['pipeline','演奏处理']].map(([id,label])=>button('editor-tab',label,'',S.editorTab===id?'active':'quiet',`data-tab="${id}"`)).join('')}</div>`;
  const title=`<header class="dock-header"><div class="dock-identity"><span class="track-dot" style="background:${t.color}"></span><strong>${esc(t.name)}</strong><span class="dock-pattern">${esc(p.name)} · ${p.bars} 小节${refs>1?' · '+refs+' 处共享':''}</span></div>${tabs}<div class="dock-actions">${ib('expand-editor',S.editorExpanded?'还原编辑器':'放大编辑器','grid')}${ib('close-editor','收起编辑器','down')}</div></header>`;
  if(S.editorTab==='sound')return title+`<div class="dock-panel">${renderSound()}</div>`;
  if(S.editorTab==='pipeline')return title+`<div class="dock-panel">${renderPipeline()}</div>`;
  return title+`<div class="studio-edit-tools"><div class="tool-group">${[['draw','画笔 · B','pencil'],...(t.kind!=='drum'?[['chord','和弦画笔','notes']]:[]),['select','选择 · V','select'],['erase','橡皮 · E','eraser'],['pan','浏览 · H','hand']].map(([id,label,ic])=>button('tool','',ic,S.tool===id?'active':'quiet',`data-tool="${id}" title="${label}" aria-label="${label}"`)).join('')}</div>${S.tool==='chord'?`<select data-field="chord" aria-label="和弦类型">${Object.keys(G.CHORDS).map(k=>`<option value="${k}" ${S.chord===k?'selected':''}>${({major:'大三',minor:'小三',maj7:'大七',min7:'小七',dom7:'属七',sus2:'挂二',sus4:'挂四',fifth:'五度'})[k]}</option>`).join('')}</select>`:''}<label>网格<select data-field="snap" aria-label="吸附精度">${[[480,'1/8'],[240,'1/16'],[120,'1/32'],[320,'1/8 三连音'],[160,'1/16 三连音'],[80,'1/32 三连音'],[0,'自由 · 不吸附']].map(([v,l])=>`<option value="${v}" ${S.snap===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="compact-check"><input type="checkbox" data-field="continuous" ${S.continuous?'checked':''}>连续小节</label>${!S.continuous?`<select data-field="editor-page" aria-label="当前小节">${Array.from({length:p.bars},(_,i)=>`<option value="${i}" ${S.page===i?'selected':''}>第 ${i+1} 小节</option>`).join('')}</select>`:''}<div class="editor-tool-spacer"></div>${button('fit-notes','适配','grid','quiet')}${ib('zoom-out','缩小时间轴 · Ctrl/⌘ 滚轮','minus')}${ib('zoom-in','放大时间轴 · Ctrl/⌘ 滚轮','plus')}${button('note-inspector','精细编辑','','quiet')}${button('editor-more','更多工具','dots','quiet')}</div><div class="grid-scroll ${S.tool==='pan'?'pan-mode':''}" data-scroll="grid"><div class="gridframe" id="gridframe" tabindex="0" role="application" aria-label="音符编辑画布"><div id="grid-inner"></div></div></div><div class="dock-footer"><span>${S.selected.length?'已选 '+S.selected.length+' 音 · 力度仅作用于所选':'点空白写音符 · 拖边缘改长度 · Alt + 方向键微调'}</span><div>${button('listen-pattern','试听片段','headphones','quiet')}${button('copy-notes','复制','copy','quiet')}${button('paste-notes','粘贴','','quiet')}${button('delete-notes','删除','trash','quiet')}</div></div>`;
 };
})(globalThis.GridTone ||= {});
