/** View renderer. Receives the current document and session; never mutates either. */
(function (G) {
    'use strict';
    G.views ||= {};
    G.views.renderEditor = function (C) {
        const { project, S, B, track, pattern, button, ib, icon, esc, miniPattern, slider, presetName, trackIcon, soundCards, waveIllustration, renderSound, renderPipeline } = C;
        const { KEYS, PRESETS, clamp, noteName, presetById, canPlace } = G;
        const t = track(), p = pattern(), clip = t.clips.find(c => c.id === S.clipId), refs = t.clips.filter(c => c.patternId === p.id).length;
        const top = `<div class="editor-context"><div class="editor-breadcrumb">${button('view', '返回编排', 'arrange', 'quiet', 'data-view="arrange"')}<span>/</span><select data-field="editor-track" aria-label="编辑音轨">${project.tracks.map(x => `<option value="${x.id}" ${x.id === t.id ? 'selected' : ''}>${esc(x.name)}</option>`).join('')}</select><small>${clip ? `第 ${clip.bar + 1} 小节实例` : '尚未编排'}</small></div><div class="heading-actions">${button('listen-pattern', `试听本片段 · ${p.bars} 小节`, 'headphones', 'dark-btn')}${button('listen-bar', '当前小节', 'play', 'quiet')}</div></div>
 <div class="editor-subbar"><nav class="editor-subtabs" aria-label="片段编辑">${[['notes', t.kind === 'drum' ? '鼓点' : '画音符', 'pencil'], ['sound', '本轨音色', 'wave'], ['pipeline', '演奏处理', 'spark']].map(([id, name, ic]) => button('editor-tab', name, ic, S.editorTab === id ? 'active' : '', `data-tab="${id}" aria-pressed="${S.editorTab===id}"`)).join('')}</nav>
 <div class="shared-context"><span title="${refs > 1 ? `此片段被使用 ${refs} 次，修改同步到这 ${refs} 处。` : '独立片段，可以自由修改。'}">${refs > 1 ? `${refs} 次引用 · 共享修改` : '独立片段'}</span><span title="修改音色影响本轨全部片段">本轨音色：${esc(presetName(t))} · 整轨生效</span></div></div>`;
        if (S.editorTab === 'sound')
            return top + renderSound();
        if (S.editorTab === 'pipeline')
            return top + renderPipeline();
        const v = G.viewportFor(S, t);
        const groups = t.kind === 'drum' ? [['notes', '鼓点编辑']] : [['view', '视图'], ['aids', '创作辅助'], ['notes', '音符编辑']];
        const viewControls = t.kind === 'drum' ? `${button('catalog', '鼓点 / 鼓组', 'folder', 'quiet','data-role=drums')}` : `${button('fit-notes', '适配音符', 'grid', 'quiet')}${button('octave-down', '向低音浏览', 'minus', 'quiet')}${button('octave-up', '向高音浏览', 'plus', 'quiet')}<label>音域<select data-field="viewport-span" aria-label="可见音域">${[...new Set([12, 24, 36, 48, 72, 127, v.span])].sort((a, b) => a - b).map(n => `<option value="${n}" ${v.span === n ? 'selected' : ''}>${n === 127 ? '全部' : n + ' 半音'}</option>`).join('')}</select></label>${button('scale-lock', S.showScale ? '简化显示：开' : '简化显示：关', 'grid', 'quiet', `aria-pressed="${S.showScale}"`)}<small>拖音高尺浏览 · 点按试听</small>`;
        const aids = `<label>参考调性<select data-field="key" aria-label="参考主音">${KEYS.map((x, i) => `<option value="${i}" ${project.key === i ? 'selected' : ''}>${x}</option>`).join('')}</select><select data-field="scale" aria-label="参考音阶">${Object.entries({ major: '大调', minor: '小调', pentatonic: '五声音阶', chromatic: '半音阶' }).map(([k, l]) => `<option value="${k}" ${project.scale === k ? 'selected' : ''}>${l}</option>`).join('')}</select></label><label><input type="checkbox" data-field="input-snap" ${S.inputSnap ? 'checked' : ''}> 新音符吸附调内</label><small>参考变化保留已有音符；和弦仍生成独立音符。</small>${button('groove', `Swing ${Math.round(project.swing * 100)}%`, 'wave', 'quiet')}${button('composer', '和弦进行', 'chord', 'soft-btn')}${button('catalog', '旋律 / 贝斯模板', 'folder', 'quiet', 'data-role=melody')}`;
        const transforms = `<strong class="edit-scope">${S.selected.length ? '选中 ' + S.selected.length + ' 音' : '本片段全部音符'}</strong>${t.kind === 'drum' ? '' : `${button('transform', '升八度', '', 'quiet', 'data-transform="up"')}${button('transform', '降八度', '', 'quiet', 'data-transform="down"')}${button('transpose-dialog', '移调 / 调式适配', 'piano', 'quiet')}${button('transform', '半音镜像', 'mirror', 'quiet', 'data-transform="mirror"')}${button('transform', '调内级数镜像', '', 'quiet', 'data-transform="mirror-scale"')}`}${button('transform', '时间反转', 'reverse', 'quiet', 'data-transform="reverse"')}${button('transform', '右移一格', 'arrow', 'quiet', 'data-transform="shift"')}${button('transform', '力度变化', 'spark', 'quiet', 'data-transform="humanize"')}`;
        return top + `<section class="editor-card" style="--track:${t.color}"><div class="editor-top"><div class="pattern-title"><span class="pattern-letter">${String.fromCharCode(65 + t.patterns.findIndex(x => x.id === p.id) % 26)}</span><button data-action="rename-pattern">${esc(p.name)}${icon('pencil', 13)}</button><small>${p.notes.length} 个${t.kind === 'drum' ? '鼓点' : '音符'}</small></div><div class="bar-pages">${p.bars > 1 ? Array.from({ length: p.bars }, (_, i) => button('page', String(i + 1), '', S.page === i ? 'active' : '', `data-page="${i}" aria-label="第 ${i + 1} 小节"`)).join('') : ''}<select data-field="pattern-length" aria-label="片段小节数">${[1, 2, 4, 8].map(n => `<option value="${n}" ${n === p.bars ? 'selected' : ''}>${n} 小节</option>`).join('')}</select></div></div>
 <div class="editor-tools"><div class="tool-group">${[['draw', '画笔', 'pencil'], ...(t.kind === 'drum' ? [] : [['chord', '和弦', 'chord']]), ['select', '框选', 'select'], ['erase', '橡皮', 'eraser'], ['pan', '浏览', 'hand']].map(([id, l, ic]) => button('tool', l, ic, S.tool === id ? 'active' : '', `data-tool="${id}" aria-pressed="${S.tool===id}"`)).join('')}</div>${S.tool === 'chord' && t.kind !== 'drum' ? `<select data-field="chord" aria-label="和弦类型">${Object.entries({ major: '大三和弦', minor: '小三和弦', maj7: '大七和弦', min7: '小七和弦', dom7: '属七和弦', sus2: '挂二', sus4: '挂四', fifth: '纯五度' }).map(([id, l]) => `<option value="${id}" ${S.chord === id ? 'selected' : ''}>${l}</option>`).join('')}</select>` : ''}<div class="editor-group-tabs">${groups.map(([id, l]) => button('editor-group', l, '', S.editorGroup === id ? 'active' : '', `data-group="${id}" aria-pressed="${S.editorGroup===id}"`)).join('')}</div><div class="tools-right">${t.kind==='drum'?viewControls:S.editorGroup!=='aids'?button('composer','和弦进行','chord','soft-btn'):''}${button('zoom-out', '缩小', 'minus', 'quiet','title="缩小画板"')}${button('zoom-in', '放大', 'plus', 'quiet')}</div></div>
 ${S.editorGroup === 'notes' || (t.kind !== 'drum' && S.editorGroup) ? `<div class="editor-options">${S.editorGroup === 'aids' ? aids : S.editorGroup === 'notes' ? transforms : viewControls}</div>` : ''}
 <div class="grid-scroll ${S.tool === 'pan' ? 'pan-mode' : ''}" data-scroll="grid"><div class="gridframe" id="gridframe" tabindex="0" role="application" aria-label="${t.kind === 'drum' ? '鼓机' : '钢琴卷帘'}编辑网格"><div id="grid-inner"></div></div></div>
 <div class="selection-bar"><span class="selection-info">${S.selected.length ? `已选 <b>${S.selected.length}</b> 音` : '每小节 16 格 · 底部拖动力度'}</span><div class="selection-actions">${S.selected.length ? `${button('copy-notes', '复制', 'copy', 'quiet')}${button('shorten-notes', '时长 ½', '', 'quiet')}${button('lengthen-notes', '时长 ×2', '', 'quiet')}${button('split-notes', '拆分', 'split', 'quiet')}${button('delete-notes', '删除', 'trash', 'quiet')}` : ''}${S.clipboard ? button('paste-notes', '粘贴', 'copy', 'quiet') : ''}${button('select-all', '全选', '', 'quiet')}${button('clear-pattern', '清空', '', 'quiet')}</div></div></section>
 <section class="pattern-shelf compact-shelf"><div class="section-line"><h2>本轨片段</h2><div>${button('duplicate-pattern', '创建 A′', 'copy', 'soft-btn')}${button('add-pattern', '新片段', 'plus', 'quiet')}</div></div><div class="pattern-cards">${t.patterns.map((pat, i) => `<button class="pattern-card ${pat.id === p.id ? 'selected' : ''}" data-action="pattern" data-id="${pat.id}" style="--track:${t.color}"><div><b>${String.fromCharCode(65 + i % 26)}</b><span>${esc(pat.name)}</span><small>${pat.bars} 小节</small></div>${miniPattern(pat, t, 240, 32)}</button>`).join('')}</div></section>`;
    };
})(globalThis.GridTone ||= {});
