/** A single note editor docked below arrangement. Sound and transforms live in the inspector. */
(function(G){G.views||={};
 G.views.renderEditor=function(C){
  const {S,project,track,pattern,button,ib,esc,presetName}=C,t=track(),p=pattern(),c=t.clips.find(c=>c.id===S.clipId),refs=t.clips.filter(c=>c.patternId===p.id).length,a=G.resolveEditTarget(project,S);
  const status=G.dependencyStatus(project,p,c),warning=G.harmonyStatus(p)==='stale'?'和弦有改动 · 请复核':status==='stale'?'参考内容有改动':status==='missing'?'参考来源已删除':'';
  return `<header class="dock-header"><div class="dock-identity"><span class="track-dot" style="background:${t.color}"></span><div><strong>${esc(p.name)}</strong><small>${esc(t.name)} · ${c?`第 ${c.bar+1}—${c.bar+p.bars} 小节`:'尚未放入编排'}${refs>1?` · ${refs} 处关联`:''}</small></div></div><div class="dock-actions">${button('open-sound',presetName(t),'wave','quiet sound-chip',`data-track="${t.id}" title="本轨音色 · 影响整条音轨"`)}${button('listen-pattern','试听当前块','headphones','quiet')}${ib('expand-editor',S.editorExpanded?'恢复编排与画板':'放大音符编辑器','grid')}${ib('close-editor','收起音符编辑器','close')}</div></header>${warning?`<div class="editor-warning" role="status">${esc(warning)} ${button('harmony-editor','检查和声','chord','quiet')}</div>`:''}
  ${a.kind==='clips'&&a.ids.length>1?`<p class="editor-context-note">正在操作 ${a.ids.length} 个音乐块。下方显示「${esc(p.name)}」；进入画板后只编辑这块内容。</p>`:''}
  <div class="studio-edit-tools" role="toolbar" aria-label="画板工具"><div class="tool-group">${[['draw','画笔','pencil','B'],['select','选择','select','V'],['range','范围','range','R'],['erase','橡皮','eraser','E'],['pan','浏览','hand','H']].map(([id,label,ic,key])=>button('tool',label,ic,S.tool===id?'active small-btn':'quiet small-btn',`data-tool="${id}" aria-pressed="${S.tool===id}" title="${label} · ${key}"`)).join('')}${t.kind!=='drum'?button('tool','和弦','chord',S.tool==='chord'?'active small-btn':'quiet small-btn','data-tool="chord" aria-label="和弦画笔"'):''}</div>
  <div class="canvas-view-controls"><label>网格<select data-field="snap" aria-label="吸附精度">${[[480,'1/8'],[240,'1/16'],[120,'1/32'],[320,'1/8 三连'],[160,'1/16 三连'],[80,'1/32 三连'],[0,'自由']].map(([v,l])=>`<option value="${v}" ${S.snap===v?'selected':''}>${l}</option>`).join('')}</select></label>${!S.continuous?`<select data-field="editor-page" aria-label="当前小节">${Array.from({length:p.bars},(_,i)=>`<option value="${i}" ${S.page===i?'selected':''}>第 ${i+1} 小节</option>`).join('')}</select>`:''}${ib('zoom-out','缩小时间轴','minus')}${ib('zoom-in','放大时间轴','plus')}${button('fit-notes','适配','','quiet')}${t.kind!=='drum'?ib('octave-down','浏览低八度','minus')+ib('octave-up','浏览高八度','plus'):''}${ib('canvas-settings','视图与输入辅助','dots')}</div></div>
  ${S.tool==='chord'?`<div class="tool-options"><label>和弦类型 <select data-field="chord">${Object.keys(G.CHORDS).map(k=>`<option value="${k}" ${S.chord===k?'selected':''}>${({major:'大三',minor:'小三',maj7:'大七',min7:'小七',dom7:'属七',sus2:'挂二',sus4:'挂四',fifth:'五度'})[k]}</option>`).join('')}</select></label><small>画出后仍是可独立编辑的音符</small></div>`:''}
  <div id="candidate-overlay-status" class="projection-status" role="status" hidden></div>
  <div class="grid-scroll ${S.tool==='pan'?'pan-mode':''}" data-scroll="grid"><div class="gridframe" id="gridframe" tabindex="0" role="application" aria-label="音符编辑画布"><div id="grid-inner"></div></div></div>
  <footer class="dock-footer"><span>${a.kind==='range'?'已选时间范围，包含其中的休止':S.selected.length?`记住 ${S.selected.length} 个音符的选择 · 基础操作在顶部`:'点格子画音 · 拖右边缘延长 · 音高尺可拖动浏览'}</span><small>编辑落点：${G.editPositionLabel(S.cursor||0)}</small></footer>`;
 };
})(globalThis.GridTone||={});
