/** One persistent side-panel slot. Attribute ownership is always explicit. */
(function(G){G.views||={};
 G.views.renderInspector=function(C){
  const {project,S,button,ib,esc,slider}=C,type=S.rightPanel;if(!type||['creation','composer'].includes(type))return '';
  const t=project.tracks.find(t=>t.id===S.inspectorTrackId)||G.activeEditTrack(project,S),a=G.resolveEditTarget(project,S),p=t?.patterns.find(p=>p.id===S.patternId);
  const resume=Object.entries(C.drafts||{}).filter(([,on])=>on).map(([id])=>button('resume-tool',id==='creation'?'恢复生成草稿':'恢复和弦草稿','undo','quiet',`data-panel="${id}"`)).join('');
  const head=(title,note)=>`<div class="inspector-pinned"><header class="creation-dock-heading"><div><small>${esc(note)}</small><h2>${esc(title)}</h2></div>${ib('inspector-close','关闭工具面板','close')}</header>${resume?`<div class="tool-resume">${resume}</div>`:''}${['properties','sound','pipeline'].includes(type)?tabs:''}</div>`;
  const tabs=`<nav class="inspector-tabs" aria-label="本轨工具">${[['properties','属性'],['sound','音色'],['pipeline','演奏']].map(([id,label])=>button('inspector-tab',label,'',type===id?'active':'quiet',`data-panel="${id}" data-track="${t?.id}"`)).join('')}</nav>`;
  if(['properties','sound','pipeline'].includes(type)){
   let body='';
   if(type==='properties')body=`<section class="inspector-section"><label class="form-label">音轨名称<input data-field="inspector-name" data-track="${t.id}" value="${esc(t.name)}" maxlength="60"></label><label class="form-label">声部角色<select data-field="inspector-role" data-track="${t.id}">${[['unspecified','未指定'],['melody','旋律'],['bass','贝斯'],['chords','和弦'],['drums','鼓点'],['texture','伴奏 / 氛围']].map(([k,l])=>`<option value="${k}" ${(t.role||'unspecified')===k?'selected':''}>${l}</option>`).join('')}</select></label><p>这些设置属于整条音轨；下方画板仍显示原来打开的音乐块。</p></section><section class="inspector-section"><h3>基本平衡</h3>${slider('音量','track','volume',t.volume,0,1,.01,'',t.id)}${slider('左右位置','track','pan',t.pan,-1,1,.01,'',t.id)}<div class="button-row">${button('mute','静音','',t.mute?'active':'quiet',`data-id="${t.id}" aria-pressed="${t.mute}"`)}${button('solo','只听','',C.B.soloIds.includes(t.id)?'active':'quiet',`data-id="${t.id}" aria-pressed="${C.B.soloIds.includes(t.id)}"`)}</div></section><section class="inspector-section"><h3>轨道中的音乐块</h3>${t.clips.length?`<div class="pattern-list">${t.clips.map(c=>{const pat=t.patterns.find(p=>p.id===c.patternId);return button('open-instance',pat.name+' · 第 '+(c.bar+1)+' 小节','pencil','quiet',`data-track="${t.id}" data-clip-id="${c.id}"`);}).join('')}</div>`:'<p>此轨尚无编排内容，可从音乐模板库拿取。</p>'}${t.patterns.filter(p=>!t.clips.some(c=>c.patternId===p.id)).length?`<details><summary>尚未编排的内容</summary><div class="pattern-list">${t.patterns.filter(p=>!t.clips.some(c=>c.patternId===p.id)).map(p=>button('open-pattern-id',p.name,'pencil','quiet',`data-track="${t.id}" data-pattern="${p.id}"`)).join('')}</div></details>`:''}</section>`;
   if(type==='sound'){const preset=G.resolvePreset(t.preset,project);body=`<section class="inspector-section sound-current"><span class="eyebrow">本轨声音</span><h3>${C.esc(preset.name||t.name)}</h3><p>只替换声音，音符和节奏保持。影响本轨全部音乐块。</p><div class="button-column">${button('library-open','选择音色','piano','dark-btn',`data-kind="sound" data-track="${t.id}" data-id="${t.preset}"`)}${button('sound-audition','试听当前声音','headphones','quiet',`data-id="${t.preset}"`)}</div></section><details class="inspector-section"><summary>调节与导入</summary><p>音色参数保存在本轨，随作品保存。</p>${button('sound-full','调整当前声音','wave','quiet',`data-track="${t.id}"`)}${button('sound-resources','声音资源与导入','folder','quiet',`data-track="${t.id}"`)}</details>`;}
   if(type==='pipeline')body=C.renderPipeline();
   return head(t.name,'本轨工具 · 影响该轨全部音乐块')+body;
  }
  if(type==='arrangement')return head('编排结构','作用于歌曲中的音乐块')+`<section class="inspector-section"><h3>现有材料</h3><div class="button-column">${button('time-tools','长度与时间编辑','range','soft-btn')}${button('repeat-song','整段重复','copy','soft-btn')}${button('creation','发展编排','spark','soft-btn','data-mode="arrange"')}${button('creation','声部一起变化','spark','quiet','data-mode="ensemble"')}</div><p>重复保留关联；发展编排可以选择主题、变化与结尾。</p></section><section class="inspector-section"><h3>快速铺底</h3>${button('recipes','选择组合模板','grid','soft-btn')}<p>也可以直接打开音乐模板库放入一套材料。</p></section>`;
  if(type==='view')return head('视图与输入辅助','画板范围不改写已有音符')+`<section class="inspector-section"><h3>画布</h3>${G.ui.Toggle({field:'continuous',label:'连续显示全部小节',checked:S.continuous})}${button('fit-notes','适配全部音符','grid','soft-btn')}<div class="button-row">${button('octave-down','浏览低八度','minus','quiet')}${button('octave-up','浏览高八度','plus','quiet')}</div></section><section class="inspector-section"><h3>参考调性</h3><label class="form-label">主音<select data-field="key">${G.KEYS.map((k,i)=>`<option value="${i}" ${project.key===i?'selected':''}>${k}</option>`).join('')}</select></label><label class="form-label">音阶<select data-field="scale">${[['major','大调'],['minor','小调'],['pentatonic','五声音阶'],['chromatic','全部半音']].map(([k,l])=>`<option value="${k}" ${project.scale===k?'selected':''}>${l}</option>`).join('')}</select></label>${G.ui.Toggle({field:'scale-display',label:'简化调内音显示',checked:S.showScale})}${G.ui.Toggle({field:'input-snap',label:'新音符吸附调内',checked:S.inputSnap})}<p>参考设置用于显示和后续输入，已有音符保持原样。</p></section><section class="inspector-section"><h3>全曲律动</h3>${slider('十六分 Swing','project','swing',project.swing,0,.45,.01)}<p>影响整首作品的演奏；与本画板吸附网格分别管理。</p></section>`;
  if(type==='edit'){
   const label=G.editTargetLabel(project,S),noteTarget=['notes','range'].includes(a.kind),clipTarget=a.kind==='clips',single=clipTarget&&a.ids.length===1;
   const useP=noteTarget?a.pattern:single?a.items[0].pattern:null;
   const common=useP?`<section class="inspector-section"><h3>音乐块内容</h3>${button('rename-pattern','重命名音乐块','pencil','quiet')}<label class="form-label">长度<select data-field="pattern-length">${G.PATTERN_BARS.map(n=>`<option value="${n}" ${useP.bars===n?'selected':''}>${n} 小节</option>`).join('')}</select></label><p>共享内容的长度与音符修改会影响全部引用。</p></section>`:'';
   let content='';
   if(clipTarget)content=`<section class="inspector-section"><h3>音乐块关系</h3><div class="button-column">${['linked','unlink'].map(id=>{const d=G.editCommandState(project,S,id);return button('edit-command',d.label,d.icon,'soft-btn',`data-command="${id}" ${d.enabled?'':'disabled'} title="${esc(d.reason)}"`);}).join('')}</div><p>复制一份是独立内容。关联重复共同使用同一份音符；移除音乐块只移除它的编排位置。</p></section>`;
   if(noteTarget)content=`<section class="inspector-section"><h3>音符变形</h3><p>${a.kind==='range'?'作用于明确选区内的音符':a.ids.length?'仅作用于所选音符':'先选择音符，或使用全选'}</p><div class="transform-grid">${[['up','升八度'],['down','降八度'],['mirror','半音镜像'],['mirror-scale','调内镜像'],['reverse','时间反转'],['humanize','力度变化'],['quantize','起音对齐网格']].map(([id,label])=>button('edit-transform',label,'','quiet',`data-transform="${id}" title="${id==='quantize'?'仅对齐起音，时长保持不变':''}" ${a.kind==='notes'&&!a.ids.length||id==='quantize'&&!S.snap?'disabled':''}`)).join('')}</div><h3>时长与分割</h3><div class="transform-grid">${[['half','时长减半'],['double','时长加倍'],['split','从中间拆分'],['cursor','在光标拆分']].map(([id,label])=>button('edit-duration',label,'','quiet',`data-duration="${id}" ${a.kind==='notes'&&!a.ids.length?'disabled':''}`)).join('')}</div><label class="form-label">设置力度（1—100%）<input type="number" min="1" max="100" value="75" id="selection-velocity"></label>${button('edit-velocity','应用力度','','soft-btn',a.kind==='notes'&&!a.ids.length?'disabled':'')}${button('transpose-dialog','移调与调式适配','piano','quiet',a.kind==='notes'&&!a.ids.length?'disabled':'')}${button('note-inspector','精细修改 / 前后比较','pencil','quiet',a.kind==='notes'&&!a.ids.length?'disabled':'')}</section>`;
   const musical=useP?`<section class="inspector-section"><h3>生成与变化</h3><div class="button-column">${(noteTarget?a.track:a.items?.[0]?.track)?.kind!=='drum'?button('composer','选择和弦进行','chord','soft-btn'):''}${button('creation',(noteTarget?a.track:a.items?.[0]?.track)?.kind==='drum'?'鼓型变化':'按现有材料生成','spark','soft-btn')}${(noteTarget?a.track:a.items?.[0]?.track)?.kind!=='drum'?button('creation','只改结尾','','quiet','data-mode="ending"')+button('creation','写一个回答句','','quiet','data-mode="answer"'):''}</div><p>生成后仍是普通音符，可继续手动编辑。</p></section>`:'';
   return head(label.title,'编辑工具 · 随当前选择更新')+`<p class="scope-note">${esc(label.detail)}</p>`+content+musical+common+(noteTarget?`<section class="inspector-section danger-section">${button('edit-command','清空音乐块内容','trash','danger-btn','data-command="clear"')}<p>这是清空内容，会明确确认共享影响。</p></section>`:'');
  }
  return '';
 };
})(globalThis.GridTone||={});
