/** View renderer. Receives the current document and session; never mutates either. */
(function (G) {
    'use strict';
    G.views ||= {};
    G.views.renderMix = function (C) {
        const { project, S, B, track, pattern, button, ib, icon, esc, miniPattern, slider, presetName, trackIcon, soundCards, waveIllustration, renderSound, renderPipeline } = C;
        const { KEYS, PRESETS, clamp, noteName, presetById, canPlace } = G;
        return `<div class="view-heading compact-heading"><div><span class="eyebrow">MIX / 作品混音</span><span class="pill">${project.tracks.length} 条音轨</span><p>音量、声像与静音保存到作品。“只听”为临时比较。</p></div><div class="heading-actions">${(B.soloIds.length || B.target === 'tracks') ? button('clear-solo', '恢复全曲', 'headphones', 'soft-btn') : ''}${button('listen-tracks', '试听勾选音轨', 'play', 'quiet', B.selectedTrackIds.length ? '' : 'disabled')}${button('reset-mix', '重置混音', 'undo', 'soft-btn')}</div></div><div class="mix-layout"><div class="mixer-channels">${project.tracks.map(t => `<section class="mixer-channel" data-component="channel-strip" style="--track:${t.color};${G.ui.musicStyle(t.color,t.role||(t.kind==='drum'?'drums':'melody'))}"><div class="channel-head"><label class="monitor-check"><input type="checkbox" data-field="monitor-track" data-id="${t.id}" ${B.selectedTrackIds.includes(t.id) ? 'checked' : ''} aria-label="勾选 ${esc(t.name)} 试听"> 加入试听</label><span>${icon(trackIcon(t), 23)}</span><h3>${esc(t.name)}</h3><small>${esc(presetName(t))}</small></div><div class="mute-solo">${button('mute', '静音', '', t.mute ? 'active soft-btn' : 'soft-btn', `data-id="${t.id}" title="作品静音" aria-pressed="${t.mute}"`)}${button('solo', '只听', '', B.soloIds.includes(t.id) ? 'active soft-btn' : 'soft-btn', `data-id="${t.id}" title="临时只听，可选多轨" aria-pressed="${B.soloIds.includes(t.id)}"`)}</div><div class="fader-area"><div class="db-labels"><span>0</span><span>−6</span><span>−12</span><span>−24</span><span>−∞</span></div><input type="range" class="vertical-fader" min="0" max="1" step=".01" value="${t.volume}" data-range="track.volume" data-track="${t.id}" aria-label="${esc(t.name)} 音量"><div class="channel-meter"><i data-meter="${t.id}"></i></div></div><strong class="volume-readout" data-volume="${t.id}">${t.volume > 0 ? (20 * Math.log10(t.volume)).toFixed(1) : '−∞'} dB</strong><div class="channel-knobs">${slider('左右位置', 'track', 'pan', t.pan, -1, 1, .01, t.pan === 0 ? '居中' : `${t.pan < 0 ? '左' : '右'} ${Math.round(Math.abs(t.pan) * 100)}`, t.id)}${slider('混响', 'fx', 'reverb', t.fx.reverb, 0, 1, .01, '', t.id)}${slider('回声', 'fx', 'delay', t.fx.delay, 0, 1, .01, '', t.id)}</div></section>`).join('')}</div><section class="master-channel"><span class="eyebrow">MASTER OUTPUT</span><h2>总输出</h2><div class="master-art">${icon('volume', 68)}</div>${slider('总音量', 'project', 'master', project.master)}<p>内置动态压缩控制峰值。WAV 导出时，仅在峰值过高时整体衰减，避免削波。</p>${button('export', '导出作品', 'download', 'dark-btn full-width')}<div class="mix-note">播放时使用耳机，<br>从较低音量开始。</div></section></div>`;
    };
})(globalThis.GridTone ||= {});
