/** View renderer. Receives the current document and session; never mutates either. */
(function (G) {
    'use strict';
    G.views ||= {};
    G.views.renderMix = function (C) {
        const { project, S, B, track, pattern, button, ib, icon, esc, miniPattern, slider, presetName, trackIcon, soundCards, waveIllustration, renderSound, renderPipeline } = C;
        const { KEYS, PRESETS, clamp, noteName, presetById, canPlace } = G;
        return `<header class="mix-command-bar"><div class="mix-identity"><h2>混音</h2><small>${project.tracks.length} 条音轨</small></div><div class="mix-command-actions" role="group" aria-label="混音比较与恢复">${(B.soloIds.length || B.target === 'tracks') ? button('clear-solo', '恢复全曲', 'headphones', 'quiet small-btn') : ''}${button('listen-tracks', '试听勾选音轨', 'play', 'quiet small-btn', B.selectedTrackIds.length ? '' : 'disabled')}${button('reset-mix', '重置混音', 'undo', 'quiet small-btn')}${button('creation','建议混音','spark','quiet small-btn','data-mode="mix"')}</div></header><p class="mix-scope">音量、声像与静音保存到作品。“只听”为临时比较。</p><div class="mix-layout"><div class="mixer-channels">${project.tracks.map(t => `<section class="mixer-channel" data-component="channel-strip" style="--track:${t.color};${G.ui.musicStyle(t.color,t.role||(t.kind==='drum'?'drums':'melody'))}"><div class="channel-head"><label class="monitor-check"><input type="checkbox" data-field="monitor-track" data-id="${t.id}" ${B.selectedTrackIds.includes(t.id) ? 'checked' : ''} aria-label="勾选 ${esc(t.name)} 试听"> 加入试听</label><div class="channel-identity"><span>${icon(trackIcon(t), 18)}</span><h3 title="${esc(t.name)}">${esc(t.name)}</h3></div><small title="${esc(presetName(t))}">${esc(presetName(t))}</small></div><div class="mute-solo action-tray" role="group" aria-label="静音与只听">${button('mute', '静音', '', t.mute ? 'active soft-btn small-btn' : 'soft-btn small-btn', `data-id="${t.id}" title="作品静音" aria-pressed="${t.mute}"`)}${button('solo', '只听', '', B.soloIds.includes(t.id) ? 'active soft-btn small-btn' : 'soft-btn small-btn', `data-id="${t.id}" title="临时只听，可选多轨" aria-pressed="${B.soloIds.includes(t.id)}"`)}</div><div class="fader-area"><div class="db-labels"><span>0</span><span>−6</span><span>−12</span><span>−24</span><span>−∞</span></div><input type="range" class="vertical-fader" min="0" max="1" step=".01" value="${t.volume}" data-range="track.volume" data-track="${t.id}" aria-label="${esc(t.name)} 音量"><div class="channel-meter"><i data-meter="${t.id}"></i></div></div><strong class="volume-readout" data-volume="${t.id}">${t.volume > 0 ? (20 * Math.log10(t.volume)).toFixed(1) : '−∞'} dB</strong><div class="channel-knobs">${slider('左右位置', 'track', 'pan', t.pan, -1, 1, .01, t.pan === 0 ? '居中' : `${t.pan < 0 ? '左' : '右'} ${Math.round(Math.abs(t.pan) * 100)}`, t.id)}<details class="channel-effects"><summary>本轨效果</summary>${slider('混响', 'fx', 'reverb', t.fx.reverb, 0, 1, .01, '', t.id)}${slider('回声', 'fx', 'delay', t.fx.delay, 0, 1, .01, '', t.id)}</details></div></section>`).join('')}</div><section class="master-channel"><h2>总输出</h2>${slider('总音量', 'project', 'master', project.master)}<details><summary>输出说明</summary><p>内置动态压缩控制峰值。WAV 导出仅在峰值过高时整体衰减，避免削波。播放时用耳机，从较低音量开始。</p></details>${button('export', '导出作品', 'download', 'dark-btn full-width')}</section></div>`;
    };
})(globalThis.GridTone ||= {});
