/** Stable layers for the musical canvas; content is data, never a decorative asset. */
(function(G){G.views ||= {};let staticKey='';
 G.views.drawPianoRoll=function(C){
  const {project,S,track,pattern,getRows,drag,esc}=C,frame=document.querySelector('#gridframe');if(!frame)return;
  const t=track(),p=pattern(),paint=G.ui.musicPalette(t.color,t.role|| (t.kind==='drum'?'drums':'melody')),rows=getRows(),vp=G.viewportFor(S,t),win=G.gridWindow(S,p),left=t.kind==='drum'?100:86,top=28,baseRow=t.kind==='drum'?32:vp.rowHeight,rh=S.editorExpanded?Math.max(baseRow,Math.min(42,Math.floor((frame.parentElement.clientHeight-top-74)/rows.length))):baseRow;
  const width=Math.max(frame.parentElement.clientWidth-2,win.bars*200*vp.zoomX+left+12),cw=(width-left-12)/(win.bars*16),height=top+rows.length*rh+74;
  const geo={width,left,top,row:rh,cw,rows,height,offset:win.offset,bars:win.bars};
  const key=JSON.stringify([width,rows,rh,win,t.id,project.key,project.scale,S.snap,S.showScale,t.color]);
  let svg=document.querySelector('#note-grid');
  if(!svg||key!==staticKey){
   staticKey=key;let bg=`<rect width="${width}" height="${height}" fill="var(--grid-paper)"/>`;
   rows.forEach((pitch,i)=>{const y=top+i*rh,black=[1,3,6,8,10].includes(pitch%12),root=pitch%12===project.key;bg+=`<rect x="${left}" y="${y}" width="${width-left}" height="${rh}" fill="${S.showScale&&G.inScale(pitch,project.key,project.scale)?'var(--selected)':black?'var(--grid-key)':'var(--grid-paper)'}"/><line x1="${left}" x2="${width}" y1="${y+rh}" y2="${y+rh}" stroke="var(--grid-minor)"/>`;});
   const gridStep=S.snap||G.STEP;for(let j=0;j<=win.bars*G.BAR/gridStep;j++){const i=j*gridStep/G.STEP,x=left+i*cw;bg+=`<line x1="${x}" x2="${x}" y1="${top}" y2="${top+rows.length*rh}" stroke="${i%16===0?'var(--grid-major)':i%4===0?'var(--line)':'var(--grid-minor)'}"/>`;if(i%16===0&&i<win.bars*16)bg+=`<text x="${x+8}" y="18" font-size="11" fill="var(--muted)">${win.offset/G.BAR+i/16+1}</text>`;}
   frame.querySelector('#grid-inner').innerHTML=`<svg id="note-grid" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="音符网格 · ${win.bars} 小节" data-left="${left}" data-low="${vp.low}" data-span="${vp.span}" data-row-height="${rh}" data-cell-width="${cw}"><defs><linearGradient id="note-face" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${paint.surface}"/><stop offset="1" stop-color="${paint.noteSurface}"/></linearGradient></defs><g id="grid-background">${bg}</g><g id="note-origin-layer" pointer-events="none"></g><g id="note-layer"></g><g id="velocity-layer"></g><g id="selection-layer"></g><g id="playhead" visibility="hidden" pointer-events="none"><circle cx="0" cy="22" r="3.5" fill="var(--color-playhead)"/><line x1="0" x2="0" y1="${top}" y2="${height}" stroke="var(--color-playhead)" stroke-width="1.5"/></g><g id="pitch-axis" data-pitch-axis="true" aria-label="音高尺：点击试听，上下拖动浏览音域"></g></svg>`;
   svg=document.querySelector('#note-grid');
  }
  let notes='',velocities='';const vy=top+rows.length*rh+12,a=G.resolveEditTarget(project,S),active=a.kind==='notes'&&a.patternId===p.id,selected=new Set(active?S.selected:[]);
  for(const n of p.notes){if(n.start>=win.offset+win.bars*G.BAR||n.start+n.duration<=win.offset)continue;const row=rows.indexOf(n.pitch);if(row<0)continue;
   const x=left+(Math.max(win.offset,n.start)-win.offset)/G.STEP*cw+1,y=top+row*rh+3,nw=Math.max(3,(Math.min(win.offset+win.bars*G.BAR,n.start+n.duration)-Math.max(win.offset,n.start))/G.STEP*cw-2),sel=selected.has(n.id);
   notes+=`<g data-note="${n.id}" class="note ${sel?'chosen':S.selected.includes(n.id)?'context-selected':''} ${drag?.moved&&drag.notes?.has(n.id)?'is-moving':''}" style="cursor:grab;--track:${t.color};${G.ui.musicStyle(t.color,t.role)}"><rect class="note-body" x="${x}" y="${y}" width="${nw}" height="${Math.max(6,rh-6)}" rx="4" fill="url(#note-face)" stroke="${sel?'var(--ink)':paint.border}" stroke-width="${sel?1.5:1}"/><line class="note-edge" x1="${x+3}" x2="${x+Math.max(3,nw-3)}" y1="${y+1}" y2="${y+1}" stroke="white"/><line class="note-bottom" x1="${x+3}" x2="${x+Math.max(3,nw-3)}" y1="${y+Math.max(6,rh-6)-1}" y2="${y+Math.max(6,rh-6)-1}" stroke="${paint.border}"/>${sel?`<circle class="note-handle" cx="${x+nw-2}" cy="${y+Math.max(6,rh-6)/2}" r="3.5" fill="white" stroke="var(--ink)"/>`:''}${nw>70&&rh>=24?`<text x="${x+5}" y="${y+rh/2}" font-size="11" fill="${paint.ink}" pointer-events="none">${esc(G.noteName(n.pitch))}</text>`:''}${n.start+n.duration<=win.offset+win.bars*G.BAR?`<rect data-resize="${n.id}" x="${x+Math.max(0,nw-8)}" y="${y}" width="${Math.min(nw,8)}" height="${Math.max(6,rh-6)}" fill="transparent" style="cursor:ew-resize"/>`:''}</g>`;
   const vx=left+(n.start-win.offset)/G.STEP*cw;
   if(vx>=left)velocities+=`<rect data-note="v-${n.id}" x="${vx}" y="${vy+48*(1-n.velocity)}" width="${sel?5:3}" height="${48*n.velocity}" rx="1" fill="${sel?'var(--brand)':paint.ink}" opacity="${selected.size&&!sel ? .35 : .8}"/>`;
  }
  // SVG-aware keyed patching avoids replacing capture targets and static grid lines.
  function layer(id,html){const el=document.getElementById(id);if(el.dataset.markup===html)return;el.dataset.markup=html;const container=document.createElementNS('http://www.w3.org/2000/svg','g');container.innerHTML=html;const old=new Map([...el.children].map(n=>[n.getAttribute('data-note'),n]));for(const n of [...container.children]){const prev=old.get(n.getAttribute('data-note'));if(prev){old.delete(n.getAttribute('data-note'));if(prev.outerHTML!==n.outerHTML)prev.replaceWith(n);}else el.append(n);}for(const n of old.values())n.remove();}
  layer('note-layer',notes||`<text data-note="empty-hint" x="${left+(width-left)/2}" y="${top+Math.min(rows.length*rh/2,110)}" text-anchor="middle" font-size="13" fill="var(--muted)" pointer-events="none">${t.kind==='drum'?'点亮一个格子，开始节奏':'点一下，写下第一个音符'}</text>`);layer('velocity-layer',`<text data-note="velocity-label" x="${left-10}" y="${vy+27}" text-anchor="end" font-size="11" fill="var(--muted)">力度</text>`+velocities);
  const origin=document.querySelector('#note-origin-layer');if(origin)origin.innerHTML=drag?.moved&&drag.notes?[...drag.notes.values()].map(n=>{const row=rows.indexOf(n.pitch);if(row<0)return '';return `<rect x="${left+(n.start-win.offset)/G.STEP*cw+1}" y="${top+row*rh+3}" width="${Math.max(3,n.duration/G.STEP*cw-2)}" height="${Math.max(6,rh-6)}" rx="3" fill="none" stroke="${paint.ink}" stroke-opacity=".6" stroke-dasharray="3 3"/>`;}).join(''):'';
  const selection=document.querySelector('#selection-layer');const selectedRange=a.kind==='range'&&a.patternId===p.id?a.range:null;const cursorX=left+((S.cursor||0)-win.offset)/G.STEP*cw;const overlays=(selectedRange?`<rect x="${left+(selectedRange.start-win.offset)/G.STEP*cw}" y="${top}" width="${(selectedRange.end-selectedRange.start)/G.STEP*cw}" height="${rows.length*rh}" fill="var(--brand)" fill-opacity=".09" stroke="var(--brand)" pointer-events="none"/>`:'')+(cursorX>=left&&cursorX<=width?`<path d="M${cursorX} ${top}V${top+rows.length*rh}" stroke="var(--brand)" stroke-opacity=".35" stroke-dasharray="3 3" pointer-events="none"/>`:'');selection.innerHTML=overlays+(drag?.type==='marquee'?`<rect x="${Math.min(drag.x,drag.mx)}" y="${Math.min(drag.y,drag.my)}" width="${Math.abs(drag.mx-drag.x)}" height="${Math.abs(drag.my-drag.y)}" fill="var(--brand)" fill-opacity=".09" stroke="var(--brand)"/>`:'');
  const axis=svg.querySelector('#pitch-axis');
  axis.innerHTML=`<rect x="0" y="0" width="${left}" height="${height}" fill="var(--surface)"/><path d="M${left-.5} 0V${height}" stroke="var(--line-strong)"/>`+rows.map((pitch,i)=>`<g><rect data-ruler-pitch="${pitch}" x="0" y="${top+i*rh}" width="${left-1}" height="${rh}" fill="var(--surface)"/><line x1="0" x2="${left-1}" y1="${top+(i+1)*rh}" y2="${top+(i+1)*rh}" stroke="var(--line-strong)" pointer-events="none"/>${t.kind!=='drum'?`<rect x="0" y="${top+i*rh+2}" width="28" height="${rh-4}" rx="2" fill="${[1,3,6,8,10].includes(pitch%12)?'var(--key-dark)':'var(--button-face)'}" stroke="var(--line-strong)" pointer-events="none"/><line x1="2" x2="26" y1="${top+i*rh+3}" y2="${top+i*rh+3}" stroke="white" opacity=".5" pointer-events="none"/>`: ''}<text x="${left-10}" y="${top+i*rh+rh/2+4}" text-anchor="end" font-size="12" fill="var(--muted)" pointer-events="none">${esc(t.kind==='drum'?(G.drumsFor(project,t).find(d=>d.pitch===pitch)?.name||pitch):G.noteName(pitch))}</text></g>`).join('')+`<text x="${left-10}" y="${vy+27}" text-anchor="end" font-size="12" fill="var(--ink)" pointer-events="none">力度</text>`;
  const scroll=frame.parentElement;
  const pin=()=>{const svg=document.querySelector('#note-grid'),axis=svg?.querySelector('#pitch-axis');if(axis)axis.setAttribute('transform',`translate(${scroll.scrollLeft},0)`);};
  if(!scroll.dataset.pitchPin){scroll.addEventListener('scroll',pin,{passive:true});scroll.dataset.pitchPin='true';}
  pin();
  return geo;
 };
})(globalThis.GridTone ||= {});
