/** Track-scoped inspector, shared by all workspaces. */
(function (G) {
 G.views ||= {};
 G.views.renderProperties = function (C) {
 const { project, S, B, track, pattern, button, ib, esc, slider, presetName } = C;
 const { PRESETS } = G; const t=track(), p=pattern();
 return `<aside class="properties-sidebar" aria-label="音轨属性"><header><span class="eyebrow">当前音轨</span>${ib('close-sidebar', '收起属性', 'close')}</header><h2>${esc(t.name)}</h2><p class="scope-note">这里的设置影响本轨全部片段。</p>${button('rename-track', '名称与管理', 'pencil', 'soft-btn full-width')}<section><label class="form-label">本轨音色<select data-field="preset-select" aria-label="本轨音色">${(G.projectPresets ? G.projectPresets(project) : PRESETS).filter(x => t.kind === 'drum' ? x.engine === 'drum' : x.engine !== 'drum').map(x => `<option value="${esc(x.id)}" ${t.preset === x.id ? 'selected' : ''}>${esc(x.name)}</option>`).join('')}${(t.preset.startsWith('sample:') || G.resolvePreset(t.preset, project).missing) ? `<option selected value="${esc(t.preset)}">${esc(presetName(t))}</option>` : ''}</select></label>${button('open-sound', '打开音色工作台', 'wave', 'quiet')}${button('preview', '听一个音', 'play', 'quiet')}</section><section>${slider('本轨音量', 'track', 'volume', t.volume, 0, 1, .01, '', t.id)}${slider('左右位置', 'track', 'pan', t.pan, -1, 1, .01, t.pan === 0 ? '居中' : `${Math.round(t.pan * 100)}`, t.id)}<div class="mute-solo">${button('mute', '静音', '', t.mute ? 'active' : '', `data-id="${t.id}" aria-pressed="${t.mute}"`)}${button('solo', '只听', '', B.soloIds.includes(t.id) ? 'active' : '', `data-id="${t.id}" aria-pressed="${B.soloIds.includes(t.id)}"`)}</div></section><section><span class="eyebrow">所选片段</span><h3>${esc(p.name)}</h3><p>${p.bars} 小节 · ${p.notes.length} 个事件</p><p>${t.clips.filter(c => c.patternId === p.id).length} 处引用共享内容</p>${button('open-current', '打开片段', 'pencil', 'soft-btn full-width')}</section><section>${button('catalog', '打开模板库', 'folder', 'quiet')}${button('import-catalog', '导入素材包', 'upload', 'quiet')}</section><small class="version-label">声格 1.2 · 本地创作</small></aside>`;
 };
})(globalThis.GridTone ||= {});
