/** Single composition workspace. The lower editor is a panel, never a second page. */
(function(G){G.views||={};
 G.views.renderShell=function(C){
  const {project,S,B,engine,history,future,button,ib,esc,icon,renderEditor,renderArrange,renderMix,scrollKey}=C;
  const editor=()=>S.editorOpen?`<div class="dock-resize" role="separator" tabindex="0" aria-label="调整音符编辑器高度" aria-orientation="horizontal" aria-valuemin="240" aria-valuemax="900" aria-valuenow="${S.editorHeight}"></div><div class="creation-workspace" id="creation-workspace"><section class="studio-editor" style="height:${S.editorHeight}px" aria-label="音符编辑器">${renderEditor()}</section></div>`:'';
  const editbar=()=>`<div id="editbar-host">${G.views.renderEditBar(C)}</div>`;
  const panel=['creation','composer'].includes(S.rightPanel)?C.creationMarkup:C.inspectorMarkup||'';
  const compact=S.view==='arrange';
  const structureActions=()=>`${button('add-track','音轨','plus','quiet small-btn')}${button('new-blank-clip','空白音乐块','plus','quiet small-btn')}${button('structure-tools','编排工具','arrange','quiet small-btn')}${button('time-tools',project.bars+'小节 · 长度','range','quiet small-btn')}`;
  const identity=()=>`<div class="arrangement-identity"><h2>编排</h2><small>${project.tracks.length} 条音轨 · ${project.bars} 小节</small></div>`;
  const content=S.view==='mix'?`<section class="mix-workspace">${renderMix()}</section>`:`<section class="studio-arrangement" id="arrangement-pane"><div class="arrangement-command-deck">${`<header class="arrangement-structure" data-component="structure-module" aria-label="编排结构">${identity()}<div class="structure-actions">${structureActions()}</div></header>`}${!compact&&!(S.editorExpanded&&S.editorOpen)?editbar():''}</div>${renderArrange()}</section>${editor()}`;
  return `<main class="app-shell studio-shell legou-shell single-workspace unified-shell ${compact?'compact-workbench':''} ${S.editorExpanded&&S.editorOpen&&S.view!=='mix'?'editor-expanded':''}" style="--studio-dock-height:${S.editorHeight}px"><header class="topbar"><div class="brand-area"><button type="button" class="btn project-entry" data-size="small" data-variant="quiet" data-action="workspace-menu" aria-label="作品与设置" title="${esc(project.title)} · 作品与设置"><span class="brand-sign" aria-hidden="true"><i></i><i></i><i></i></span><b>乐构</b><span class="project-entry-title">${esc(project.title)}</span>${icon('down',12)}</button></div><div class="top-transport action-tray" data-component="action-tray" aria-label="播放控制">${button('play','',engine.playing?'pause':'play','play-btn',`data-density="compact" aria-label="${engine.playing?'暂停':'播放'}"`)}${ib('stop','停止 · 再按回曲首','stop','','secondary')}<label class="tempo"><input id="bpm" type="number" min="40" max="240" data-field="bpm" value="${project.bpm}" aria-label="速度 BPM"><span>BPM</span></label></div>${compact?`<div class="global-edit-module" ${S.rightPanel==='composer'?'inert':''}>${editbar()}</div>`:''}<div class="top-actions action-tray" data-component="action-tray" role="group" aria-label="作品操作">${ib('undo','撤销 · '+G.keymap.label('undo')+'','undo',history.length?'':'disabled')}${ib('redo','重做 · '+G.keymap.label('redo')+'','redo',future.length?'':'disabled')}${button('library-open','音乐模板','grid','quiet small-btn','data-kind="music"')}</div><nav class="workspace-tabs segmented-control" role="group" aria-label="工作视图">${button('view','编排','arrange',S.view==='arrange'?'active small-btn':'quiet small-btn','data-view="arrange"')}${button('view','混音','mix',S.view==='mix'?'active small-btn':'quiet small-btn','data-view="mix"')}</nav></header>
  ${G.missingResources(project).length?`<div class="missing-banner" role="status">部分音源待补齐 ${button('import-catalog','导入素材包','upload','quiet small-btn')}${button('open-sound','替代音色','wave','quiet small-btn')}</div>`:''}
  <div class="workspace-body"><div class="view-content" ${S.rightPanel==='composer'?'inert':''} data-scrollkey="${esc(scrollKey)}" data-workspace="${S.view}">${content}</div><aside id="creation-dock" class="creation-dock ${S.rightPanel==='composer'?'composer-wide':''}" aria-label="当前工具面板" ${panel?'':'hidden'}>${panel||''}</aside></div>
  ${C.shelfMarkup||''}<footer class="playback-footer"><div class="footer-loop">${button('loop','循环','loop',B.loop?'on soft-btn small-btn':'soft-btn small-btn',`aria-pressed="${B.loop}"`)}<div class="transport-loop"><input type="number" data-field="loop-from" aria-label="循环起始小节" min="1" max="${project.bars}" value="${(B.range?.[0]||0)/G.BAR+1}"><span>—</span><input type="number" data-field="loop-to" aria-label="循环结束小节" min="1" max="${project.bars}" value="${(B.range?.[1]||project.bars*G.BAR)/G.BAR}">${ib('clear-range','清除循环范围','close')}</div></div><div class="clock"><strong id="position">001 : 01 : 01</strong><small id="playback-label">${esc(G.playbackLabel(project,S,B))}</small></div>${button('clear-solo','听全曲','headphones','quiet small-btn')}<span id="storage-status" role="status" aria-live="polite"></span><span id="save-status-actions" class="save-status-actions" hidden>${button('retry-save','重试','save','quiet small-btn')}${button('export-project','备份','download','quiet small-btn','aria-label="下载作品文件备份"')}</span><span id="runtime-status"></span></footer></main>`;
 };
})(globalThis.GridTone||={});
