/** Sound browser: category × source, and explicit audition vs use. Views have no document writes. */
(function(G){'use strict';G.views||={};
 G.soundEngineLabel=p=>p.drumkitId==='expansion.kit.808'?'808 实机短采样':({'prism-ep':'双层 FM','prism-pluck':'弦建模','prism-modal':'模态共振','prism-bass':'滤波低音','prism-pad':'三层音垫','prism-lead':'滤波主音','prism-air':'气流 / 泛音',multisample:'多音高实录',fm:'FM 合成',harmonic:'泛音合成',organ:'风琴合成',drum:'鼓声合成',pad:'波形合成',sub:'波形合成',bass:'波形合成',sample:'我的采样','studio-va':'经典模拟','studio-fm4':'四运算器 FM','studio-wave':'AKWF 单周期合成'})[p.engine]||'合成音色';
 G.soundIcon=p=>p.category==='低音'?'bass':p.category==='键盘'?'piano':p.engine==='drum'?'drum':p.category==='氛围'?'wave':'melody';
 G.visibleSounds=function(project,S,t){
  const source=S.soundSource||'curated',family=G.studioFamilyOf?.(t.preset),related=family?new Set([...family.members,...(family.legacyMembers||[])]):null;return G.projectPresets(project).filter(p=>(t.kind==='drum'?p.engine==='drum':p.engine!=='drum')&&(source==='all'||source==='curated'&&(related?related.has(p.id):(p.id.startsWith('prism.')||p.engine==='multisample'))||source==='basic'&&!p.id.startsWith('prism.')&&p.engine!=='multisample')&&(S.tab==='全部'||p.category===S.tab)&&(p.name+' '+p.description+' '+(p.tags||[]).join(' ')).toLowerCase().includes(S.query.toLowerCase()));
 };
 G.views.soundCards=function({project,S,track,icon,esc,button}){
  const t=track();if(S.soundSource==='recorded'){
   return G.SAMPLE_BANKS.filter(p=>(S.tab==='全部'||p.category===S.tab)&&(p.name+p.description).includes(S.query)).map(b=>{const installed=!G.resolvePreset(b.id,project).missing;return `<article class="sound-card recorded-card ${t.preset===b.id?'selected':''}" data-sound-id="${b.id}"><div class="sound-card-top"><span class="sound-avatar">${icon(G.soundIcon(b),20)}</span><small>${esc(b.category)}</small><span class="source-badge">CC0</span></div><strong>${esc(b.name)}</strong><p>${esc(b.description)}</p><div class="sound-tags"><span>实录 · ${b.zones.length} 个音高</span><span>${installed?'已就绪':'首次联网载入'}</span></div><div class="sound-card-actions">${installed?button('sound-audition','试听','headphones','quiet small-btn',`data-id="${b.id}"`)+button('preset','使用','check','soft-btn small-btn',`data-id="${b.id}"`):button('load-sample-bank','载入音源','download','soft-btn',`data-id="${b.id}"`)}</div></article>`;}).join('')||'<p class="empty-state">这个分组暂时没有音源。</p>';
  }
  return G.visibleSounds(project,S,t).map(p=>`<article class="sound-card ${t.preset===p.id?'selected':''}" data-sound-id="${esc(p.id)}"><div class="sound-card-top"><span class="sound-avatar">${icon(G.soundIcon(p),20)}</span><small>${esc(p.category)}</small>${t.preset===p.id?'<span class="source-badge">本轨正在使用</span>':''}</div><strong>${esc(p.name)}</strong><p>${esc(p.description)}</p><div class="sound-tags">${(p.tags||[G.soundEngineLabel(p)]).slice(0,2).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="sound-card-actions">${button('sound-audition','试听','headphones','quiet small-btn',`data-id="${esc(p.id)}" aria-label="试听 ${esc(p.name)}"`)}${button('preset',t.preset===p.id?'已使用':'使用','check',t.preset===p.id?'quiet small-btn':'soft-btn small-btn',`data-id="${esc(p.id)}" aria-label="使用 ${esc(p.name)}"`)}<small>${esc(G.soundEngineLabel(p))}</small></div></article>`).join('')||'<p class="empty-state">没有匹配的声音，试试其他分组或清空搜索。</p>';
 };
 G.views.waveIllustration=()=>''; // A synthetic decorative waveform is not an audio measurement.
 G.views.auditionKeys=function(octave,button){const base=octave*12+12;let white=0;
  return `<div class="audition-keys" aria-label="点按琴键试音">${Array.from({length:13},(_,i)=>{const black=[1,3,6,8,10].includes(i);const pos=black?white-.32:white++;return button('audition-key',black?'':G.noteName(base+i),'',`audition-key ${black?'black-key':'white-key'}`,`data-pitch="${base+i}" style="--key-left:${pos*12.5}%" aria-label="试听 ${G.noteName(base+i)}"`);}).join('')}</div>`;
 };
 G.views.renderSoundParameters=function(C,{slots=false}={}){
  const {project,track,button,esc,slider}=C,t=track(),preset=G.resolvePreset(t.preset,project),asset=t.preset.startsWith('sample:')?project.assets[t.preset.slice(7)]:null;
  const kind=t.kind==='drum',kit=kind?G.resolveKit(t.drumkitId,project):null;
  const body=`<div data-component="sound-parameters-only"><p><strong>${esc(t.name)} · ${esc(preset.name)}</strong><br>只调整这条音轨的声音与效果，音符保持。每次调节可撤销。</p><div class="sound-parameter-columns"><section class="inspector-section"><h3>声音性格</h3>${slider('明亮度','sound','brightness',t.sound.brightness,0,1,.01,'',t.id)}${slider('起音','sound','attack',t.sound.attack,.002,2,.002,(t.sound.attack*1000).toFixed(0)+' ms',t.id)}${slider('尾音','sound','release',t.sound.release,.03,3,.01,t.sound.release.toFixed(2)+' s',t.id)}</section><section class="inspector-section"><h3>本轨效果</h3>${slider('混响空间','fx','reverb',t.fx.reverb,0,1,.01,'',t.id)}${slider('回声','fx','delay',t.fx.delay,0,1,.01,'',t.id)}${slider('饱和度','fx','drive',t.fx.drive,0,1,.01,'',t.id)}</section></div>${asset?`<section class="inspector-section"><h3>当前采样</h3><p>${esc(asset.name)}</p><label class="form-label">原始音高<select data-field="sample-root">${Array.from({length:128},(_,i)=>`<option value="${i}" ${asset.root===i?'selected':''}>${G.noteName(i)}</option>`).join('')}</select></label><label class="form-label">演奏方式<select data-field="sample-mode"><option value="pitched" ${asset.mode==='pitched'?'selected':''}>随音高变速</option><option value="oneshot" ${asset.mode==='oneshot'?'selected':''}>一次性播放</option></select></label></section>`:''}${kind?`<p class="field-note">当前鼓组：${esc(kit?.name||'标准鼓组')}。更换声音使用音色选择器，独立鼓件资源在声音资源中管理。</p>`:''}<p class="field-note">${esc(preset.origin||'乐构内置声音')} · ${esc(G.soundEngineLabel(preset))}</p></div>`;
  const actions=`${button('sound-test-current','试听调整','headphones','soft-btn',`data-track="${t.id}"`)}${button('close-modal','完成','','quiet')}`;
  return slots?{body,actions}:body+`<div class="modal-actions" data-dialog-actions>${actions}</div>`;
 };
 G.views.renderSound=function(C){const {project,S,track,button,icon,esc,slider,presetName,soundCards}=C,t=track(),p=G.presetById(t.preset,project),asset=t.preset.startsWith('sample:')?project.assets[t.preset.slice(7)]:null;
  const order=['键盘','拨弦','钟琴 / 敲击','低音','主音','管乐','氛围','鼓组'],all=G.projectPresets(project).filter(p=>t.kind==='drum'?p.engine==='drum':p.engine!=='drum');
  const source=S.soundSource||'curated',cats=source==='recorded'?[...new Set(G.SAMPLE_BANKS.map(x=>x.category))]:[...new Set(all.filter(p=>source==='all'||source==='curated'&&(p.id.startsWith('prism.')||p.engine==='multisample')||source==='basic'&&!p.id.startsWith('prism.')&&p.engine!=='multisample').map(x=>x.category))].sort((a,b)=>(order.indexOf(a)<0?99:order.indexOf(a))-(order.indexOf(b)<0?99:order.indexOf(b)));
  const internal=new Set(all.flatMap(p=>(p.zones||[]).map(z=>z.assetId))),custom=Object.entries(project.assets).filter(([id])=>!internal.has(id));
  const octave=S.keyOctave??(t.kind==='drum'?2:p.category==='低音'?3:4);
  const kit=t.kind==='drum'?G.resolveKit(t.drumkitId,project):null, boundRows=kit?.rows.filter(r=>r.source?.type==='sample'||r.source?.presetId).length||0;
  const kitNotice=boundRows?`<div class="kit-scope-note"><strong>${esc(kit.name)}</strong><p>${boundRows} 个鼓件绑定独立声音；本轨预设只影响未绑定的鼓件。更换整套鼓声请选鼓组。</p>${button('catalog-tab','选择鼓组','drum','soft-btn',`data-category="drumkits"`)}</div>`:'';
  return `${button('library-open','到完整声音库挑选','grid','soft-btn full-width','data-kind="sound"')}<div class="view-heading compact-heading"><div><h1>寻找一种声音</h1><p>先试听，再使用。更换音色影响本轨全部音乐块。</p></div><div class="heading-actions">${button('import-catalog','导入音色包','folder','quiet')}${button('record','录音','mic','soft-btn')}${button('import-sample','导入音源','upload','soft-btn')}</div></div>
  <div class="sound-layout"><section class="sound-library"><div class="sound-source-bar" aria-label="声音来源">${[['curated','精选声音'],['basic','基础合成'],...(t.kind==='drum'?[]:[['recorded','真实采样']]),['all','全部']].map(([id,label])=>button('sound-source',label,'',source===id?'active small-btn':'quiet small-btn',`data-source="${id}" aria-pressed="${source===id}"`)).join('')}<small>${source==='recorded'?'VSCO 2 CE · CC0 轻量选集':source==='basic'?'旧声音完整保留，已有作品音色保持原样':'独立发声算法 · 按乐器角色挑选'}</small></div>
  <div class="library-header"><div class="sound-tabs">${['全部',...cats].map(c=>button('sound-category',esc(c),'',S.tab===c?'active small-btn':'quiet small-btn',`data-category="${esc(c)}"`)).join('')}</div><label class="search-box">${icon('search',16)}<input type="search" placeholder="名称、性格、用途" value="${esc(S.query)}" id="sound-search" aria-label="搜索音色"></label></div>
  <div class="audition-settings"><span>${icon('headphones',14)} 比较试听</span><select data-field="audition-mode" aria-label="音色比较乐句">${(t.kind==='drum'?[['drum','同一段鼓点']]:[['melody','同一段旋律'],['chord','同一组和弦'],['bass','同一段低音']]).map(([id,n])=>`<option value="${id}" ${(S.auditionMode||'melody')===id?'selected':''}>${n}</option>`).join('')}</select><small>试听保留原作品；音量与效果采用统一设置。</small></div>
  <div class="sound-grid" id="sound-cards">${soundCards()}</div>
  ${custom.length?`<div class="custom-sounds"><h2>我的录音 <span>${custom.length}</span></h2><div class="sound-grid">${custom.map(([id,a])=>`<button class="sound-card" data-action="custom-preset" data-id="${esc(id)}"><strong>${esc(a.name)}</strong><p>${a.mode==='oneshot'?'一次性播放':'随音高演奏'} · ${G.noteName(a.root)}</p></button>`).join('')}</div></div>`:''}
  ${source==='recorded'?'<p class="library-note">这些音源由真实乐器录音制成。首次载入需要访问 GitHub 原始文件；选择后，轻量采样会随作品文件保存。此选集采用单力度、多音高映射，保留最长 6 秒原声，无自动循环；未包含原库全部力度层和演奏法。</p>':''}</section>
  <aside class="sound-inspector"><div class="inspector-top"><span class="eyebrow">${boundRows?'本轨默认音色':'本轨正在使用'}</span><h2>${esc(presetName(t))}</h2><p class="instrument-origin">${esc(G.soundEngineLabel(p))} · ${esc(t.name)}</p>${kitNotice}
  ${t.kind==='drum'?button('preview','敲一下鼓','drum','preview-btn'):G.views.auditionKeys(octave,button)+`<div class="keyboard-footer">${button('key-octave','−','','quiet',`data-delta="-1" aria-label="试音键盘低八度"`)}<small>C${octave}—C${octave+1} · 点按试音</small>${button('key-octave','+','','quiet',`data-delta="1" aria-label="试音键盘高八度"`)}</div>`}</div>
  <details class="sound-simple-adjustments" id="sound-adjustment-panel" ${document.querySelector('#sound-adjustment-panel')?.open?'open':''}><summary>微调当前声音</summary><div id="sound-parameters"><div class="inspector-section"><h3>声音性格</h3>${slider('明亮度','sound','brightness',t.sound.brightness)}${slider('起音','sound','attack',t.sound.attack,.002,2,.002,(t.sound.attack*1000).toFixed(0)+' ms')}${slider('尾音','sound','release',t.sound.release,.03,3,.01,t.sound.release.toFixed(2)+' s')}
  ${asset?`<label class="field-row">原始音高<select data-field="sample-root">${Array.from({length:73},(_,i)=>i+24).map(n=>`<option value="${n}" ${asset.root===n?'selected':''}>${G.noteName(n)}</option>`).join('')}</select></label><label class="field-row">演奏方式<select data-field="sample-mode"><option value="pitched" ${asset.mode==='pitched'?'selected':''}>随音高变速</option><option value="oneshot" ${asset.mode==='oneshot'?'selected':''}>一次性播放</option></select></label>`:''}</div>
  <div class="inspector-section"><h3>声音效果</h3>${slider('混响空间','fx','reverb',t.fx.reverb)}${slider('回声','fx','delay',t.fx.delay)}${slider('饱和度','fx','drive',t.fx.drive)}</div><p class="library-note">${esc(p.origin||'乐构内置合成声音')}</p></div></details></aside></div>`;
 };
})(globalThis.GridTone ||= {});
