(function(G){'use strict';
 class TemplateShelf{
  constructor(context,catalog){this.c=context;this.catalog=catalog;this.selected=null;this.pending=null;this.collapsed=false;try{this.preferences=JSON.parse(localStorage.getItem('legou.catalog.preferences'))||{};}catch{this.preferences={};}this.preferences.favorites||=[];this.preferences.recent||=[];this.filter=this.preferences.filter||'all';this.catalog.search=this.preferences.search||this.catalog.search;this.install();}
  save(){try{localStorage.setItem('legou.catalog.preferences',JSON.stringify(this.preferences));}catch{}}
  all(){const key=this.c.getProject().key+':'+G.catalogRevision();if(this.cache?.key===key)return this.cache.items;const items=[...G.catalogTemplates().map(t=>t.type==='song'?{...t,bars:t.project.bars}:t),...G.RECIPES.map(r=>({...r,type:'recipe',role:'song',bars:r.answer?8:4})),...G.PROGRESSIONS.map(r=>{const texture=G.generateProgression(r.id,{key:this.c.getProject().key,rhythm:'arp'}).template;return {...texture,id:texture.id+'.texture',name:r.name+' · 分解伴奏',role:'texture'};})];this.cache={key,items};return items;}

  item(id){return this.all().find(x=>x.id===id);}
  render(){const {button,esc}=this.c;
   if(this.collapsed)return `<aside class="template-shelf collapsed">${button('shelf-toggle','展开素材','grid','quiet')}</aside>`;
   const q=this.catalog.search.toLowerCase(),items=this.all().filter(t=>(this.filter==='all'||this.filter==='favorites'&&this.preferences.favorites.includes(t.id)||this.filter==='recent'&&this.preferences.recent.includes(t.id)||this.catalog.roleOf(t)===this.filter)&&(!q||[t.name,t.description,...(t.tags||[])].join(' ').toLowerCase().includes(q)));
   return `<aside class="template-shelf" aria-label="音乐素材架"><header><h2>素材</h2>${button('shelf-toggle','收起','','quiet')}</header><input type="search" data-field="shelf-search" aria-label="搜索素材架" placeholder="找一个声音的起点" value="${esc(this.catalog.search)}"><nav class="shelf-filters">${[['all','全部'],['song','整套'],['chords','和弦'],['drums','鼓点'],['melody','旋律'],['bass','贝斯'],['texture','伴奏'],['favorites','收藏'],['recent','最近']].map(([id,label])=>button('shelf-filter',label,'',this.filter===id?'active':'quiet',`data-filter="${id}"`)).join('')}</nav><p class="shelf-hint" role="status">${esc(this.message|| (this.selected?'已拿起素材：点编排空位，或放入当前乐句。':'试听、拖到空位，或选素材后点击落点。'))}</p>${this.selected?`<div class="shelf-placement">${button('shelf-current','放入当前乐句','plus','soft-btn')}${button('shelf-cancel','取消拿取','','quiet')}</div>`:''}<div class="shelf-cards">${items.map(t=>`<article class="shelf-card ${this.selected===t.id?'selected':''}" draggable="true" data-shelf-id="${esc(t.id)}"><button class="shelf-card-pick" data-action="shelf-pick" data-id="${esc(t.id)}"><strong>${esc(t.name)}</strong><small>${t.bars||4} 小节 · ${esc(t.type==='recipe'?'配套五轨':({song:'整曲',chords:'和弦',drums:'鼓点',melody:'旋律',bass:'贝斯',texture:'伴奏'})[this.catalog.roleOf(t)]||'音乐素材')}</small>${t.notes?G.ui.miniPattern(t,{kind:t.kind,color:'var(--brand)'},180,30):'<span class="shelf-ensemble-mark" aria-hidden="true">▰ ▰ ▰ ▰</span>'}</button><div>${button('shelf-preview','试听','play','quiet',`data-id="${esc(t.id)}"`)}${button('shelf-favorite',this.preferences.favorites.includes(t.id)?'已收藏':'收藏','','quiet',`data-id="${esc(t.id)}" aria-pressed="${this.preferences.favorites.includes(t.id)}"`)}</div></article>`).join('')||'<p>没有匹配的素材</p>'}</div><footer>${button('catalog','管理素材与音源','grid','quiet')}</footer></aside>`;
  }
  feedback(message){this.message=message;this.c.render();}
  cancel(){this.selected=null;this.selectedItem=null;this.pending=null;this.dragProject=null;this.clearGhost();this.c.playback.endAudition();this.message='';this.c.render();}
  choose(id){this.selectedItem=G.clone(this.item(id));this.selected=id;this.dragProject=this.c.getProject().id;this.message='已拿起「'+this.item(id).name+'」';this.c.render();}
  place(options){const p=this.c.getProject(),item=this.selectedItem||this.item(this.selected);if(!item)throw Error('请先选择素材。');if(this.dragProject!==p.id)throw Error('作品已切换，请重新拿起素材。');const result=G.planPlacement(p,item,options);this.pending={id:item.id,options,result,flow:new G.CandidateSession(p,'placement',options.clipId?{trackId:options.trackId,clipId:options.clipId}:{})};this.pending.flow.begin();this.pending.flow.ready([result]);return result;}
  async apply(options){try{const result=this.place(options),id=this.selected;const commit=await this.c.commit(result);if(commit?.ok===false)throw Error(commit.error.message);this.preferences.recent=[id,...this.preferences.recent.filter(x=>x!==id)].slice(0,20);this.save();this.pending=null;this.selected=null;this.message='已放入，可继续搭建或撤销。';this.c.render();}catch(e){this.feedback(e.message);}}
  current(at){const p=this.c.getProject(),s=this.c.getSession(),t=p.tracks.find(t=>t.id===s.trackId),pat=t.patterns.find(p=>p.id===s.patternId),item=this.selectedItem||this.item(this.selected);if(item.type!=='pattern')throw Error('整套素材请放到编排中的起始小节。');const start=Math.floor((at??s.cursor)/G.STEP)*G.STEP,end=start+item.bars*G.BAR,options={trackId:t.id,patternId:pat.id,clipId:s.clipId,start,end};const overlap=pat.notes.some(n=>n.start<end&&n.start+n.duration>start);if(end>pat.bars*G.BAR){this.longTarget={trackId:t.id,projectId:p.id};const clip=t.clips.find(c=>c.id===s.clipId),bar=Math.min(G.LIMITS.bars-item.bars,(clip?.bar||0)+pat.bars);this.c.openModal('素材比当前乐句更长',`<p>素材 ${item.bars} 小节，当前乐句 ${pat.bars} 小节。可以在明确的编排位置新建独立片段；原片段和其他共享实例保留。</p><label>新片段从第几小节开始<input id="shelf-new-bar" type="number" min="1" max="${G.LIMITS.bars-item.bars+1}" value="${bar+1}"></label><div class="modal-actions">${this.c.button('shelf-new-independent','新建独立片段','plus','dark-btn')}${this.c.button('close-modal','取消','','quiet')}</div>`);return;}
   if(overlap){this.replacement=options;this.replacementProject=p.id;this.replacementFingerprint=G.targetFingerprint(p,{trackId:t.id,clipId:s.clipId});this.c.openModal('替换这段范围？',`<p>从第 ${start/G.PPQ+1} 拍起放入 ${item.bars} 小节。当前实例会独立修改；范围外内容保留。</p><p>跨越边界的长音默认保留并阻止替换。可以扩大选区，或明确拆分。</p><div class="modal-actions">${this.c.button('shelf-replace','替换选区','check','dark-btn')}${this.c.button('shelf-split-replace','拆分边界长音并替换','','soft-btn')}${this.c.button('close-modal','取消','','quiet')}</div>`);}
   else void this.apply(options);
  }
  async preview(id){try{const p=this.c.getProject(),item=this.item(id);let result;if(item.type==='recipe')result={project:G.recipeProject(id)};else if(item.type==='song')result=G.applyTemplate(G.blankProject(),item);else{const current=p.tracks.find(t=>t.id===this.c.getSession().trackId);if(current?.kind===item.kind){const preview=G.clone(p);preview.tracks=[G.clone(current)];preview.tracks[0].clips=[];preview.bars=item.bars;result=G.applyTemplate(preview,item,{mode:'new',trackId:current.id,bar:0,applySound:false});}else result=G.applyTemplate(G.blankProject(),item,{mode:'new-track',bar:0});}await this.c.playback.audition(result.project,result.trackId?{kind:'pattern',trackId:result.trackId,patternId:result.patternId,ignoreMute:true}:{kind:'song'},'素材试听 · '+item.name);}catch(e){this.feedback(e.message);}}
  handleField(el){if(el.dataset.field!=='shelf-search')return false;this.catalog.search=el.value;this.preferences.search=el.value;this.save();this.c.render();return true;}
  handleAction(action,el){if(!action.startsWith('shelf-'))return false;try{if(action==='shelf-toggle'){this.collapsed=!this.collapsed;this.c.render();}if(action==='shelf-pick')this.choose(el.dataset.id);if(action==='shelf-cancel')this.cancel();if(action==='shelf-preview')void this.preview(el.dataset.id);if(action==='shelf-current')this.current();if(action==='shelf-new-independent'){if(this.c.getProject().id!==this.longTarget.projectId)throw Error('作品已切换，请重新拿取素材。');const bar=Number(document.querySelector('#shelf-new-bar').value)-1;this.place({trackId:this.longTarget.trackId,bar});this.c.closeModal();void this.apply({trackId:this.longTarget.trackId,bar});}if(action==='shelf-filter'){this.filter=el.dataset.filter;this.preferences.filter=this.filter;this.save();this.c.render();}if(action==='shelf-favorite'){const id=el.dataset.id;this.preferences.favorites=this.preferences.favorites.includes(id)?this.preferences.favorites.filter(x=>x!==id):[...this.preferences.favorites,id];this.save();this.c.render();}if(action==='shelf-replace'||action==='shelf-split-replace'){if(this.c.getProject().id!==this.replacementProject||G.targetFingerprint(this.c.getProject(),{trackId:this.replacement.trackId,clipId:this.replacement.clipId})!==this.replacementFingerprint)throw Error('目标已变化，请重新选择替换范围。');this.c.closeModal();void this.apply({...this.replacement,replace:true,splitBoundary:action==='shelf-split-replace'});}}catch(e){this.feedback(e.message);}return true;}
  clearGhost(){document.querySelectorAll('.shelf-drop-ghost').forEach(e=>e.remove());}
  location(e){const svg=e.target.closest('#note-grid');if(svg){const box=svg.getBoundingClientRect(),left=Number(svg.dataset.left),cw=Number(svg.dataset.cellWidth),x=e.clientX-box.left;if(x<left||e.clientY-box.top<28)return null;const s=this.c.getSession(),p=this.c.getProject(),t=p.tracks.find(t=>t.id===s.trackId),pat=t.patterns.find(p=>p.id===s.patternId),win=G.gridWindow(s,pat),start=Math.floor((x-left)/cw)*G.STEP+win.offset;return {svg,start,trackId:t.id,key:'grid:'+pat.id+':'+start,x:left+(start-win.offset)/G.STEP*cw,cw};}const lane=e.target.closest('.arrange-lane');if(!lane)return null;const box=lane.getBoundingClientRect(),bars=Number(lane.dataset.bars);return {lane,trackId:lane.dataset.track,bar:Math.max(0,Math.min(bars-1,Math.floor((e.clientX-box.left)/box.width*bars)))};}
  install(){
   document.addEventListener('dragstart',e=>{const card=e.target.closest('[data-shelf-id]');if(!card)return;this.nativeDragging=true;this.selected=card.dataset.shelfId;this.selectedItem=G.clone(this.item(this.selected));this.dragProject=this.c.getProject().id;e.dataTransfer.setData('text/plain',this.selected);e.dataTransfer.effectAllowed='copy';});
   document.addEventListener('dragover',e=>{if(!this.dragProject||!this.selected)return;const target=this.location(e);if(!target)return;e.preventDefault();const scroll=e.target.closest('[data-scroll]');if(scroll){const r=scroll.getBoundingClientRect();if(e.clientX>r.right-36)scroll.scrollLeft+=18;else if(e.clientX<r.left+36)scroll.scrollLeft-=18;}const item=this.selectedItem||this.item(this.selected),key=target.key||target.trackId+':'+target.bar;if(this.ghostKey===key&&document.querySelector('.shelf-drop-ghost'))return;this.ghostKey=key;this.clearGhost();if(target.svg){const g=document.createElementNS('http://www.w3.org/2000/svg','rect');g.setAttribute('class','shelf-drop-ghost');g.setAttribute('x',target.x);g.setAttribute('y',28);g.setAttribute('width',(item.bars||4)*16*target.cw);g.setAttribute('height',Number(target.svg.getAttribute('height'))-102);g.setAttribute('fill','var(--brand)');g.setAttribute('fill-opacity','.12');g.setAttribute('stroke','var(--brand)');g.setAttribute('stroke-dasharray','5 4');g.style.pointerEvents='none';target.svg.append(g);return;}const g=document.createElement('div');g.className='shelf-drop-ghost';g.textContent=item.name;g.style.left=target.bar/Number(target.lane.dataset.bars)*100+'%';g.style.width=(item.bars||4)/Number(target.lane.dataset.bars)*100+'%';target.lane.append(g);});
   document.addEventListener('drop',e=>{if(!this.dragProject)return;const target=this.location(e);this.clearGhost();if(target){e.preventDefault();if(target.svg){try{this.current(target.start);}catch(error){this.feedback(error.message);}}else void this.apply({trackId:target.trackId,bar:target.bar});}});
   document.addEventListener('dragend',()=>{this.nativeDragging=false;this.clearGhost();});
   // Native HTML dragging emits pointercancel when the browser takes over the pointer.
   document.addEventListener('pointercancel',()=>{if(this.nativeDragging)return;this.clearGhost();this.dragProject=null;});
   document.addEventListener('pointerdown',e=>{if(!this.selected)return;const target=this.location(e);if(!target?.svg)return;e.preventDefault();e.stopImmediatePropagation();try{this.current(target.start);}catch(error){this.feedback(error.message);}},true);
   document.addEventListener('click',e=>{if(!this.selected)return;const target=e.target.closest('.empty-bar');if(target){e.preventDefault();e.stopImmediatePropagation();void this.apply({trackId:target.dataset.track,bar:Number(target.dataset.bar)});}},true);
   document.addEventListener('keydown',e=>{if(e.key==='Escape'&&this.selected){e.preventDefault();this.cancel();}});
   window.addEventListener('blur',()=>{this.clearGhost();this.dragProject=null;});
  }
 }
 G.TemplateShelf=TemplateShelf;
})(globalThis.GridTone ||= {});
