/** Prism instrument voices. Original DSP implementations; old engine IDs keep their old renderer.
 * Each voice owns its sources via voiceTools, so preview/stop/export share one lifecycle.
 * “Modeled” instruments are explicitly labeled; no procedural sound is labeled recorded.
 */
(function(G){'use strict';
 const {clamp}=G, frequency=n=>440*2**((n-69)/12), caches=new WeakMap();
 function envelope(v,out,at,gate,release,peak,attack=.004,hold=1){
  const env=v.gain(0);env.connect(out);const a=Math.max(.002,Math.min(attack,gate*.4));
  env.gain.setValueAtTime(.00001,at);env.gain.linearRampToValueAtTime(peak,at+a);
  if(hold!==1)env.gain.exponentialRampToValueAtTime(Math.max(.00001,peak*hold),at+Math.min(gate,a+.2));
  env.gain.setValueAtTime(Math.max(.00001,peak*hold),at+gate);
  env.gain.exponentialRampToValueAtTime(.00001,at+gate+release);
  return env;
 }
 function setup(args,level=.25){
  const {graph,out,note,track,at,duration,preset}=args,v=G.voiceTools(graph,out),gate=Math.max(.018,duration),release=clamp(track.sound.release*preset.release/.32,.035,3),end=at+gate+release+.015;
  return {v,ctx:v.ctx,f:frequency(note.pitch),gate,release,end,amp:note.velocity*level*(preset.gain??1)};
 }
 function partialVoice(args){
  const {v,f,gate,release,end,amp}=setup(args,.4),{at,preset,track}=args;
  const profiles={glass:[[1,.72,2.1],[2.756,.3,.9],[5.404,.12,.5],[8.933,.065,.25]],wood:[[1,.9,.8],[3.98,.21,.2],[9.9,.06,.08]],kalimba:[[1,.85,1.6],[2.01,.2,.7],[5.02,.2,.14],[6.8,.035,.07]],vibes:[[1,.85,2.4],[4,.18,.45],[10,.07,.2]]};
  const parts=profiles[preset.profile]||profiles.glass;
  const gateEnv=envelope(v,args.out,at,gate,release,amp,Math.max(.002,track.sound.attack));
  let toneBus=gateEnv;
  if(preset.profile==='vibes'){
   toneBus=v.gain(.88);toneBus.connect(gateEnv);const lfo=v.add(v.ctx.createOscillator()),depth=v.gain(.12);
   lfo.frequency.value=5.4;lfo.connect(depth);depth.connect(toneBus.gain);v.source(lfo,at,end);
  }
  parts.forEach(([ratio,level,decay])=>{if(f*ratio>v.ctx.sampleRate*.46)return;const e=v.gain(0);e.connect(toneBus);e.gain.setValueAtTime(level,at);e.gain.exponentialRampToValueAtTime(.00001,at+Math.max(.05,Math.min(decay,end-at)));v.osc('sine',f*ratio,e,at,end);});
 }
 function pluckBuffer(ctx,pitch,profile){
  let cache=caches.get(ctx);if(!cache){cache=new Map();caches.set(ctx,cache);}const key=`${pitch}:${profile}`;if(cache.has(key))return cache.get(key);
  const rate=ctx.sampleRate,f=frequency(pitch),delay=Math.max(2,rate/f-.5),size=Math.ceil(delay)+3;
  const ring=new Float32Array(size),out=ctx.createBuffer(1,Math.ceil(rate*3.4),rate),d=out.getChannelData(0);
  let seed=(pitch*7919+77)>>>0;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296*2-1;};
  for(let i=0;i<size;i++)ring[i]=random();
  // A short spatial average models a softer excitation; decay is generated by a feedback loop.
  if(profile==='nylon')for(let i=0;i<size;i++)ring[i]=(ring[i]+ring[(i+1)%size]+ring[(i+2)%size])/3;
  const loss=profile==='muted'?.985:profile==='steel'?.9985:.997;
  let w=0,prev=0,dc=0,peak=0;
  for(let i=0;i<d.length;i++){
   const read=(w-delay+size)%size,j=Math.floor(read),a=read-j,x=ring[j]*(1-a)+ring[(j+1)%size]*a;
   const y=(x+prev)*.5*loss;prev=x;ring[w]=y;w=(w+1)%size;
   dc=dc*.997+x*.003;d[i]=x-dc;peak=Math.max(peak,Math.abs(d[i]));
  }
  if(peak>0)for(let i=0;i<d.length;i++)d[i]=d[i]/peak*.9*Math.min(1,i/40);
  if(cache.size>=48)cache.delete(cache.keys().next().value);cache.set(key,out);return out;
 }
 function pluckVoice(args){
  const {v,f,gate,release,end,amp}=setup(args,.52),{at,preset,track,note}=args;
  const src=v.add(v.ctx.createBufferSource());src.buffer=pluckBuffer(v.ctx,note.pitch,preset.profile);
  const body=v.add(v.ctx.createBiquadFilter());body.type='peaking';body.frequency.value=profileFreq(preset.profile);body.Q.value=.7;body.gain.value=3;
  const env=envelope(v,args.out,at,Math.min(gate,3.3),Math.min(release,.65),amp,Math.max(.002,track.sound.attack));
  src.connect(body);body.connect(env);v.source(src,at,Math.min(end,at+src.buffer.duration+.01));
 }
 function profileFreq(p){return p==='nylon'?280:p==='steel'?2200:600;}
 function tineVoice(args){
  const {v,f,gate,release,end,amp}=setup(args,.24),{at,preset,track,note}=args;
  const env=envelope(v,args.out,at,gate,release,amp,Math.max(.002,track.sound.attack),.55);
  const bell=preset.profile==='bell',reed=preset.profile==='reed';
  for(let i=0;i<2;i++){
   const car=v.add(v.ctx.createOscillator()),mod=v.add(v.ctx.createOscillator()),depth=v.gain(0),mix=v.gain(i?.24:.85);
   car.frequency.value=f;car.detune.value=i?2.3:-2.3;mod.frequency.value=f*(i?(bell?7:14):(reed?2:1));
   depth.gain.setValueAtTime(f*(i?.5:(reed?2.5:1.65))*note.velocity**1.6,at);
   depth.gain.exponentialRampToValueAtTime(f*.025,at+(i?.08:(bell?1.1:.65)));
   mod.connect(depth);depth.connect(car.frequency);car.connect(mix);mix.connect(env);v.source(car,at,end);v.source(mod,at,end);
  }
 }
 function analogVoice(args){
  const bass=args.preset.engine==='prism-bass';const {v,f,gate,release,end,amp}=setup(args,bass?.32:.21),{at,preset,track,note}=args;
  const pad=preset.engine==='prism-pad',env=envelope(v,args.out,at,gate,release,amp,pad?Math.max(.16,track.sound.attack):track.sound.attack,pad?.85:.58);
  const filter=v.add(v.ctx.createBiquadFilter());filter.type='lowpass';filter.Q.value=bass?1.8:.7;
  const open=bass?Math.min(6500,f*18):pad?4200:8000;
  filter.frequency.setValueAtTime(pad?480:open,at);filter.frequency.exponentialRampToValueAtTime(pad?2400:Math.max(100,f*(bass?2.5:4)),at+(pad?Math.min(gate,1.8):.2));filter.connect(env);
  const profile=preset.profile;
  if(bass){v.osc(profile==='round'?'triangle':'sawtooth',f,filter,at,end,.65);v.osc('sine',f/2,filter,at,end,.45);if(profile==='rubber')v.osc('square',f,filter,at,end,.14);}
  else if(pad){v.osc(profile==='choir'?'triangle':'sawtooth',f,filter,at,end,.35,-8);v.osc('sawtooth',f,filter,at,end,.35,8);v.osc('sine',f/2,filter,at,end,.3);}
  else{v.osc(profile==='pulse'?'square':'sawtooth',f,filter,at,end,.5,-3);v.osc('triangle',f*2,filter,at,end,.25,4);}
 }
 function airVoice(args){
  const {v,f,gate,release,end,amp}=setup(args,.31),{at,track,preset,note}=args;
  const env=envelope(v,args.out,at,gate,release,amp,Math.max(.055,track.sound.attack),.75);
  const ratios=preset.profile==='reed'?[[1,.75],[3,.19],[5,.08],[7,.035]]:[[1,.86],[2,.1],[3,.025]];
  for(const [r,l]of ratios)if(f*r<v.ctx.sampleRate*.46){const o=v.osc('sine',f*r,env,at,end,l);const lfo=v.add(v.ctx.createOscillator()),depth=v.gain(3.2);lfo.frequency.value=5.2;lfo.connect(depth);depth.connect(o.detune);v.source(lfo,at,end);}
  const noise=v.add(v.ctx.createBufferSource());noise.buffer=G.seededNoise(v.ctx,1);noise.loop=true;
  const filter=v.add(v.ctx.createBiquadFilter());filter.type='bandpass';filter.frequency.value=f*3;filter.Q.value=1.2;const breath=v.gain(.045*note.velocity);noise.connect(filter);filter.connect(breath);breath.connect(env);v.source(noise,at,end);
 }
 function drumVoice(args){
  const profile=args.preset.profile;if(!profile)return G.legacyDrumVoice(args);
  const {graph,out,note,at}=args,v=G.voiceTools(graph,out),{ctx}=v,vel=note.velocity*(args.preset.gain??1),p=note.pitch;
  function tone(f,decay,level,bend){const e=envelope(v,out,at,.006,Math.max(.02,decay),level*vel,.002);const o=v.osc('sine',f,e,at,at+decay+.025);if(bend)o.frequency.exponentialRampToValueAtTime(bend,at+Math.min(.13,decay*.7));}
  function noise(sec,hz,level,type='highpass',bursts=false){const n=v.add(ctx.createBufferSource()),filter=v.add(ctx.createBiquadFilter()),env=v.gain(0);n.buffer=G.seededNoise(ctx,1);filter.type=type;filter.frequency.value=hz;filter.Q.value=.65;n.connect(filter);filter.connect(env);env.connect(out);env.gain.setValueAtTime(Math.max(.00001,level*vel),at);if(bursts)[.012,.025,.038].forEach(t=>{env.gain.setValueAtTime(level*vel*.08,at+t-.003);env.gain.setValueAtTime(level*vel,at+t);});env.gain.exponentialRampToValueAtTime(.00001,at+sec);v.source(n,at,at+sec+.01);}
  const deep=profile==='deep',brush=profile==='brush';
  if(p===36){tone(deep?164:105,deep?.62:brush?.17:.27,deep?.82:.72,deep?43:58);noise(.011,brush?450:2300,.08,brush?'lowpass':'highpass');}
  else if(p===38){tone(brush?160:205,.1,brush?.1:.22,150);noise(brush?.32:.16,brush?2100:1650,brush?.25:.4,brush?'bandpass':'highpass');}
  else if(p===42||p===46||p===49){const sec=p===42?(brush?.075:.05):p===46?.32:1.05;if(deep){const env=envelope(v,out,at,.003,sec,.065*vel,.001),h=v.add(ctx.createBiquadFilter());h.type='highpass';h.frequency.value=6500;h.connect(env);[415,613,829,1047,1391,1741].forEach(f=>v.osc('square',f,h,at,at+sec+.04,.18));}else noise(sec,brush?4600:8500,brush?.16:.24);}
  else if(p===39)noise(brush?.16:.22,brush?1350:1850,.42,'bandpass',true);
  else if(p===45)tone(deep?165:218,.26,.5,deep?80:115);
  else if(p===37){tone(brush?520:910,.023,.32,700);noise(.015,1700,.1,'bandpass');}
 }
 function multisampleVoice(args){
  const {v,gate,release,amp}=setup(args,.54),{note,preset,assets,at}=args;
  const zones=preset.zones||[];const zone=zones.reduce((best,z)=>!best||Math.abs(z.root-note.pitch)<Math.abs(best.root-note.pitch)?z:best,null);
  const asset=zone&&assets.get(zone.assetId);if(!asset)throw Error('多采样音源未就绪。请补齐音源。');
  const src=v.add(v.ctx.createBufferSource()),rate=2**((note.pitch-zone.root)/12);src.buffer=asset.buffer;src.playbackRate.value=rate;
  const full=src.buffer.duration/rate,actualGate=Math.min(gate,Math.max(.005,full-.006)),rel=Math.min(release,Math.max(.003,full-actualGate));
  const env=envelope(v,args.out,at,actualGate,rel,amp*(zone.gain??1),Math.min(args.track.sound.attack,.04));src.connect(env);v.source(src,at,at+Math.min(full,actualGate+rel)+.012);
 }
 G.registerInstrument('prism-modal',partialVoice);G.registerInstrument('prism-pluck',pluckVoice);G.registerInstrument('prism-ep',tineVoice);G.registerInstrument('prism-bass',analogVoice);G.registerInstrument('prism-pad',analogVoice);G.registerInstrument('prism-lead',analogVoice);G.registerInstrument('prism-air',airVoice);G.registerInstrument('drum',drumVoice);G.registerInstrument('multisample',multisampleVoice);
 G.PRISM_ENGINES=['prism-modal','prism-pluck','prism-ep','prism-bass','prism-pad','prism-lead','prism-air','multisample'];
})(globalThis.GridTone ||= {});
